### ISSUE TITLE
Have you guys considered using recycling pattern

### ISSUE THREAD

**Issue by Jaafar-abusair** [archriss/react-native-snap-carousel#100]
Hi guys,

I'm sorry but it has a poor performance, have you considered using recycling pattern?

any idea to enhance it for now?

Thanks

**Comment by bd-arc** [comment]
Hi @Jaafar-abusair,

Yes, `ScrollView`'s performance (on which the carousel is built) is sub-par when displaying many items. That why we're currently working on implementing `FlatList` (see #73).

Stay tuned!
