### ISSUE TITLE
Creating an infinite slider?

### ISSUE THREAD

**Issue by stueynet** [archriss/react-native-snap-carousel#103]
Has anyone tinkered with making an infinite slider where when you reach the last slide it shows the first slide to the right?

**Comment by bd-arc** [comment]
Hi @stueynet,

There is a lot of discussion about that in #12, but as you can see in [this comment](https://github.com/archriss/react-native-snap-carousel/issues/12#issuecomment-308984390), it is not an easy feature to implement.

Your thoughts are welcome ;-)
