### ISSUE TITLE
How to disable the gesture? 

### ISSUE THREAD

**Issue by wangdicoder** [archriss/react-native-snap-carousel#104]
Hi, 

I want to use this component to achieve a function like a wizard, which means I don't want to use the figure to drag into next screen. I just want to use `snapToNext` to switch. I don't find an attribute can set it, so how can I implement this effect? 

Cheers

**Comment by bd-arc** [comment]
Hi @wangdicoder,

Currently, there is no way to disable gesture events. It's not a common use case, but I will look into adding a specific prop for that as soon as possible ;-)

**Comment by wangdicoder** [comment]
Yes, if you could implement this function, that will be great. I'm looking forward the good news. 👍👍👍 Thanks

**Comment by bd-arc** [comment]
Hi @wangdicoder,

In the end, there is no need for specific code: `ScrollView` already has the required prop [`scrollEnabled`](https://facebook.github.io/react-native/docs/scrollview.html#scrollenabled). Since `Carousel` inherits `ScrollView`'s props, you can use it right away ;-)

**Comment by RamMahe1110** [comment]
@bd-arc 
How do I implement that Scroll disabling feature in this code ?

`  <View style={{ alignItems: "center" }}>
          <Carousel
            style={{ marginRight: 10 }}
            layout={"default"}
            ref={c => {
              this.carousel = c;
            }}
            loop
            data={this.state.entries}
            renderItem={this._renderItem}
            sliderWidth={500}
            itemWidth={400}
            layout={"stack"}
            layoutCardOffset={18}
            loopClonesPerSide={1}
            onSnapToItem={index => {
              console.log(index);
            }}
          />
        </View>`

**Comment by bd-arc** [comment]
@RamMahe1110 `<Carousel scrollEnabled={false} />`

**Comment by shivam21197** [comment]
@bd-arc Not able to disable the scrolling using scrollEnabled={false}.

**Comment by Masadow** [comment]
@shivam21197 It works for me.

@bd-arc Should be added to the doc as I was about to drop this plugin until I saw that issue. I think it's a pretty common use case to do wizard with such plugins :)

**Comment by bd-arc** [comment]
@Masadow It's actually [part of the doc already](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#inherited-props), but I will add this prop's description [here](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior) so that users have a better chance of finding it :-)

**Comment by therbta** [comment]
> @Masadow It's actually [part of the doc already](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#inherited-props), but I will add this prop's description [here](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior) so that users have a better chance of finding it :-)

I was looking for this, thank you!
