### ISSUE TITLE
firstItem doesn't work as expected

### ISSUE THREAD

**Issue by gvenk** [archriss/react-native-snap-carousel#107]
I'm using the flatlist branch and it looks like the firstItem isn't working. If I set it to something different than 0, the list is displayed on the correct position, but the item isn't rendered. If I start scrolling the list, it appears. 

This doesn't happen on the iOS emulator, only on a real device. 

For the rest everything is working just fine! Great work on the FlatList implementation!

**Comment by gvenk** [comment]
It appears to be rather random, sometimes this will happen and sometimes not. Like it's some kind of timing issue?

**Comment by bd-arc** [comment]
Hi @gvenk,

I'm afraid that this is a bug of the `FlatList` component itself. See issues [#1831](https://github.com/facebook/react-native/issues/1831) and [#13316](https://github.com/facebook/react-native/issues/13316).

One thing that could help is adding `removeClippedSubviews={false}` to the `<Carousel />`. Unfortunately, it might take a toll on performance...

You can also try playing with the following props from [`VirtualizedList`](https://facebook.github.io/react-native/docs/virtualizedlist.html) and [`FlatList`](https://facebook.github.io/react-native/docs/flatlist.html)'s docs: `initialNumToRender`, `maxToRenderPerBatch`, `windowSize` and `updateCellsBatchingPeriod`.

Let me know if any of this tips helped regarding the issue!

**Comment by gvenk** [comment]
Thanks for the info. Unfortunately all the tips from the mentioned issues didn't result in a completely working list.  
I tricked the list by setting the firstItem to the actual firstitem - 1 and then use snapToItem() to scroll to the correct item. I did this in componentDidMount() but I had to use a timeout of 250msec otherwise it's not working.
Not a solution I'm totally happy with, but for now it's working.

**Comment by bd-arc** [comment]
@gvenk That's the unfortunate tradeoff of migrating to `FlatList`: some issues are not resolved yet. You idea is indeed a hack, but it seems like the only solution at the moment.

Note that the 250 ms timeout might be linked to the new prop [`apparitionDelay`](https://github.com/archriss/react-native-snap-carousel/tree/flatlist#behavior) (its default value being... 250 ms). You can change it to suit your needs.

**Comment by gvenk** [comment]
Yes, I'll experiment a bit with apparitionDelay, but for now it's working good enough I think.

Thanks!
