### ISSUE TITLE
Swipe gesture doesn't work on iOS

### ISSUE THREAD

**Issue by ImAtome** [archriss/react-native-snap-carousel#109]
When I'm swiping on the slide with the simulator or directly on a phone the slide doesn't slide as expected.Nothing happens.

```javascript
<View style={ styles.container }>
    <View style={ {flex:1, paddingTop:35, paddingBottom:15} }>
        <Carousel
            slideStyle={ {width:itemWidth} }
            sliderWidth={sliderWidth}
            carouselHorizontalPadding={ 40 }
            itemWidth={itemWidth}>
            <View style={ {flex:1, backgroundColor:'red'} }></View>
            <View style={ {flex:1, backgroundColor:'green'} }></View>
            <View style={ {flex:1, backgroundColor:'blue'} }></View>
        </Carousel>
    </View>
    <View style={ {height:50, borderWidth:1, borderColor: '#EEEEEE'} }></View>
</View>
```

When I use autoplay prop the slides swipe well, but automatically.

Does someone facing the same issue?

**Comment by bd-arc** [comment]
Hi @ImAtome,

This behavior is only supposed to happen if you set [`scrollEnabled`](https://facebook.github.io/react-native/docs/scrollview.html#scrollenabled) to `false`. Does the issue persist if you try [the example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

You can also try the soon-to-be-merged [`flatlist` branch](https://github.com/archriss/react-native-snap-carousel/tree/flatlist) and see if this solves your problem.

**Comment by ImAtome** [comment]
Hi @bd-arc ,

I fixed the problem by restarting the computer ... I don't understand why this happens sometimes.

Thank's for your help !
