### ISSUE TITLE
react native 0.42 error undefined is not an object (evaluating '_reactNative.ViewPropTypes.style')

### ISSUE THREAD

**Issue by sonnguyenit** [archriss/react-native-snap-carousel#112]
when i install this module with react native 0.42 then i get this error when run app:
 `undefined is not an object (evaluating '_reactNative.ViewPropTypes.style')`

**Comment by bd-arc** [comment]
You need to use at least version 0.44 of React Native (see #87).

I will commit next week a quick fix that allows for retro-compatibilty. But note that the plugin is soon going to be based on `FlatList`, which is pretty unstable before RN 0.45 anyway.
