### ISSUE TITLE
Is it possible to expose ‘onScrollBeginDrag’ also like ‘onScroll’ 

### ISSUE THREAD

**Issue by lazyelegance** [archriss/react-native-snap-carousel#113]

**Comment by bd-arc** [comment]
Hi @lazyelegance,

No problem to expose this callback if this can be helpful for you. I'll keep you posted.

**Comment by bd-arc** [comment]
Done in version 3.0.0. Make sure to read the [migration guide](https://github.com/archriss/react-native-snap-carousel/#migration-from-version-2x) ;-)
