### ISSUE TITLE
Different colors of active/inactive pagination dots

### ISSUE THREAD

**Issue by naffiq** [archriss/react-native-snap-carousel#114]
Hi and thanks for great plugin, it's very smooth! 

I'm currently working on project, where inactive pagination dots are different color from active ones.
The documentation has only opacity and scale for inactive ones, but I guess it would be great if we could change border radius, colors, margin, etc.

**Comment by bd-arc** [comment]
Hi @naffiq,

That's a good idea! What do you think about adding a prop `inactiveDotStyle` on top of `dotStyle`? Note that the changes you mention won't be animated.

**Comment by naffiq** [comment]
Yep, I understand that Animations are coded within `PaginationDot` component, and here comes another idea: how about adding ability to define dot component within `Pagination` component? 
It will allow developers to define their animations, without rewriting whole pagination code.

**Comment by bd-arc** [comment]
@naffiq Thank you very much for the PR!

Regarding the custom implementation, you're absolutely right: that's what I was planning to do. I've only added the component due to popular demand, and did not have time to update `Pagination`. I'll take a look at it as soon as possible.

**Comment by naffiq** [comment]
@bd-arc 

Cool, I might help if I'll have my hands free 🙌  I'm going to use this component again right after my current project, so it's also quite important for me 😄

Thank you!

**Comment by bd-arc** [comment]
I think that version `3.1.0` and the bunch of [new props](https://github.com/archriss/react-native-snap-carousel/blob/master/src/pagination/README.md) for `<Pagination />` will do the trick ;-)
