### ISSUE TITLE
Display `this._carousel.currentIndex`

### ISSUE THREAD

**Issue by mazing** [archriss/react-native-snap-carousel#116]
I don't understand `currentIndex`.

If I put it inside an `onPress` method, it works as it should, but I am not able to print it in a `<Text>`.

It says that `this._carousel` is undefined.

I am defining `this._carousel` with

    <Carousel
      ref={carousel => { this._carousel = carousel; }}
      ...

See the code below.

    elements.map((el, i) => {
      return (
        <TouchableOpacity onPress={() => alert(this._carousel.currentIndex)}>
          <Text>{this._carousel.currentIndex}</Text>
        </TouchableOpacity>
      )
    })

**Comment by NikitaKis** [comment]
I have the same issue too! Any ideas?

**Comment by benjdlambert** [comment]
Easiest solution is not to use the `ref`.

The reason it doesn't work, is the component itself doesn't get re-rendered, which means that it will always display the value at render time.

A better solution would be to use `onSnapToItem` to set state inside the component that uses the carousel. Something like this, (not tested, just writing from memory)

```js
class MyThing extends React.PureComponent {
  state = {
    currentIndex: 0,
  }
  changeIndex = (currentIndex) => {
    this.setState({ currentIndex });
  }
  render() {
    return (
      <View>
        <Carousel onSnapToItem={this.changeIndex} />
        <Text>{this.state.currentIndex</Text>
      </View>
  }
}
```

Think that should do it...

**Comment by NikitaKis** [comment]
Thank you! It works.

**Comment by bd-arc** [comment]
I didn't have time to answer this before today, so many thanks to @benjdlambert for shining in and explaining things thoroughly!

**Comment by ricarrrdoaraujo** [comment]
Thanks!

**Comment by hussainhspl** [comment]
Use **onBeforeSnapToItem** instead of onSnapToItem

**Comment by algate** [comment]
> Use **onBeforeSnapToItem** instead of onSnapToItem

The last project does not execute this programmatically；
