### ISSUE TITLE
Snap Carousel not working suddenly on Android

### ISSUE THREAD

**Issue by deadcoder0904** [archriss/react-native-snap-carousel#117]
I don't know what just happened
It was working for 2 days then suddenly stopped working yesterday
I can't drag even the 1st slider with mouse, I can only use keyboards `left` & `right` to move them & they are only moving halfways
Its working pretty well in iOS simulator

**Comment by bd-arc** [comment]
Hi @deadcoder0904,

From your description, I don't think it has anything to do with the plugin. You might want to check #109 for a similar issue (on iOS though) that has been fixed after restarting the computer...

**Comment by deadcoder0904** [comment]
Naah, been trying to figure the issue from 2 days so I restarted it multiple times...I thought u might know the issue...still its not working...Thanks anyways....I'll post the answer as soon as I'm done & Idk but its the issue with the `plugin` or `react-native` or `plugin + react-native + android`

**Comment by bd-arc** [comment]
I honestly don't see how the plugin could be the root of your issue, but I might have overlooked something.

My guess is that it has to do with React Native's `ScrollView` implementation. Still, would you mind trying with the [`flatlist` branch](https://github.com/archriss/react-native-snap-carousel/tree/flatlist)?

**Comment by deadcoder0904** [comment]
I will definitely use `flatlist` branch

I honestly don't know how the issue arose bcz its working smoothly in iOS Simulator & was working on Android Emulator & Genymotion but now its not even responding to the PanResponder API, i.e, whenever I click & slide there is no response in Android the Slides just go inside & if I set `autoplay={true}` it works on Android but whenever I click it goes inside ,i.e, it scales down

I think the issue might be with 2 libraries not working together well

I am using [react-native-infinite-scroll](https://github.com/lexor90/react-native-infinite-scroll) & inside of that this package is used like this

```
<InfiniteScrollView>
     <Carousel>
     </Carousel>
</InfiniteScrollView>
```

I think you are right about the `ScrollView` implementation
Hopefully will get it done by night 
I'll post the results later
Thanks again 👍

**Comment by deadcoder0904** [comment]
Confirming it works well standalone without using [react-native-infinite-scroll](https://github.com/lexor90/react-native-infinite-scroll)

**Comment by bd-arc** [comment]
Thanks for letting me know.

Unfortunately, there are a lot of issues with nested `ScrollViews`, so that's no surprise the two plugins aren't working well together.

**Comment by deadcoder0904** [comment]
Will `FlatList` inside `ScrollView` do the job ?

**Comment by bd-arc** [comment]
Not sure about that since `FlatList` [is based on `VirtualizedList` which, in turned, is based on `ScrollView`](https://github.com/facebook/react-native/blob/master/Libraries/Lists/FlatList.js#L290:L292).

**Comment by deadcoder0904** [comment]
Well that sucks as I need Nested Scroll Views on Android
I tried everything but nothing is helping out
I'm gonna post now on StackOverflow 😂

**Comment by deadcoder0904** [comment]
I am so stupiddd
Sorry for all the trouble
I didn't needed Nested Scrollviews, I just needed Horizontal Infinite Carousel which fetches data when the right end is reached
I used `onScroll` function on this package & did [this](https://stackoverflow.com/questions/41056761/detect-scrollview-has-reached-the-end/45836560) to detect horizontal scrollview & it works on Android & iOS smoothly

Thank you for everything ❤️ 
This package is awesome 😍  & plz release FlatList bcz my horizontal carousel is too damn big 😂

**Comment by bd-arc** [comment]
Thanks for the love ;-)

I'm going to release 3.0.0 pretty soon. Note that you will no longer need to detect the end of the `ScrollView` since `FlatList` has a [`onEndReached` prop](https://facebook.github.io/react-native/docs/flatlist.html#onendreached)...
