### ISSUE TITLE
Double rendered.

### ISSUE THREAD

**Issue by NicholasBertazzon** [archriss/react-native-snap-carousel#125]
Using your new update.
I don't know why, but my entries has doubled.
Example, if I have [{title:"Rome"},{title:"Paris},{title:"Berlin"}] as entries, the rendered items are: Rome - Paris - Berlin - Rome - Paris - Berlin.

Also, in the documentation, "inactiveSlideOpacity" is no more default:1.

**Comment by bd-arc** [comment]
Good catch regarding the default value `inactiveSlideOpacity`! I'll update it later, along with other changes.

Regarding your issue, can your try the [example](https://github.com/archriss/react-native-snap-carousel/tree/master/example) and see if it works as intended for you? I've used the new version in production with real data and did not have a "double rendering" issue...

**Comment by NicholasBertazzon** [comment]
I'm trying your project but it doesn't start.

Error:
(function (exports, require, module, __filename, __dirname) { import { AppRegistry } from 'react-native';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by bd-arc** [comment]
I must admit that I haven't tested the example on Android in a while; I was doing all my testing inside production apps. I'll make sure that the example can run on Android and get back to you real soon.

In the meantime, is it possible for you to try the iOS example?

**Comment by ragnorc** [comment]
Also experiencing double rendering.

**Comment by bd-arc** [comment]
Oh my gosh! I had some temporary code that I forgot to stash before publishing :-( Really sorry about that...

You can start using version `3.1.0` immediately, which should fix the issue. Can you confirm?

**Comment by ragnorc** [comment]
@bd-arc Don't mind! The bug is now gone. Thank you very much!
