### ISSUE TITLE
No dots visible

### ISSUE THREAD

**Issue by RWOverdijk** [archriss/react-native-snap-carousel#128]
I'm using the Pagination component but it's not showing.

```jsx
<Carousel
            data={this.onboarding}
            renderItem={this.renderItem}
            sliderWidth={Metrics.width}
            itemWidth={SLIDE_WIDTH}
            sliderHeight={250}
            onSnapToItem={index => this.setState({activeSlide: index})}
          >
            <Pagination
              dotsLength={this.onboarding.length}
              activeDotIndex={this.state.activeSlide}
              containerStyle={{ backgroundColor: 'hotpink', width: 200, height: 100 }}
              dotColor={'red'}
              inactiveDotColor={'green'}
              inactiveDotOpacity={0.4}
              inactiveDotScale={0.6}
            />
          </Carousel>
```

I added some containerStyle to see if it shows up at _all_ but it seems to not do that.

**Comment by RWOverdijk** [comment]
**Update:** It works when place outside of the Carousel. Inside, it just doesn't do anything.

**Comment by bd-arc** [comment]
Hi @RWOverdijk,

If you look at [component's doc](https://github.com/archriss/react-native-snap-carousel/blob/master/src/pagination/README.md#usage), you'll see that it is supposed to be rendered **outside** `<Carousel />`.

Moreover, the carousel component is now based on `FlatList`, which means it just won't render any direct children.

**Comment by RWOverdijk** [comment]
Ah... The indentation threw me off. My bad.
