### ISSUE TITLE
console.log('CUSTOM DATA', customData) ?

### ISSUE THREAD

**Issue by stueynet** [archriss/react-native-snap-carousel#129]
Removed `node_modules` and reinstalled latest package from scratch and yet is has the following at `node_modules/react-native-snap-carousel/src/carousel/Carousel.js`

![screen shot 2017-08-24 at 9 32 15 pm](https://user-images.githubusercontent.com/1100677/29695979-cb1b4d00-8913-11e7-9c68-455e0c35bced.jpg)

This causes the following in the console:

![screen shot 2017-08-24 at 9 33 12 pm](https://user-images.githubusercontent.com/1100677/29695996-e2f6e448-8913-11e7-9263-9c06503150c1.jpg)

**Comment by bd-arc** [comment]
Hi @stueynet,

This has been fixed in `3.1.0`. See [this comment](https://github.com/archriss/react-native-snap-carousel/issues/125#issuecomment-324640733).

**Comment by stueynet** [comment]
Thanks @bd-arc. Any idea why it still installs the old version?

**Comment by bd-arc** [comment]
That's pretty strange... I've just tried `npm i react-native-snap-carousel` in a new project and version `3.1.0` was properly installed.

Are you experiencing something different?
