### ISSUE TITLE
How to hide the underline of carousel?

### ISSUE THREAD

**Issue by 1325718308** [archriss/react-native-snap-carousel#13]
How to hide the underline of carousel?

**Comment by bd-arc** [comment]
@1325718308 Not so sure about what you mean. Can you provide a screenshot of the issue?

**Comment by 1325718308** [comment]
Thanks  I have already solved

**Comment by Symous** [comment]
it's better if you put your answer to slove this here :D 

showsHorizontalScrollIndicator={false}

to hide the scrollindicator.
