### ISSUE TITLE
RTL Snap isn't working properly

### ISSUE THREAD

**Issue by yogevlahyani** [archriss/react-native-snap-carousel#132]
I run "react-native-snap-carousel" version "3.1.0" and when I swipe with 3 slides, when i get to the last it's automatically jumps to the first, same with the first to the last.
another thing - my first slide isn't active by default.

All of the code I took from the usage instructions from this git repository..

https://drive.google.com/file/d/0B8qw0MlJdTYJRWgyNEVBOXFnOWs/view?usp=sharing

THANK YOU for the support :)

**Comment by bd-arc** [comment]
Hi @yogevlahyani,

I'm not surprised because RTL was based on a hack to counteract a React Native bug. I have to admit that I didn't test it with the recent updates (notably `FlatList` implementation).

I'll take a look at it as soon as I can ;-)

**Comment by yogevlahyani** [comment]
Thank you @bd-arc
If you could notify me on this issue it will be great!

**Comment by nichesoftgh01** [comment]
Is this working now?

**Comment by bd-arc** [comment]
Not yet. I'm working on a big refactoring of the plugin and this issue is going to be next in my todo list.

Don't worry, I'll keep you posted :-)

**Comment by bd-arc** [comment]
@yogevlahyani @nichesoftgh01 Good news: I've fixed the issues with RTL layouts! It's available in version `3.2.2`.

Make sure to read [this note](https://github.com/archriss/react-native-snap-carousel#rtl-support-experimental) from the doc ;-)

**Comment by yogevlahyani** [comment]
Works perfectly!! Thank you!

**Comment by DanGDroid** [comment]
sorry i tried on latest v. but RTL with over 30 items in the list does not function,
i tried older v 2.1 but no success

**Comment by bd-arc** [comment]
Hi @DanGDroid,

Can you please open a new issue? Make sure to read [the contribution guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) and to follow [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md).

Make also sure to test with different versions of React Native; this looks like a RN bug that might have been introduced or fixed recently.
