### ISSUE TITLE
[Android] Images won't show

### ISSUE THREAD

**Issue by itswaze** [archriss/react-native-snap-carousel#135]
Hey!

Images won't load on Android, but they do work perfectly on iOS.
I'm using FlatList.

```
          <Carousel
            data={this.state.imagens}
            sliderWidth={width}
            sliderHeight={(height > width) ? 250 : responsiveHeight(60)}
            itemWidth={width}
            slideStyle={{ width: width }}
            inactiveSlideOpacity={1}
            inactiveSlideScale={1}
            snapOnAndroid={true}
            enableMomentum={false}
            scrollEndDragDebounceValue={0}
            firstItem={this.state.index}
            removeClippedSubviews={false}
            onSnapToItem={(index) => this.setState({ activeSlide: index })}
            renderItem={({item, index}) => (
              <View style={{ height: height, justifyContent: 'center'}} key={index}>
                <Image
                  source={{uri: `URL/${item.Ficheiro}`, height:(height > width) ? 250 : responsiveHeight(60), width: (height > width) ? Dimensions.get('window').width : Dimensions.get('window').width}}>
                </Image>
             </View>
            )}
          />
```

**Comment by bd-arc** [comment]
Hi @itswaze,

In the [example](https://github.com/archriss/react-native-snap-carousel/tree/master/example), remote images are displayed without issues. It has been tested on both iOS and Android.

Can you try it and let me know if it works for you?

**Comment by itswaze** [comment]
@bd-arc The example works perfectly...
It's something on my end then.

**Comment by bd-arc** [comment]
If you look at the dedicated [React Native issues](https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=android%20image%20not%20rendered%20), it's apparently a common problem. Hope you'll find something useful there!

**Comment by henninghall** [comment]
Make sure you haven't saved images in .psd format but with another file extension, i.e .png. Those will render perfectly on ios but are inivisible on Android.
