### ISSUE TITLE
Customise each card of the carousel

### ISSUE THREAD

**Issue by bozzmob** [archriss/react-native-snap-carousel#14]
This is the BEST ever carousel for React Native I've ever seen or used till date. Looks amazing and a lot promising.

How about exposing a way to customize each card in the carousal. We can have say many layouts predefined and the developer can use the layout that suits his/her requirement.

I can send a PR soon once I get more hands on.

**Comment by bd-arc** [comment]
@bozzmob Thank you for the kind words. Regarding your suggestion, it shouldn't be to complicated. I suppose that we could create another method besides `renderItem()` that would just loop through an array of custom components.
To be honest, we are a bit short on time at the moment to implement it, but you are more than welcome to submit a PR :)
