### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by asantos00** [archriss/react-native-snap-carousel#141]
Hi, at first good job with this package, it definitely simplifies the usage of a carousel without having to directly handle FlatList.

I have a question regarding the lazy loading of the items, does this package renders all the steps on the first render? or only when needed? 

Thanks!

**Comment by edo1493** [comment]
Hey @asantos00, the package is build on top of a FlatList, with a windowSize, so the answer is no. It doesn't render them all at first.

**Comment by jordenchang55** [comment]
To implement lazy loading, I found [this answer](https://stackoverflow.com/questions/47218953/load-only-visible-images-in-flatlist-react-native#answer-49405408) on SO.
And it works for me to render image lazily by adding both `windowSize` and `initialNumToRender` into props.
```javascript
<Carousel
          data={data}
          initialNumToRender={3}
          windowSize={3}
          renderItem={this.renderItem}
          sliderWidth={window.width}
          itemWidth={window.width * 0.79}
        />
```
