### ISSUE TITLE
Option to render a React Component when data has no items?

### ISSUE THREAD

**Issue by jarvisluong** [archriss/react-native-snap-carousel#142]
Hi! Should this library have an option that does allow us to render something when there isn't any item?

**Comment by bd-arc** [comment]
Hi @jarvisluong,

Well, I don't think that this should be handled by the component itself since it would mess with the rendering logic of the `FlatList`. Instead, I recommend you to settle for something along those lines:

```
get loader () {
    return (
        <ActivityIndicator size={'small'} />
    );
}

get carousel () {
    const { items } = this.state;
    return (
        <Carousel data={items} />
    );
}

render () {
    const { items } = this.state;
    return !items.length ? this.loader : this.carousel;
}
```
