### ISSUE TITLE
Not rendering the cards in carousel correctly.

### ISSUE THREAD

**Issue by gauravdhiman** [archriss/react-native-snap-carousel#143]
I am using [react-native-snap-carousel][1] NPM package with [NativeBase][2] in a react-native app. I am able to load the page successfully but the carousel is not showing up the children components as expected. Cards in Carousel are rendering very small (very small height, not visible clearly) 

If I use the card component in `<ListItem>` component of NativeBase, the cards come up perfectly fine, but when use the same card component under carousel component, cards are messed up. Most probably it something related to styles of carousel children component.

This is how carousel looks like on Android (not tested on iOS):
[![enter image description here][3]][3]

I tried to see the properties of Carousel component and after setting `minHeight` for one of the inner components of Carousel, I was somewhat able to see the card but that too was not perfect. Here is the snapshot of property that I manipulated.
![react-native-snap-carousel-issue](https://user-images.githubusercontent.com/5612223/30241814-9659f200-953f-11e7-8e76-70592c7283f0.png)

Below is the code.

**BusinessCarousel.js**

    import React, { Component } from 'react';
    import { Dimensions } from 'react-native';
    import { Text, View } from 'native-base';
    import Carousel from 'react-native-snap-carousel';
    import BusinessCard from './card';
    
    export class BusinessCarousel extends Component {
      _renderItem({ item, index }) {
        return <BusinessCard business={item} />;
      }
    
      render() {
        const businesses = [
          {
            name: 'business 1',
            details:
              'Business 1 details Business 1 details Business 1 details Business 1 details Business 1 details ',
            address: {
              fullAddress: 'some address'
            }
          },
          {
            name: 'business 2',
            details:
              'Business 1 details Business 1 details Business 1 details Business 1 details Business 1 details ',
            address: {
              fullAddress: 'some address'
            }
          },
          {
            name: 'business 3',
            details:
              'Business 1 details Business 1 details Business 1 details Business 1 details Business 1 details ',
            address: {
              fullAddress: 'some address'
            }
          }
        ];

        return (
            <Carousel
              ref={c => {
                this._carousel = c;
              }}
              data={businesses}
              renderItem={this._renderItem}
              sliderWidth={Dimensions.get('window').width}
              itemWidth={Dimensions.get('window').width * 0.8}
              containerCustomStyle={{ overflow: 'visible' }}
              contentContainerCustomStyle={{ overflow: 'visible' }}
            />
        );
      }
    }

**BusinessCard (card.js)**

    import React, { Component } from 'react';
    import {
      Card,
      CardItem,
      Left,
      Right,
      Thumbnail,
      Image,
      Text,
      View,
      Button,
      Body,
      Icon
    } from 'native-base';
    
    export default class BusinessCard extends Component {
      _getLogoURL() {
        const { business } = this.props;
        if (business.logo && business.logo.url) return { uri: business.logo.url };
        return require('../../public/no-image-available.png');
      }

      render() {
        const { business } = this.props;
        return (
          <Card>
            <CardItem>
              <Left>
                <Thumbnail source={this._getLogoURL()} />
                <Body>
                  <Text>{business.name}</Text>
                  <Text note numberOfLines={1}>
                    {(business.address && business.address.fullAddress) || ''}
                  </Text>
                </Body>
              </Left>
              <Right>
                <Icon name="create" />
              </Right>
            </CardItem>
            <CardItem>
              <Body>
                <Text>{business.details}</Text>
              </Body>
            </CardItem>
          </Card>
        );
      }
    }

  [1]: https://www.npmjs.com/package/react-native-snap-carousel
  [2]: https://nativebase.io/
  [3]: https://i.stack.imgur.com/pNIEo.png

**Comment by bd-arc** [comment]
Hi @gauravdhiman,

While not required, I would recommend defining your carousel's height, particularly when that much nesting is involved.

Is there a specific height you're after or are you trying to pass down something like `{ flex: 1 }`?

**Comment by gauravdhiman** [comment]
@bd-arc thanks for response. I will try that, but please let me know how to define height of Carousel that you are asking for. Please give some example. I gave my code, can you give example, based on that?

**Comment by bd-arc** [comment]
If you're going for a flexible height, you could try the following:
```
<Carousel
    // other props
    containerCustomStyle={{ flex: 1, backgroundColor: 'lightcoral' }}
    slideStyle={{ flex: 1, backgroundColor: 'gold' }}
 />
```
This should allow you to see the space reserved for carousel's slides.

Then, you need to make your `<Cards />` fill up this space. I've never used Native Base, so maybe nothing else is required to make it work. Can you share a screenshot of the end result?

**Comment by gauravdhiman** [comment]
@bd-arc thanks for response.

I applied below properties to `<Carousel>` component. That started showing the cards under carousel but still the height of slider is less than height of cards - you can see the white space below carousel, not sure what that is and why carousel is not covering that.

Please see below screenshot.
![card-carousel](https://user-images.githubusercontent.com/5612223/30364981-2eb92a9c-981b-11e7-9427-f98615b586d9.png)

Few more things:
1. how to make cards center-align in respect to slider. Want to show main card inside and some part of adjacent card on both sides. Something as shown for this [react-native component](https://www.npmjs.com/package/react-native-card-carousel)
2. the transitions on Android are not smooth. If we transition fast from lest to right, it quickly moves to first element (in reverse order).

**Comment by bd-arc** [comment]
1. To achieve this you just need to specify an `itemWidth` smaller than your `sliderWidth`. In your example, you could try `itemWidth={ width * 0.75 }`. I would also get rid of `contentContainerCustomStyle={{ minHeight: 800 }}`.

2. I've just released [version `3.2.0`](https://github.com/archriss/react-native-snap-carousel/releases/tag/v3.2.0) which should help with Android transitions. There are a lot of issues at stake regarding Android feeling, but it all comes down to React Native's implementation. In the near future, I'll be working on a custom scroller implementation to improve carousel's behavior.

If you have trouble implementing the carousel, I would recommend starting with [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example) and building up for there, one component at a time (starting with your cards for example).

**Comment by gauravdhiman** [comment]
I want to try example given in your repo. When I run `npm start` in `example` folder, below out I can see on terminal, but how to load an app in Android emulator or real Android mobile device ?

```sh
~/proj/node/rn/react-native-snap-carousel/example$ npm start

> example@0.4.0 start /home/gauravdhiman/proj/node/rn/react-native-snap-carousel/example
> node node_modules/react-native/local-cli/cli.js start

Scanning 481 folders for symlinks in /home/gauravdhiman/proj/node/rn/react-native-snap-carousel/example/node_modules (3ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /home/gauravdhiman/proj/node/rn/react-native-snap-carousel/example 


React packager ready.

Loading dependency graph, done.
```

**Comment by bd-arc** [comment]
Well, it's a barebone React Native project and, as such, following [the getting started guide](https://facebook.github.io/react-native/docs/getting-started.html) is all that is required (make sure to check tab "Building Projects with Native Code").

If everything is properly configured on your end, running `react-native run-android` or `react-native run-ios` is all that is required for the local server to start and the app to be installed on the first device or emulator that is seen.

I'll make sure to add a README to the example.

**Comment by gauravdhiman** [comment]
I tried your example components with fresh `CRNA` project. Its coming up perfectly fine. Android transitions are still junky.

When I replaced you `parallax` images with my `BusinessCard` component (which is based on NativeBase) - the cards are rendering properly but their alignment is bit on right side, they are not centrally aligned. May be the reason for that is [NativeBase `Card` component](http://docs.nativebase.io/Components.html#card-showcase-headref). I thing `Card` component take full width of screen, so even if the container component is of lesser width, `Card` component still takes full width of screen and as  result it bit right aligned. See the screenshot.

![example](https://user-images.githubusercontent.com/5612223/30468863-756ae7a4-99a2-11e7-9492-97843e7ea605.png)

Well thanks for your help. I will choose between either your component or [this one](https://www.npmjs.com/package/react-native-card-carousel) - this too is good, but not so configurable as your component.

**Comment by bd-arc** [comment]
@gauravdhiman You're welcome!

Regarding slides' alignment, you might be spot on. Still, what `itemWidth` have you specified? Also, don't you have the liberty the customize `Card` component's width?

Regarding Android transitions, make sure to take a look at [this note](https://github.com/archriss/react-native-snap-carousel/#android-performance). TLDR: always test carousel's performance in a production build as dev mode really impairs it.
