### ISSUE TITLE
Carousel Component ref getting null for small instance on re render

### ISSUE THREAD

**Issue by pritishvaidya94** [archriss/react-native-snap-carousel#144]
![simulator screen shot sep 11 2017 10 51 49 am](https://user-images.githubusercontent.com/26863724/30259525-688732ce-96df-11e7-9428-589c05c87a33.png)
Hello,
If I try to do a re render to the carousel using the same page, the ref gets null for a small instance and throws this error. But this does not happen in native FlatList.

![screen shot 2017-09-11 at 10 55 53 am](https://user-images.githubusercontent.com/26863724/30259616-e24d76b8-96df-11e7-8286-1e049de9c939.png)

**Comment by bd-arc** [comment]
Hi @pritishvaidya94,

Can you provide a simple test case? Because I'm not able to reproduce the issue...

**Comment by pritishvaidya94** [comment]
Hello @bd-arc,
I have the code in the following way,

**Main Screen**
`render () {
renderCarousel = (data) => {
    return (
      <Carousel
        ref={(c) => { 
        console.log('Checking Callback Ref' + c)
        this._carousel = c }}
        data={data}
        renderItem={this._renderItemWithParallax}
        sliderWidth={width}
        itemWidth={itemWidth}
        hasParallaxImages
        slideStyle={{flex: 1}}
        removeClippedSubviews={false}
      />
    )
  }
}`

and then navigating to another component say **Component Screen** containing another carousel and  a button on one of its slides which redirects to **Main Screen** with different data props causing this error to generate.

Thanks.

**Comment by bd-arc** [comment]
Do you have the same issue with only one `<Carousel />`? With a button that triggers a prop update for example...

I would gladly take a look at the issue, but I need to be able to reproduce it. If you could modify [the example](https://github.com/archriss/react-native-snap-carousel/tree/master/example) and share it on a public repo, I'll then be able to investigate ;-)

**Comment by pritishvaidya** [comment]
Hello @bd-arc ,
I have added you as a collab in my repo.A simple test case would be to checkout branch **react-native-carousel-demo** and search **Doteysir** in the loginscreen as shown in the screenshot.

![screenshot_3](https://user-images.githubusercontent.com/19945677/30298277-7294dc38-9768-11e7-94fe-ab26ef5a0bcf.png)

and navigate to friends tab,  and click **Get Info**.It would show the error.

Thanks

**Comment by bd-arc** [comment]
@pritishvaidya Thanks for trusting me with your private repo! I'll take a look at it as soon as possible.

It's good to know that the PR fixed the issue since I'm currently working on a big refactoring that includes a fix like this one. Hopefully, this will also enhance carousel's overall feeling, especially on Android (even though I have absolutely no control over the `scrollToIndex()` duration which results, as you've experienced, in a quite brutal animation on Android).

I'll keep you posted!

**Comment by pritishvaidya94** [comment]
@bd-arc , yes thanks for the update, you may close this issue if necessary.

**Comment by bd-arc** [comment]
Hey @pritishvaidya,

I've just released [version `3.2.0`](https://github.com/archriss/react-native-snap-carousel/releases/tag/v3.2.0) which should solve your issue. Can you confirm?

**Comment by pritishvaidya** [comment]
@bd-arc  yes, it works now in version 3.2.1, Thanks !
