### ISSUE TITLE
Best way to access Navigation prop with renderItem function

### ISSUE THREAD

**Issue by pcooney10** [archriss/react-native-snap-carousel#146]
Hi, this project looks awesome but I had a quick question about the new `renderItem` function. 

I would like to pass the navigation prop down to my individual `SliderEntry` items, but can't seem to find the best way to do so. I tried doing something like [this](https://github.com/react-community/react-navigation/issues/2135#issuecomment-315247220), but the `renderItem` function in this example doesn't seem to take any other arguments.  I am working off of the example in this repo.

**Comment by bd-arc** [comment]
Hi @pcooney10,

Well, you need to create a custom function that "extends" `renderItem()`. If you take a look at [the source code of the plugin](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L685:736), you'll see that it's exactly what I've done.

My answer to [this SO question](https://stackoverflow.com/a/45995946/8412141) might also help you figuring it out.

Hope that helps!

**Comment by lucienboillod** [comment]
@pcooney10 I'm facing the same problem, did you manage to fix it using @bd-arc method ?

**Comment by jordangrant** [comment]
@pcooney10 @lucienboillod Hey guys, here's my solution for this:

In your Carousel:

```
<Carousel
    data={image1}
    renderItem={this._renderItem.bind(this)}   //<------
    sliderWidth={equalWidth2}
    itemWidth={equalWidth5}
  />
```
Adding the bind allows the _renderItem function to understand what "this" is (in this.props.navigation.)

In the renderItem function:

```
_renderItem ({item, index}) {
        return (
            <SliderEntry
              data={item}
              navigation={this.props.navigation}   //<-------
            />
        );
    }
```
And inside SliderEntry.js:

```
export default class SliderEntry extends Component {

    static propTypes = {
        data: PropTypes.object.isRequired,
    };

    render () {
        const { data: { title, subtitle, illustration}, navigation } = this.props;    //<------

        return (
          <TouchableOpacity
          activeOpacity={1}
          style={styles.slideInnerContainer}
          onPress={() => navigation.navigate('Feed')}  //<------- now you can use navigation
          >
```
Hope this helps!

**Comment by pcooney10** [comment]
Hey @lucienboillod, I didn't see your message for some reason but I ended up using the `withNavigation` HOC from react-navigation: https://github.com/react-community/react-navigation/blob/master/docs/api/withNavigation.md.  I wrapped the equivalency of `SliderEntry` above.

@jordangrant's solution seem like it might be better though, thanks @jordangrant !

**Comment by koswarabilly** [comment]
@pcooney10 can you provide example, because @jordangrant 's code work for me

**Comment by pcooney10** [comment]
Adapting the example above:
```js
<Carousel
    data={image1}
    renderItem={this._renderItem}   //<------
    sliderWidth={equalWidth2}
    itemWidth={equalWidth5}
  />
```
```js
_renderItem ({item, index}) {
        return (
            <SliderEntry
              data={item}
              index={index}
            />
        );
    }
`

```js
import { withNavigation } from 'react-navigation'

class SliderEntry extends Component {

    static propTypes = {
        data: PropTypes.object.isRequired,
    };

    render () {
        const { data: { id, title, subtitle, illustration}, navigation } = this.props;    //<------

        return (
          <TouchableOpacity
          activeOpacity={1}
          style={styles.slideInnerContainer}
          onPress={() => navigation.navigate('Feed', {id: id})}  //<------- 
          >

export default withNavigation(SliderEntry)
```

**Comment by fachrinfl** [comment]
hey can help me, i want to send props navigation from wix react-native-navigator

**Comment by koswarabilly** [comment]
@fachrinfl `const { data: { title, icon, screen}, even, navigate} = this.props;` . it must have been `navigator` as the props not the `navigate` isn't it?

**Comment by fachrinfl** [comment]
@koswarabilly when i tried using this.props.navigator directly , the result is still 'TypeError: undefined is not an object (evaluating 'this.props.navigator')'

**Comment by koswarabilly** [comment]
```
render () {
        const { data: { title, icon, screen}, even, navigate} = this.props;

        ...
```

in that code the `navigate` should change to `navigator` isn't it? @fachrinfl

**Comment by fachrinfl** [comment]
```
render () {
        const { data: { title, icon, screen}, even, navigator} = this.props;

        return (
            <TouchableOpacity
                activeOpacity={0.8}
                onPress={() => navigator.push({
                    title: 'Detail Menu',
                    screen: 'Ksei.DetailMenu',
                    animated: true,
                    animationType: 'fade'
                })}
            >
                <View
                    style={styles.slideInnerContainer}
                >
                    <View style={[styles.imageContainer, even ? styles.imageContainerEven : {}]}>
                        { this.image }
                        <View
                            style={styleIn.mainContent}>
                            <Image
                                source={icon}
                                style={styleIn.image}
                            />
                            <Text style={styleIn.textTitle}>{title}</Text>
                        </View>
                    </View>
                </View>
            </TouchableOpacity>
        )
    }
```

@koswarabilly i tried changing with navigator but eror is 

```
undefined is not an object (evaluating 'navigator.push')
```

**Comment by koswarabilly** [comment]
@fachrinfl what library are you using? if you are using react-navigation then`navigator.push` is not a correct syntax. you should change `navigator.push `to `navigator.navigate`

**Comment by fachrinfl** [comment]
@koswarabilly i used library 'https://wix.github.io/react-native-navigation/', this library using 'this.props.navigator.push' to move screen

**Comment by d41z** [comment]
hey @pcooney10 if I want to add an image where it is? into of SliderEntry?
I wait for your answer thanks.

**Comment by pedrocardoz0** [comment]
Idk, for me appears 'navigation.navigate' is not an object

**Comment by algarcia-vector** [comment]
I used this to make it work:

```
import {useNavigation} from '@react-navigation/core';

const OtherCustomersHaveContet = ({item, index}: any) => {
  return <Prueba item={item} index={index} />;
};

const Prueba = ({item, index}: any) => {
  const navigation = useNavigation();
  return (
    <TouchableOpacity
      onPress={() =>
        navigation.navigate('Analisis', {
          nombreEmisora: item.ticker,
          descripcionEmisora: item.name,
        })
      }
      style={styles.container}
      key={index}>
    </TouchableOpacity>
  );
};

const OtherCustomersHave = () => {
  const [index, setIndex] = React.useState(0);
  const isCarousel = React.useRef(null);
  const [recomendacionAnalista, setRecomendacionAnalista] = useState([]);
  
  return (
    <View style={{backgroundColor: 'white'}}>
      <Text style={{textAlign: 'center', fontWeight: 'bold', fontSize: 18}}>
        Otros Clientes Tienen
      </Text>
      <View style={{height: 220, marginBottom: -10}}>
        <Carousel
          layout={'default'}
          layoutCardOffset={9}
          ref={isCarousel}
          data={recomendacionAnalista}
          renderItem={OtherCustomersHaveContet}
          sliderWidth={SLIDER_WIDTH}
          itemWidth={ITEM_WIDTH2}
          onSnapToItem={index => setIndex(index)}
          useScrollView={true}
          inactiveSlideOpacity={1}
        />
      </View>
    </View>
  );
}
export default OtherCustomersHave;
```


Hope it helps
