### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jeffreyffs** [archriss/react-native-snap-carousel#148]
Hey there,

Awesome looking component here. I was wondering what the license is? If it is fully open, would you consider adding a license file to the repository?

Something simple like this would be awesome :)
https://opensource.org/licenses/MIT

**Comment by bd-arc** [comment]
Hi @jeffreyffs,

And [here you are](https://github.com/archriss/react-native-snap-carousel/blob/master/LICENSE)! To sum up: do whatever you want with the plugin and make awesome pull requests; just don't use our names without asking for it ;-)

**Comment by jeffreyffs** [comment]
Awesome, thanks so much!
