### ISSUE TITLE
Regression in Android behavior with version 3.2.2

### ISSUE THREAD

**Issue by bd-arc** [archriss/react-native-snap-carousel#156]
There has been a regression in carousel's behavior on Android starting with version 3.2.2. This is apparently linked to [this commit](https://github.com/archriss/react-native-snap-carousel/commit/d0a10517dbf6053cc02b30859b7cb38eb2181f48).

**Before**
Carousel was snapping one item at a time, without overscrolling.

**Now**
Carousel over-snaps and comes back if the gesture is too quick, which result in a poor user experience.

**Comment by odusseys** [comment]
Just confirming that I am indeed having this issue on Android. 
It does not seem to happen when the swipe is quick but instead when it is a long swipe.

**Comment by bd-arc** [comment]
Your guess is, indeed, spot on. I've narrowed the issue down to [these few lines of code](https://github.com/archriss/react-native-snap-carousel/compare/2568fca...d0a1051) but I really don't get why this impacts Android's behavior that much.

Currently investigating...

**Comment by mtimofiiv** [comment]
Just an observation, perhaps it could help: `onSnapToItem` callback gets triggered way too early in the case where this happens, and coincidentally sends an earlier index as an argument than is relevant. So given an example carousel with 10 items, the meandering extended scroll leads the callback being called within the first 2 indexes to the current position, before the animation even completes (with default settings). So the result appears to be a snap over several items, for example, say my scroll takes me to index 6, and the snap happened at 2, then I get snapped back to 2 but at extended speed.

**Comment by bd-arc** [comment]
Thanks for the feedback @mtimofiiv! I have been working on fixing this issue today and I'm almost done.

What you describe is more of a result than a cause. It all comes down to React Native `ScrollView`'s implementation: `onScollEndDrag` is triggered when the finger is lifted, but the momentum will continue anyway. The index is right, but calculated way too early because `ScrollView` lacks a proper `scrollEnd` event...

Anyway, I've narrowed down the issue to the fact that `setState` doesn't seem performant enough on Android; calling it too often messes with the `ScrollView`'s behavior. I should be able to push my fix tomorrow ;-)

**Comment by mtimofiiv** [comment]
Thanks a lot for the fantastic module and the active development on this!

**Comment by bd-arc** [comment]
@mtimofiiv You're most welcome! It's nice to hear that the plugin proves useful ;-)

@odusseys @mtimofiiv The issue should be fixed by [this commit](https://github.com/archriss/react-native-snap-carousel/commit/a57da943ba518fae7cfb82330b9bf8365dcbb953). Can you confirm? To use it:
```
"react-native-snap-carousel": "https://github.com/archriss/react-native-snap-carousel#a57da94"
```

**Comment by skylerparr** [comment]
@bd-arc that commit worked for me on the same issue.

**Comment by mtimofiiv** [comment]
I also find the commit is a drop-in replacement for downgrading the version to `3.2.0`!

**Comment by bd-arc** [comment]
@skylerparr @mtimofiiv Thanks for the feedback guys! The fix has been published in version `3.3.0`, along with the long-awaited "loop" feature ;-)

**Comment by bispul** [comment]
I think the bug is there again. When I long swipe it the animation shows a long swipe but ends in the next index to what is showing on the screen. This is just in android till now. Can you please check?

**Comment by bd-arc** [comment]
Hi @bispul,

I wasn't able to reproduce the issue. Did you make sure to read [this note](https://github.com/archriss/react-native-snap-carousel#important-note-regarding-android)?

**Comment by bispul** [comment]
ohhh now i get it. Thanks a lot @bd-arc
