### ISSUE TITLE
[Android] App crash randomly (scrollToOffset)

### ISSUE THREAD

**Issue by KarlosQ** [archriss/react-native-snap-carousel#158]
Sometimes, randomly, the app crash in Android.

The error:

![imagen](https://user-images.githubusercontent.com/15233913/30720632-9b0bb2fa-9f28-11e7-9ed9-b51a43e51715.png)

Carousel props: 

![imagen](https://user-images.githubusercontent.com/15233913/30720711-f2955c2e-9f28-11e7-898a-a0b3fb5de0cd.png)

React-native versions I tried: 0.47.1 and 0.48.3 
react-native-snap-carousel: 3.2.3
Android Studio Simulator (API 22)

**Comment by wildvalcom** [comment]
+1 for me this usually happens when I rotate device with the js debugging mode turned on

**Comment by bd-arc** [comment]
I think I know where the problem is. I will push a fix as soon as possible and will ask you guys to try it before releasing it.

**Comment by KarlosQ** [comment]
Thanks you! Which is the stable version for Android?

**Comment by bd-arc** [comment]
If my guess is correct, you shouldn't have any issue with version `3.1.0`.

**Comment by bd-arc** [comment]
@KarlosQ @wildvalcom [This commit](https://github.com/archriss/react-native-snap-carousel/commit/8b65fb771bc3f050663bf13050687cc17b0e4618) should solve the issue. Can you confirm?

To test it:
```
"react-native-snap-carousel": "https://github.com/archriss/react-native-snap-carousel#8b65fb7"
```

If you want a deeper understanding of the issue at stake, see [this React Native thread](https://github.com/facebook/react-native/issues/10635). Basically, you should apparently avoid using stateless components when rendered inside scroll components. They should be migrated to regular components that extend `Component` or `PureComponent`. See [this comment](https://github.com/facebook/react-native/issues/10635#issuecomment-286747320) or [this one](https://github.com/facebook/react-native/issues/10635#issuecomment-322091608).

**Comment by wildvalcom** [comment]
@bd-arc well, with this fix everything works as expected. Are you planing to merge this fix into master?

**Comment by bd-arc** [comment]
@wildvalcom It has already been merged, just not published on NPM yet ;-)

I'll publish a new release when I'm done fixing a few other issues.

**Comment by KarlosQ** [comment]
@bd-arc  No more crash, thank you!

**Comment by aschenkel** [comment]
Thanks @bd-arc! 
Just wanted to appreciate the effort and support this package has, it is great

**Comment by bd-arc** [comment]
You're welcome @aschenkel. Always good to hear though ;-)
