### ISSUE TITLE
iOS - Please implement so if you hold down thumb to scroll and select - it stays where you land. 

### ISSUE THREAD

**Issue by cooleagle8837** [archriss/react-native-snap-carousel#160]
Please implement so if you hold down thumb to scroll and select - it stays where you land.

**Comment by bd-arc** [comment]
Hi @cooleagle8837,

Can you share your implementation so I can take a look at it?

**Comment by cooleagle8837** [comment]
import React, {Component} from 'react';
import { View, Text } from 'react-native';
import PropTypes from 'prop-types';
import Carousel, { Pagination } from 'react-native-snap-carousel'

import {Metrics, Fonts} from '@themes';

const DISABLE_SWIPE_THRES = 1000;

export default class NumberPicker extends Component {

    static propTypes = {
        pickerStyle: View.propTypes.style,
        min: PropTypes.number,
        max: PropTypes.number,
        step: PropTypes.number, 
        itemWidth: PropTypes.number, 
        sliderWidth: PropTypes.number, 
        onValueChange: PropTypes.func,
        value: PropTypes.number, 
        fontColor: PropTypes.string, 
        active: PropTypes.bool, 

        setScrollEnabled: PropTypes.func, 
    }

    constructor(props) {
        super(props);
        this.state = this._stateFromProps(props);
    }

    _stateFromProps(props) {
        console.log(props);
        var state = {};
        state.pickerStyle = props.pickerStyle;
        state.min = props.min;
        state.max = props.max;
        state.step = props.step;
        state.itemWidth = props.itemWidth;
        state.sliderWidth = props.sliderWidth;
        state.onValueChange = props.onValueChange;
        state.value = props.value;
        state.fontColor = props.fontColor;
        state.active = props.active;
        state.fontSize= props.fontSize, 
        state.fontColor= props.fontColor, 

        state.setScrollEnabled = props.setScrollEnabled;
        
        state.itemHeight = Metrics.calcHeight(state.fontSize, Metrics.paddingSizeSmall);
        state.sliderHeight = state.itemHeight;

        state.data = [];
        for (var i=state.min; i<=state.max; i+=state.step) {
            state.data.push(i.toString());
        }

        return state;
    }

    componentWillReceiveProps(nextProps) {
        this.setState(this._stateFromProps(nextProps));
    }
    
    renderItem({item, index}) {
        return (
            <Text style={{ fontSize: this.state.fontSize, color: this.state.fontColor, width: this.state.itemWidth, textAlign: 'left'}}>
                {item}
            </Text>
        );
    }

    _getIndexFromValue(value, pMin, pMax, pStep) {
        var min = pMin==undefined?this.state.min:pMin;
        var max = pMax==undefined?this.state.max:pMax;
        var step = pStep==undefined?this.state.step:pStep;
        if (value < min) value = min;
        if (value > max) value = max;
        if (step == 0 || (value-min) < 0) {
            return -1;
        } else {
            return ( value - min ) / step;
        }
    }

    render() {
        let {pickerStyle, data, sliderWidth, sliderHeight, itemWidth, itemHeight, value, min, max, step} = this.state;
        return (
            // scrollEnabled={this.state.scrollEnabled}
            <View style={pickerStyle}>
                <Carousel
                    data={data}
                    renderItem={(data) => this.renderItem(data)}
                    sliderWidth={sliderWidth}
                    sliderHeight={sliderHeight}
                    itemWidth={itemWidth}
                    itemHeight={itemHeight}
                    inactiveSlideScale={1}
                    inactiveSlideOpacity={0.2}
                    onSnapToItem={(index) => {
                        this.state.onValueChange(min+index*step);
                    }}
                    firstItem={this._getIndexFromValue(value, min, max, step)}
                    enableMomentum={true}
                    decelerationRate={'fast'}
                    enableSnap={true}
                    activeSlideAlignment={'start'}
                    containerCustomStyle={{
                        //marginLeft: -sliderWidth+itemWidth/2, 
                    }}
                />
            </View>
        )
    }
}

**Comment by bd-arc** [comment]
Does it work if you set `enableMomentum` to `false`?

When this prop is set to `false`, the carousel relies on `scrollEndDrag` while it uses `momentumScrollEnd` otherwise. And there might be an issue with the RN implementation of the latter.

**Comment by cooleagle8837** [comment]
Okay. it works. Thank you.
I have also another issues and I am gonna close this and post a new issue.

**Comment by cooleagle8837** [comment]
But in this case, it's working weird for scroll.
https://www.dropbox.com/s/2xr7chczmh8o6sp/momentum%20issue.mov?dl=0

**Comment by bd-arc** [comment]
Unfortunately, it has to do with [React Native's `ScrollView` implementation](https://github.com/archriss/react-native-snap-carousel/#flatlist-and-scrollviews-limitations) and the randomness of the scroll events. But I agree: with small items, the momentum behavior is more natural.

I'll take a look at it as soon as possible to see if I can find a workaround for the `momentumScrollEnd` bug.

**Comment by cooleagle8837** [comment]
Thank you for your effort. I am looking forward to your solution.

**Comment by cooleagle8837** [comment]
@bd-arc, Can you let me know where I can change the code in node_modules?
Because it's some kind of urgent bug-fix, I am going to see the possibilities if i could fix it.

**Comment by cooleagle8837** [comment]
<img width="359" alt="screenshot at sep 26 08-24-09" src="https://user-images.githubusercontent.com/30376020/30843779-1da9bfa4-a294-11e7-9e10-92633f38d29b.png">
Hi, @bd-arc I have added one line of code and it's working fine.
Can you see if I have done something right?
Regards.

**Comment by bd-arc** [comment]
Ah, I see why this wasn't working. Apparently you're not using the latest version of the plugin.This bug was already fixed in [`3.2.2`](https://github.com/archriss/react-native-snap-carousel/releases) ;-)
