### ISSUE TITLE
Item Width Variation Issue

### ISSUE THREAD

**Issue by cooleagle8837** [archriss/react-native-snap-carousel#161]
<img width="144" alt="screenshot at sep 25 16-43-19" src="https://user-images.githubusercontent.com/30376020/30811372-a8961fec-a210-11e7-854e-eb6f8caf9a57.png">

AS you can see in this picture, 2-digit number and 3-digit number have the same width.

Is there any way that I can use it with different width so that 2-digit number and 3-digit number have the same spacing between.
<img width="163" alt="screenshot at sep 25 16-42-13" src="https://user-images.githubusercontent.com/30376020/30811345-8dc5a034-a210-11e7-9de5-4b53b0e30de3.png">
<img width="144" alt="screenshot at sep 25 16-42-34" src="https://user-images.githubusercontent.com/30376020/30811344-8dc3838a-a210-11e7-86c5-d843f6d2e567.png">

**Comment by bd-arc** [comment]
Using different items' widths is not allowed at the moment as this would be really tricky to handle, but this is something I've considered adding in the future.

For now, you might be able to hack your way around by using [`letterSpacing`](https://facebook.github.io/react-native/docs/textstyleproptypes.html#letterspacing).

**Comment by bd-arc** [comment]
@erickreutz Unfortunately, this would prove incredibly complex with the plugin's current logic.

I'm working on replacing the `FlatList` component altogether; this will maybe help with this request.
