### ISSUE TITLE
Implement Flip card feature.

### ISSUE THREAD

**Issue by trungwebsite** [archriss/react-native-snap-carousel#162]
This will be perfect if this has feature to flip card like: 
https://github.com/moschan/react-native-flip-card.
Or any guide we can integrate with it?
Thanks a lot

**Comment by bd-arc** [comment]
Hi @trungwebsite,

By glancing at the `flip-card` plugin's source code, I see no reason why you wouldn't be able to use it with the carousel. Have you try something along those lines?
```
_renderItem ({item, index}) {
    return (
        <FlipCard>
            <View style={styles.face}>
                <Text>The Face</Text>
            </View>
            <View style={styles.back}>
                <Text>The Back</Text>
            </View>
        </FlipCard>
    );
}
```

**Comment by bd-arc** [comment]
@trungwebsite In the end, have you tried implementing the flip card along with the carousel?

**Comment by itsVagabond** [comment]
Can someone please share some link where FlipCard is implemented with Carousel ?
I am doing so. Carousel is working but when I integrate FlipCard Carousel is not showing up at all.

**Comment by jerryfishzz** [comment]
@itsVagabond I have the same issue with u. Implementing FlipCard will make the both of them not working.
