### ISSUE TITLE
Render slide when visible

### ISSUE THREAD

**Issue by enguerranws** [archriss/react-native-snap-carousel#164]
Hi,

Thanks for this module, really helpful. That may be a stupid question, but I wonder if there's a way to render a component only when it becomes visible (or about to). Right now, I'm using this module to display a carousel of articles, which can really slow down global perf.

Any ideas?

**Comment by bd-arc** [comment]
Hi @enguerranws,

Well, that's exactly what the underlying `FlatList` component is supposed to do. Take a look at [this note](https://github.com/archriss/react-native-snap-carousel#inherited-props) in the documentation.

Typically, you will want to play with props `initialNumToRender`, `maxToRenderPerBatch`, `windowSize`, and `updateCellsBatchingPeriod` inherited from [`VirtualizedList`](https://facebook.github.io/react-native/docs/virtualizedlist.html).

Hope that helps!

**Comment by enguerranws** [comment]
@bd-arc Sure it does. I miss that point, thanks!

**Comment by Benguin** [comment]
If I've got a carousel with 10 items and starts on item 5, is there a way to prevent it from rendering the first 4 items? Flatlist seems to render items from the start of the array up to the current array index.
