### ISSUE TITLE
From 2.4.0 to 3.2.3: Pagination disappear

### ISSUE THREAD

**Issue by enguerranws** [archriss/react-native-snap-carousel#165]
Hi,

I guess I missed something (again) in the docs. I realized I was using `2.4.0` so I updated to `3.2.3` (that was my issue here: https://github.com/archriss/react-native-snap-carousel/issues/164).

But as I migrated from 2.4.0 to 3.2.3, my Pagination component just disappeared. I checked the styles (just to be sure it wasn't hiding somewhere out of the viewport), I checked the component properties, I don't see what can cause that.

Any idea?

**Comment by enguerranws** [comment]
Well, I checked the `containerStyle`the issue is coming from `dotStyle` which had its width set with `flex: 1`. It seems that `PaginationDot` is wrapped into a component, so the `flex` property can't be used.

I think it comes from the `<TouchableOpacity />` that is wrapping `<Animated.View style={dotStyle}/>` here: https://github.com/archriss/react-native-snap-carousel/blob/master/src/pagination/PaginationDot.js#L126

**Comment by bd-arc** [comment]
Hi @enguerranws,

Sorry for not getting back to you sooner; I'm going to take a look at this issue shortly. Thanks for your detailed feedback by the way ;-)

**Comment by bd-arc** [comment]
Can you share the exact set-up of your `Pagination` component? Because I didn't have any issue with [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example).

I must have overlooked something, but it will be easier to detect if I know the exact styles you're trying to use.

**Comment by bd-arc** [comment]
@enguerranws Well, I ended up adding a new prop for this use case: [`dotContainerStyle`](https://github.com/archriss/react-native-snap-carousel/blob/master/src/pagination/README.md#props).

You can find it in version `3.3.2` ;-)
