### ISSUE TITLE
A Carousel in another Carousel?

### ISSUE THREAD

**Issue by enguerranws** [archriss/react-native-snap-carousel#168]
Hi,

I have a simple question. Can I put a <Carousel /> in another <Carousel /> component? I made a test with a dummy <Carousel /> that I putted in a parent (and working) <Carousel />: the first (parent) carousel works as expected, not the second (child) one. 

Should this be working?

**Comment by bd-arc** [comment]
Hi @enguerranws,

Well, the `Carousel` component is, ultimately, a `ScrollView` and as such it should be possible to nest multiple carousels. Unfortunately, there are currently countless [React Native issues about nested `ScrollView`](https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=nested%20scrollview).

My recommendation would be to take a look at these issues and see if you can find something that looks like the one you're experiencing.

Do not hesitate to keep me posted; I'll gladly help if I can ;-)

**Comment by enguerranws** [comment]
@bd-arc Following your advice, I'll go for another solution: putting a carousel in a carousel doesn't make really sense (swipe gesture conflict, etc.). I'll use a solution based on https://github.com/archriss/react-native-image-gallery

**Comment by bd-arc** [comment]
Well, I'm not going to try and dissuade you from using another of our plugins :p

**Comment by enguerranws** [comment]
Well, I was using 2 of them, now 3. You've basically written 50% of my app.
