### ISSUE TITLE
Issue with interpolators when upcoming items prop has more elements than current items prop

### ISSUE THREAD

**Issue by superical** [archriss/react-native-snap-carousel#17]
I've noticed that when there is a change to the `items` prop, if the length of the upcoming `items` prop is larger than the current `items` prop, there will be issues with the interpolators. 

Assuming if `this.state.myItems` currently has 2 items like so:

```
//default state:
this.state = {myItems: [<View/>, <View/>]};
<Carousel items={this.state.myItems} ... />
```
No issue when it was initialised at start.
However, when there is change to `myItems` state at a later time to have more elements, for eg:
`this.setState = {myItems: [<View/>, <View/>, <View/>]}`;

The length of interpolators remained as 2. This will cause an undefined error because the third element in the new `myItems` cannot access an interpolator for its animation.

For my case, I'm using it with redux and so my state was something like `this.props.myItems` which came from one of my reducers. But I'm assuming that the same thing will occur with the regular `this.state`. Also, I'm running it on Android at the moment.

**Comment by superical** [comment]
I was trying to get it to work with my code and have created a PR with what I've done which seems to fix the problem.

I've really enjoyed using this component. Keep up the great work! 
Looking forward to more updates and features! 👍

**Comment by Exilz** [comment]
@superical thanks for helping out ! At first glance, your PR seems to be allright. I'll try it ASAP and merge it with other minor improvements.

**Comment by superical** [comment]
Sure. I've also just updated the PR after looking through the code again. Missed out the positions in my first commit. Thanks again for this really cool component! :)

**Comment by Exilz** [comment]
Looks like it's working like a charm. I just made the linter a little happier. It will be part of the next release. 😄
