### ISSUE TITLE
`enableSnap={false}` crashes with `this._onScrollEnd is not a function`

### ISSUE THREAD

**Issue by Kerumen** [archriss/react-native-snap-carousel#174]
When I set the prop `enableSnap` to `false` and I scroll the carousel it crashes with:

```
this._onScrollEnd is not a function
```

![screen shot 2017-10-07 at 18 15 00](https://user-images.githubusercontent.com/5436545/31309739-793eff46-ab8b-11e7-97af-87ba61eaa1c4.png)

I'm on iOS with `react-native-snap-carousel@3.3.2`.

**Comment by bd-arc** [comment]
@Kerumen Good catch! I've released a fix in version `3.3.3`. Can you confirm that it works for you?

The issue only occurs when you set `lockScrollWhileSnapping` to `true`, am I right? I must warn you that the prop doesn't have any effect when `enableSnap` is disabled.

**Comment by Kerumen** [comment]
It works! But `lockScrollWhileSnapping` was not enabled for me.
