### ISSUE TITLE
Small swipes keep resetting to item 0

### ISSUE THREAD

**Issue by alxvallejo** [archriss/react-native-snap-carousel#178]
I made a small gif to show you what I'm talking about: http://www.giphy.com/gifs/3ov9jJbGt29TIYZUas

Here's my component:

          ```
<Carousel
            sliderWidth={this.state.width * 0.9}
            sliderHeight={50}
            itemWidth={itemWidth}
            ref={carousel => (this._carousel = carousel)}
            inactiveSlideOpacity={0.5}
            inactiveSlideScale={0.7}
            onSnapToItem={slideIndex => this.setMood(slideIndex)}
            enableSnap={true}
            enableMomentum={true}
            decelerationRate={0.95}
            activeSlideAlignment="center"
            data={this.state.moods}
            renderItem={this.moodLabel}
            swipeThreshold={0}
            activeSlideOffset={5}
            lockScrollWhileSnapping={true}
          />
```

Note - i'm running 3.2.1. I'll try updating and see what happens.

I'm guessing there's some 'no-man's-land' margin somewhere so that it can't find the nearest item, but I'm curious what tactics you guys have tried if you've encountered this issue. I don't know how to eliminate all the margin of each item.

**Comment by alxvallejo** [comment]
Closing because upgrading to 3.3.3 fixed this issue. Great library guys!

**Comment by bd-arc** [comment]
@alxvallejo Thanks for the feedback ;-)
