### ISSUE TITLE
[iOS] undefined is not an object (evaluating '_react2.PropTypes.object')

### ISSUE THREAD

**Issue by ruslanverbelchuk** [archriss/react-native-snap-carousel#179]
Hi 
I run $react-native-git-upgrade for upgrading to react-native 0.49.3 and i ve got an error on iOS
undefined is not an object (evaluating '_react2.PropTypes.object')

<unknown>
    SliderEntry.js:9:24
loadModuleImplementation
    require.js:178:12
<unknown>
    index.js:6
loadModuleImplementation
    require.js:178:12
<unknown>
    index.ios.js:2
loadModuleImplementation
    require.js:178:12
guardedLoadModule
    require.js:123:45
global code
    <unknown file>:0

Thanks

**Comment by bd-arc** [comment]
Hi @ruslanverbelchuk,

Good catch! With React 0.49, `PropTypes` must be imported from the dedicated package and no longer as a subclass of `React` itself. The plugin has been ready for this for a long time, but I forgot about the example.

I'll push the required fix as soon as I can.

**Comment by bd-arc** [comment]
@ruslanverbelchuk I've just migrated the example to RN 0.49.3. Everything should now work properly ;-)
