### ISSUE TITLE
App crashed on startup with basic example

### ISSUE THREAD

**Issue by infinitey** [archriss/react-native-snap-carousel#181]
Hi, was trying to implement basic example when app just loaded with a blank and then crashes after a few seconds on both Android and iOS without any error message shown . My sincere apology if I made any mistakes. 

Thanks

 ```
"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.4",
    "react-native-snap-carousel": "^3.3.3",
     ...
```
Dashboard.js
```
import Carousel, { Pagination } from 'react-native-snap-carousel';
import styles, { CAROUSEL_WIDTH, MEMBER_CARD_WIDTH, } from '../../0styles/styles
import { ENTRIES1 } from './data'

export default class DashboardView extends Component {
    _renderItem({ item, index }) {
        return (
            <View style={styles.memberCardStyle}>
                <Text>{item.title}</Text>
            </View>
        );
    }

    render() {
        return (
            <Carousel
                data={ENTRIES1}
                renderItem={this._renderItem}
                sliderWidth={CAROUSEL_WIDTH}
                itemWidth={MEMBER_CARD_WIDTH}
            />
        );
    }
}
```
styles.js
```
const window = Dimensions.get('window');
export const MEMBER_CARD_WIDTH = window.width * 0.9;
export const CAROUSEL_WIDTH = window.width;
```

**Comment by bd-arc** [comment]
Hi @infinitey,

By glancing at your code, I don't see anything wrong with it. Can you try to build [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example) and tell me if your experience a similar issue?

**Comment by infinitey** [comment]
I was able to find the particular code that crashes the app. It is a mistake as I had attempted to reuse an old component but did not exclude margin style from my SliderEntry (card) .

Apparently, percentage margin like `margin: '5%'` will crash the app while numeric margin `'margin:10'` will throw an proper error message.

This will crash:
``` 
<View style={{ margin: '5%', width: 100, height: 200}}>
   ...
</View>
```

No more crashes:
``` 
<View style={{ width: 100, height: 200}}>
   ...
</View>
```

**Comment by bd-arc** [comment]
@infinitey Thanks for the feedback, this is interesting to know. It would be interesting to know if it is a limitation of the `ScrollView/FlatList` implementation.

**Comment by ethanyuwang** [comment]
I experienced the same issue and was able to fix it by changing percentage margin to numeric margin.
