### ISSUE TITLE
Force zIndex of inactive slides to be lower than the active slide

### ISSUE THREAD

**Issue by weswes** [archriss/react-native-snap-carousel#182]
As I'm animating current active slide to sometime take the whole width of the screen, the right inactive slide is still upside my current item.
Is there any way to force current active item zIndex to be superior than others ?

**Comment by weswes** [comment]
I can do it by changing render() in carousel.js:

```
(...)
**var zIndex= 0;
if (this.currentIndex == index){
    zIndex = 1;
}**
  return (
              <Animated.View
                key={`carousel-item-${index}`}
                style={[
                    slideStyle,
                  {  **zIndex: zIndex,**
                    opacity: animatedValue.opacity.interpolate({
                            inputRange: [0, 1],
                            outputRange: [inactiveSlideOpacity, 1]
                        }),
                        transform: [{
                            scale: animatedValue.scale.interpolate({
                                inputRange: [0, 1],
                                outputRange: [inactiveSlideScale, 1]
                            })
                        }],
                    }
                ]}>
                    { child }
              </Animated.View>
            );
(...)
```

**Comment by bd-arc** [comment]
Hi @weswes,

I can definitely add a new prop that would allow setting a higher `zIndex` for the active slide. Still, I think that users will be facing a problem when the indexes will change: the previous active item will instantly move behind the new active one, and this will result in a sub-par user experience. What are you thoughts about that?

By the way, which version of the plugin are you using?

**Comment by bd-arc** [comment]
Closing since no further feedback was provided.

**Comment by radiodario** [comment]
Hi @bd-arc this would be beneficial for me as well since i have an interaction which scales up the current slide on dragging up (to reveal some details) and currently this makes the next slide appear under the current one, How would you go about enabling this? I would definetely want the next and previous slides to have a lower z-index than the current:

`[ 1 ] [ 2 ] [ 1 ]`

**Comment by bd-arc** [comment]
Hi @radiodario,

You can use the new prop [`slideInterpolatedStyle`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#style-and-animation) to provide custom styles.

You can learn more about this feature in [the "custom interpolations" documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md). You will also find examples with the current active slide on top of the others (make sure to read the "caveats" section though).

**Comment by radiodario** [comment]
thanks a lot @bd-arc! amazing work on this library 💪

**Comment by gaykov** [comment]
Hey @bd-arc!

I'm also trying to implement similar behavior when the slide at the middle should be on top of left and right. Something like this: 

![image](https://user-images.githubusercontent.com/9068073/51175885-942ec980-18cc-11e9-96bc-f878e6ee3de2.png)

But I can't find the way of how to make it dynamically. I defined a custome `slideInterpolatedStyle` and  provided the following function on there:
```
export function animatedStyles(index, animatedValue, carouselProps) {
  let animatedOpacity = {};
  let animatedTransform = {};

  // .. do related animation configs

  return {
    // this line sets z-index to every 2nd slide, but is it possible to 
    // set this dynamically depending on the current selected slide?
    zIndex: index % 2 !== 0 ? 5 : 1,
    ...animatedOpacity,
    ...animatedTransform,
  };
}
```

Already spend a lot of time with it and can't figure it out, but feel that the solution is somewhere close and that's it should be easy 😕 Do you maybe have ideas about it?

Thank you in advance and thanks for such useful library!

**Comment by AlirezaAzizi145** [comment]
@weswes @gaykov @radiodario hello guys. i really need this style too. please help me if you found a solution.
Thanks a lot

**Comment by IvanMtz97** [comment]
Hello guys, i made a workaround, concious that isnt the best way to do it modifyng the state of the carousel container component, setting the onSnapToItem index to the Component state `index => this.setState({ carouselCurrentItemIndex })` forces the whole component re-render and re validates the slideInterpolatedStyle so can use `return { elevation: index === this.state.carouselCurrentItemIndex ? 1 : 0, }`

**Comment by tomLadder** [comment]
Same issue. Tried several hours. No perfect solution found.

**Comment by lnroma** [comment]
> Hello guys, i made a workaround, concious that isnt the best way to do it modifyng the state of the carousel container component, setting the onSnapToItem index to the Component state `index => this.setState({ carouselCurrentItemIndex: index })` forces the whole component re-render and re validates the slideInterpolatedStyle so can use `return { elevation: index === this.state.carouselCurrentItemIndex ? 1 : 0, }` and everytime you slide to an item, the component state gets changed and re renders the slider with the items interpolated style and re validates the elevation validation

elevation not for iOS

**Comment by Fredy** [comment]
If someone still needs this, just animate `zIndex`:
```
    zIndex: animatedValue.interpolate({
      inputRange: [-1, 0, 1],
      outputRange: [1, 5, 1],
      extrapolate: 'clamp',
    }),
```

**Comment by sajadghawami** [comment]
@Fredy 


how did u do it? It doesn't work for me like this:

```js
  const scrollInterpolator = (index: number, carouselProps: any) => {
    const range = [10, -10];
    const inputRange = getInputRangeFromIndexes(range, index, carouselProps);
    const outputRange = range;

    return { inputRange, outputRange };
  };

  const slideInterpolatedStyle = (
    index: number,
    animatedValue: any,
    carouselProps: any
  ) => {
    return {
      zIndex: animatedValue.interpolate({
        inputRange: [-1, 0, 1],
        outputRange: [1, 5, 1],
        extrapolate: "clamp",
      }),
    };
  };


```

The last one will still be infront of the one before

**Comment by Fredy** [comment]
@sajadghawami this is the entire `slideInterpolatedStyle` that I use:
```typescript
function slideInterpolatedStyle(
  index: number,
  animatedValue: Animated.AnimatedInterpolation,
) {
  return {
    zIndex: animatedValue.interpolate({
      inputRange: [-1, 0, 1],
      outputRange: [1, 5, 1],
      extrapolate: 'clamp',
    }),
    opacity: animatedValue.interpolate({
      inputRange: [-1, 0, 1],
      outputRange: [0.3, 1, 0.3],
      extrapolate: 'clamp',
    }),
    transform: [
      {
        scale: animatedValue.interpolate({
          inputRange: [-1, 0, 1],
          outputRange: [0.75, 1, 0.75],
          extrapolate: 'clamp',
        }),
      },
      {
        translateX: animatedValue.interpolate({
          inputRange: [-1, 0, 1],
          outputRange: [100, 1, -100],
          extrapolate: 'clamp',
        }),
      },
      {
        translateY: animatedValue.interpolate({
          inputRange: [-1, 0, 1],
          outputRange: [-80, 1, -80],
          extrapolate: 'clamp',
        }),
      },
    ],
  } as unknown as StyleProp<ViewStyle>;
}
```

**Comment by sajadghawami** [comment]
@Fredy 

Thanks for the quick reply!

Did u happen to use the `scrollInterpolator` function?

**Comment by Fredy** [comment]
@sajadghawami Yes:
```typescript
import { getInputRangeFromIndexes } from 'react-native-snap-carousel';

function scrollInterpolator(index: number, carouselProps: any) {
  const range = [1, 0, -1];
  const inputRange = getInputRangeFromIndexes(range, index, carouselProps);
  const outputRange = range;

  return { inputRange, outputRange };
}
```

**Comment by sajadghawami** [comment]
@Fredy 
thank you very much! 
unfortunately i couldn't make it run... so i ll just leave it as it is for now

**Comment by sahilrathi01** [comment]
> Hey @bd-arc!
> 
> I'm also trying to implement similar behavior when the slide at the middle should be on top of left and right. Something like this:
> 
> ![image](https://user-images.githubusercontent.com/9068073/51175885-942ec980-18cc-11e9-96bc-f878e6ee3de2.png)
> 
> But I can't find the way of how to make it dynamically. I defined a custome `slideInterpolatedStyle` and provided the following function on there:
> 
> ```
> export function animatedStyles(index, animatedValue, carouselProps) {
>   let animatedOpacity = {};
>   let animatedTransform = {};
> 
>   // .. do related animation configs
> 
>   return {
>     // this line sets z-index to every 2nd slide, but is it possible to 
>     // set this dynamically depending on the current selected slide?
>     zIndex: index % 2 !== 0 ? 5 : 1,
>     ...animatedOpacity,
>     ...animatedTransform,
>   };
> }
> ```
> 
> Already spend a lot of time with it and can't figure it out, but feel that the solution is somewhere close and that's it should be easy 😕 Do you maybe have ideas about it?
> 
> Thank you in advance and thanks for such useful library!
![Screenshot 2023-06-24 at 12 02 03 PM](https://github.com/meliorence/react-native-snap-carousel/assets/124804452/f5ea724f-9802-4cca-88c0-634ee9089a0e)

hey bro did you got this ? i also spend a lot of time with it and can't figure it out,, please please please please please
