### ISSUE TITLE
Carousel remains hidden

### ISSUE THREAD

**Issue by jay1337** [archriss/react-native-snap-carousel#184]
I have horizontals carousels indirectly in a vertical flatlist.
Carousels in the flatlist items that are initially rendered (index lower than initialNumToRender) stay hidden.
It seems that a rerender of the carousel without opacity style is effectively trigered but with no effect.
This bug only appears on Android platform with `__DEV__ === false` (optimization on).
If I change the initial state of the carousel setting `hideCarousel: false` then everything works fine.

**Comment by bd-arc** [comment]
Hi @jay1337,

Unfortunately, Android is the mighty king of unexpected and unreal issues... Can you try setting `apparitionDelay` to `0` and see if that does the trick for you?

**Comment by jay1337** [comment]
@bd-arc it seems to work. Quite logic once you've seen the code of `_didMountDelayedInit` function.

If you can't do anything to completely solve this bug, you should at least add something to the documentation (in `apparitionDelay`  description and Android issues).

**Comment by bd-arc** [comment]
@jay1337 Well, if you could set up an example project, I can take a look at it.

I don't know about documenting it since it doesn't have anything to do with the plugin but rather with `FlatList`'s implementation. I'll decide after being able to reproduce the issue myself from your example.

**Comment by jay1337** [comment]
@bd-arc 

I don't have time for a full working example but basically this should reproduce the issue (not tested, sorry):

```
const carouselRenderItem = () =>
	<Text>hello</Text>
;

const flatListRenderItem = () =>
<Carousel
	data={[{key: 1}, {key: 2}, {key: 3}]}
	renderItem={carouselRenderItem }
	sliderWidth={300}
	itemWidth={40}
	initialNumToRender={2}
/>
;

const App = () =>
	<FlatList
		data={[{key: 1}, {key: 2}, {key: 3}]}
		renderItem={flatListRenderItem}
		initialNumToRender={2}
	/>
}
```
