### ISSUE TITLE
not rendering images

### ISSUE THREAD

**Issue by MostafaEbrahimi** [archriss/react-native-snap-carousel#185]
I copy your sample code into my app.
slider display but not showing images.(uri images not loading but local images loads)

**Comment by bd-arc** [comment]
@MostafaEbrahimi Can you try [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example) and tell me if it works properly for you?

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.

See #135 for more information about a similar issue.
