### ISSUE TITLE
how to set space between slides

### ISSUE THREAD

**Issue by leogeng** [archriss/react-native-snap-carousel#187]
I want to change the space between slides.
![image](https://user-images.githubusercontent.com/3293583/31658373-71ec260c-b2f6-11e7-89b4-4890fbffa3de.png)

If change the margin of each item, something as the following.
![image](https://user-images.githubusercontent.com/3293583/31658411-8e1f2946-b2f6-11e7-8f3d-8f001d4aa994.png)

Does have any property to reset the space between slides.

**Comment by leogeng** [comment]
Margin between slides

If you need some extra horizontal margin between slides (besides the one resulting from the scale effect), you should add it as paddingHorizontal on slide's container.

⚠️ The value of itemWidth must include this extra margin.

const horizontalMargin = 20;
const slideWidth = 280;

const sliderWidth = Dimensions.get('window').width;
const itemWidth = slideWidth + horizontalMargin * 2;
const itemHeight = 200;

const styles = Stylesheet.create({
    slide: {
        width: itemWidth,
        height: itemHeight
        // other styles for your item's container
    }
};

**Comment by devmoonsite** [comment]
how?

**Comment by bd-arc** [comment]
@devmoonsite Make sure to read the doc; there is [an entire section](https://github.com/archriss/react-native-snap-carousel/#margin-between-slides) that explains how in length.

**Comment by futantan** [comment]
@bd-arc sorry to re-comment on this issue. I have read almost all the doc, but still not found a way to **reduce** the space between slides. Is there a way to do this?

**Comment by bd-arc** [comment]
@futantan Basically, this is determined by the `inactiveSlideScale` prop.

Play with its value until you find something that suits you. If you set it to `1`, you'll have no space between the slides.

**Comment by futantan** [comment]
@bd-arc Thanks for your help!

**Comment by bd-arc** [comment]
@futantan Sure. You just need to create an inner container and to set its padding to the value you want.

If you have trouble doing it, please create a [Snack](https://snack.expo.io/) example so I can take a look at it.

**Comment by mrafei** [comment]
@bd-arc is it possible to have the inactive scaled behavior without the extra space between slides?
thanks.

**Comment by bd-arc** [comment]
@mrafei It can be done thanks to [custom interpolations](https://github.com/archriss/react-native-snap-carousel#custom-interpolations).

You can base yours on [the default interpolation](https://github.com/archriss/react-native-snap-carousel/blob/master/src/utils/animations.js#L29-L64) and add a `translateX` one on top of the `scale` one.

**Comment by mrafei** [comment]
@bd-arc Thanks for the response.
I tried implementing what you said, this is my custom interpolator and animatedStyle:
`_scrollInterpolator(index, carouselProps) {
    const range = [3, 2, 1, 0, -1, -2, -3];

    const inputRange = getInputRangeFromIndexes(range, index, carouselProps);
    return {inputRange, range};
  }

  _animatedStyles(index, animatedValue, carouselProps) {
    const sizeRef = carouselProps.itemWidth;
    let animatedOpacity = {};
    let animatedScale = {};

    if (carouselProps.inactiveSlideOpacity < 1) {
      animatedOpacity = {
        opacity: animatedValue.interpolate({
          inputRange: [0, 1],
          outputRange: [carouselProps.inactiveSlideOpacity, 1]
        })
      };
    }

    if (carouselProps.inactiveSlideScale < 1) {
      animatedScale = {
        transform: [{
          scale: animatedValue.interpolate({
            inputRange: [0, 1],
            outputRange: [carouselProps.inactiveSlideScale, 1],
            extrapolate: 'clamp'
          })
        }, {
          translateX: animatedValue.interpolate({
            inputRange: [-3, -2, -1, 0, 1, 2, 3],
            outputRange: [40, 30, 20, 10, 0, -10, -20],
            extrapolate: 'clamp'
          })
        }]
      };
    }

    return {
      ...animatedOpacity,
      ...animatedScale
    };
  }`
I think this only shifts the inactive items to right which puts only the first item left of the active item in the right position. The transform doesn't seem to affect the rest of items.

also I have tried this with `useScrollView={true}` and it doesn't help on top of it I lose the snap to item functionality.

Can you help me fix this?
thanks.

**Comment by bd-arc** [comment]
Sure @mrafei!

Can you please provide a [Snack example](https://snack.expo.io/) that includes your latest developments?

**Comment by mrafei** [comment]
Gladly @bd-arc!

this is the [snack](https://snack.expo.io/HyKwc-IHX).

Thanks.

**Comment by bd-arc** [comment]
Hey @mrafei,

I've played with your example a few days ago and, as far as I can tell, it should just work!

I'm going to try and recreate it from scratch because this leaves me rather confused :-)

**Comment by mrafei** [comment]
@bd-arc 
any news on this?

**Comment by bd-arc** [comment]
@mrafei And here you are: https://snack.expo.io/H10cT8K8Q ;-)

The key was to change `const outputRange = [0, 1, 0];` (default value) to `const outputRange = range;` in the `scrollInterpolator` function and to modify the output ranges in `animatedStyles` accordingly.

**Comment by mrafei** [comment]
@bd-arc 
This is great. Thanks again for the great library. :)

**Comment by bishnudev** [comment]
I'm unable to do this. Can someone provide a clearer example or step by step instructions?

**Comment by chengsam** [comment]
> I'm unable to do this. Can someone provide a clearer example or step by step instructions?

I got it working by setting `inactiveSlideScale` to 1

**Comment by jdstregz** [comment]
> @futantan Sure. You just need to create an inner container and to set its padding to the value you want.
> 
> If you have trouble doing it, please create a [Snack](https://snack.expo.io/) example so I can take a look at it.

I'm sorry, I really dont know how to do this. I've tried wrapping my component in a view with 0 padding, as well as changing the container and content container custom styling but no luck. Anychance I could see an example of creating an inner container?

**Comment by Navipro70** [comment]
1. Just add margin to Container of component used at renderItem
2. Decrease your itemWidth with (your specified space) * 2

**Comment by Peter-Liao-github** [comment]
no space:
```
<Carousel
  inactiveSlideScale={1}
  // ... other code
/>
```

set space "`w (number)`":
```
<Carousel
  inactiveSlideScale={1}
  sliderHeight={imageHeight}
  contentContainerCustomStyle={{ marginLeft: w }}
  itemWidth={imageWidth + w}
  renderItem={() => (
    <View style={{ height: imageHeight }}>
      <Image source={imagePath} style={styles.swiperImage}>
    </View>
  )}
  // ... other code
/>

const styles = StyleSheet.create({
  swiperImage: {
    width: imageWidth,
    height: '100%',
    ...StyleSheet.absoluteFillObject,
  }
})
```
