### ISSUE TITLE
Full screen slides not working

### ISSUE THREAD

**Issue by AdamPD** [archriss/react-native-snap-carousel#188]
Hi there,

I am trying to get full screen slides working without having to specify explicit heights, but for some reason it's simply not working:

```
const pageWidth = Dimensions.get("window").width;
<Carousel
        containerCustomStyle={{ flex: 1, backgroundColor: "blue" }}
        data={[1,2,3]}
      sliderWidth={pageWidth}
      itemWidth={pageWidth}
      inactiveSlideScale={1}
      renderItem={() => <View style={{ backgroundColor: "red", flex: 1 }}><Text>This is a test</Text></View>}
      slideStyle={{ width: pageWidth }}
    >
    </Carousel>
```

No matter what I try, if I don't specify an explicit height on the rendered items, they will not expand to be full 100% height.

I understand this component wasn't designed for this but the example in the README seems to suggest this should work.

**Comment by kadoshms** [comment]
I used the following settings to have a full screen carousel:

```
<Carousel renderItem={this.renderItem.bind(this)}
                      data={this.props.children}
                      scrollEndDragDebounceValue={0}
                      activeSlideOffset={0}
                      vertical={true}
                      apparitionDelay={10}
                      sliderHeight={windowHeight}
                      itemHeight={windowHeight}
                      lockScrollWhileSnapping={true}
                      inactiveSlideOpacity={1}
                      inactiveSlideScale={1}
                      onScroll={onSwipe}
            />
```
also make sure the items and the container that contains this carousel are full height.

**Comment by bd-arc** [comment]
Hi @AdamPD,

Can you take a look at [the answer I gave to a similar question](https://github.com/archriss/react-native-snap-carousel/issues/134#issuecomment-327166846) and tell me if that helps?

Basically, I think you just forgot to transfer `{ flex: 1 }` with `slideStyle`. I will make a note about it in the doc.
