### ISSUE TITLE
<Pagination /> component How to set height?

### ISSUE THREAD

**Issue by lanjiemm** [archriss/react-native-snap-carousel#191]
I want <Pagination /> to be short
![qq20171019-180606](https://user-images.githubusercontent.com/20971872/31765830-58bcfb52-b48b-11e7-80fa-7900d556dff1.png)
this is my code 
![image](https://user-images.githubusercontent.com/20971872/31765882-8ce6bb3e-b48b-11e7-8086-84f8e5bb9672.png)

**Comment by bd-arc** [comment]
If you take a look at [the source code](https://github.com/archriss/react-native-snap-carousel/tree/master/src/pagination), you'll see that `<Pagination />` receives a default style of `{ paddingVertical: 30 }`.

Using prop `containerStyle`, you can either pass a different `paddingVertical` (my recommendation) or set it to `0` and define a custom height.

**Comment by lanjiemm** [comment]
@bd-arc Thanks very much
