### ISSUE TITLE
Scrolling the list pads the items slightly more down

### ISSUE THREAD

**Issue by mahomahoxd** [archriss/react-native-snap-carousel#192]
Either I am doing something wrong or the list is just not working for me. I load in a couple of notes, as soon as I scroll down, theres a strange padding or margin at the top of the list. Once I scroll down enough, eventually the items will be off screen. I've looked in the example and I didn't see the same kind of behavior. I am wondering what I am doing so different why it doesn't work that well for me.

I have this in my Notes.js screen : 

> \        <View
          style={{ backgroundColor: 'transparent', flex:1}}
          onLayout={this.updateHeightsNoteCarousel}
        >
          <Carousel
            vertical
            itemHeight={this.wp(75) + this.wp(2) * 2}
            sliderHeight={this.heightWindow}
            data={this.notes}
            renderItem={(item) =>
              <NoteItem onPress={this.onPressNote} note={item.item} height={this.wp(75) + this.wp(2) * 2} />
            }
            keyExtractor={item => item.id}
          />
        </View>

The wp function, I've copied from the example, where you take the screen height and take a percentage out of it. The height of the NoteItem property is just setting the height of the component. The heightWindow is the screen height. Is there something I'm missing?

**Comment by bd-arc** [comment]
Hi @mahomahoxd,

Would you mind sharing a screencast of the behavior you're experiencing? Also, can you try to render your carousel horizontally instead of vertically, and tell me if you're having the same issue ?

**Comment by mahomahoxd** [comment]
I can't get horizontal to work that easily as it requires me to change a lot of code while I really need it to be in vertical mode. https://im5.ezgif.com/tmp/ezgif-5-e10d2ba99d.gif is what happens, I don't want the position of the notes to move downwards, I want them to stay in one place as I scroll down

**Comment by bd-arc** [comment]
@mahomahoxd The screencast helped.

The issue is the same as the one described in the second part of #61. Take a look at [this comment](https://github.com/archriss/react-native-snap-carousel/issues/61#issuecomment-325202231) as well as [this one](https://github.com/archriss/react-native-snap-carousel/issues/61#issuecomment-325244828), and I think you'll be set.
