### ISSUE TITLE
Accessing this.state from within renderItem method

### ISSUE THREAD

**Issue by adamski** [archriss/react-native-snap-carousel#196]
I'm trying to achieve the following. I have a component within my Carousel's `renderItem` method which relies on `this.state` in order to update one of its props. However, once inside the `renderItem` method it seems longer able to access this.state (or any other member of the class).

In the case of the example below, I need to access `this.state.isRecording`, however it seems that in this context `this.state` is undefined. 

I've added `extraData` but I don't see how to access it. 

My conclusion is that the `renderItem` method has no access to properties of the containing class. If so how can I pass the state in? Unless I make it part of the `item` I'm passing but that does not make sense for my use case. 

```js
  renderTestWord({item, index}) {
    return (
        <View style={styles.carouselItem}>
          <JuceComponent 
            style={styles.juceComponent} 
            documentId={item} 
            showLastRecording={false}
            isRecording={this.state.isRecording} 
            onRecordingComplete={this.recordingComplete} />
        </View>
    )
  }

// In the main render method:
       <Carousel
          style={{ flex: 1 }}
          ref={(c) => { this._carousel = c; }}
          data={this.props.testList}
          renderItem={this.renderTestWord}
          sliderWidth={viewportWidth}
          itemWidth={viewportWidth}
          slideStyle={{ flex: 1 }}
          extraData={this.state}
        />
```

**Comment by adamski** [comment]
So I partially solved this by using an arrow function:
```js
        <Carousel
          style={{ flex: 10 }}
          ref={(c) => { this._carousel = c; }}
          data={this.props.testList}
          renderItem={({item, index}) => {
            console.log('renderTestWord', item);
            return (
            <View style={styles.carouselItem}>
              <JuceComponent 
                style={styles.juceComponent} 
                documentId={item} 
                showLastRecording={false}
                isRecording={this.state.isRecording}
                onRecordingComplete={this.recordingComplete} />
            </View>
            )
          }}
          sliderWidth={viewportWidth}
          itemWidth={viewportWidth}
          slideStyle={{ flex: 1 }}
          extraData={this.state}
        />
```
However quickly realised the folly of this method, is that it sets all the Carousels components recording resulting in a crash :laughing:

So I am now adding `onSnapToItem={itemIndex => this.setState({isRecording: this.props.testList[itemIndex]})}` and changing `isRecording` to reflect the current focused card on the carousel.

**Comment by bd-arc** [comment]
Hi @adamski,

It looks like you forgot to bind `this` in the constructor to provide the expected context inside `renderItem`.

[The answer](https://github.com/archriss/react-native-snap-carousel/issues/130#issuecomment-324953042) I gave to a similar question should put you back on track ;-) You can also take a look at [plugin's source code](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js) (search for `_renderItem`).
