### ISSUE TITLE
Add the ability to translate up or down the active item while scrolling

### ISSUE THREAD

**Issue by bd-arc** [archriss/react-native-snap-carousel#204]
The goal is to implement the following kind of interaction, where the active item is "higher" (or possibly "lower") than the inactive ones.

[Poster Gallery, by Jakub Nespor for STRV](https://dribbble.com/shots/3908716-Poster-Gallery)
![react-native-snap-carousel inactive slide shift](https://i.imgur.com/bwkiHoal.png)

**Comment by bd-arc** [comment]
Implemented in version `3.4.0`.

**Comment by DeveshBansalAppinventiv** [comment]
Hi @bd-arc  Can you please share the prop which can help us to build this?
