### ISSUE TITLE
View.propTypes.style deprecated

### ISSUE THREAD

**Issue by jsappme** [archriss/react-native-snap-carousel#206]
from https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6

 you need to change View.propTypes.style to ViewPropTypes.style

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

The matter you're talking about has been taken care of [a long time ago](https://github.com/archriss/react-native-snap-carousel/commit/2c893f4d79573d600ac7acbc9cd9d6d044daab25).
[Now we use both](https://github.com/archriss/react-native-snap-carousel/commit/292a75f0f418ea179df14da4c7485a831cfece0a) to ensure compatibility with older versions of React Native.

**Comment by iman2420** [comment]
@bd-arc 
`**atempted import error: 'ViewPropTypes' is not exported from 'react-native-web/dist/index'.**`
