### ISSUE TITLE
doesn’t show anything 

### ISSUE THREAD

**Issue by damathryx** [archriss/react-native-snap-carousel#207]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel#reporting-an-issue) regarding bug report?

yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

yes

### Have you made sure that your issue hasn't already been reported/solved?

yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

I only use android for now

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

No, but the example is not simple enough. This code is. but it shows nothing. 

### Environment

 Environment:
    React: 16.0.0-beta.5
    React native: 0.49.2
    react-native-snap-carousel: 3.4.0

  Target Platform:
    Android (6.0)

### Reproducible Demo

```
  renderPropertyItem = (property) => {
    return (
      <Text>{property.name}</Text>
    )
  }

  render () {
    return (
      <View>
        <Carousel
          data={[
            {
              name: 'apartment',
            },
            {
              name: 'condo',
            },
            {
              name: 'bungalow',
            },
            {
              name: 'semidetached',
            },
            {
              name: 'detached',
            }
          ]}
          renderItem={this.renderPropertyItem}
          itemWidth={50}
          sliderWidth={100}
        />
      </View>
    )
  }
```

**Comment by bd-arc** [comment]
Hi @damathryx,

There is a problem with your `renderPropertyItem()` method. [As seen in the doc](https://github.com/archriss/react-native-snap-carousel/#required), it receives one argument: `{item, index}`. So you need to call `property.item.name` for it to work.

Be careful with `<Text />` though: if you don't specify a width, slides will take a dynamic one based on label's length and this will mess the plugin up. To prevent this, you can either specify a slide width equals to `itemWidth` (e.g. `slideStyle={{width: 50}}`) or simply wrap your `<Text />` in a `<View />`. I recommend the latter.

**Comment by bd-arc** [comment]
@damathryx I've just tested what I've told you and wanted to let you know that **with a `Text` component, you need to specify slide's width**. So either:
```
<Carousel
    data={[...]}
    renderItem={this.renderPropertyItem}
    sliderWidth={100}
    itemWidth={50}
    slideStyle={{ width: 50 }}
/>
```
or:
```
renderPropertyItem = ({item, index}) => {
    return (
        <View style={{ width: 50 }}>
            <Text>{item.name}</Text>
        </View>
    );
}
```

**Comment by bd-arc** [comment]
@damathryx I've just tested what I've told you and wanted to let you know that **with a `Text` component, you need to specify slide's width**. So either:
```
<Carousel
    data={[...]}
    renderItem={this.renderPropertyItem}
    sliderWidth={100}
    itemWidth={50}
    slideStyle={{ width: 50 }}
/>
```
or:
```
renderPropertyItem = ({item, index}) => {
    return (
        <View style={{ width: 50 }}>
            <Text>{item.name}</Text>
        </View>
    );
}
```

**Comment by damathryx** [comment]
thanks

**Comment by abbasmoosavi** [comment]
I solved it by simply using removeClippedSubviews={false}
