### ISSUE TITLE
activeSlideAlignment add more option when snap items

### ISSUE THREAD

**Issue by levinhphuc91** [archriss/react-native-snap-carousel#209]
Hi team,

Can we have one more option for first item on left side but second, third item will be center?

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

Hi @levinhphuc91,

Unfortunately no, there is no way we can provide such a feature with the current inner logic of the plugin. You might interested by #195 though.
