### ISSUE TITLE
Error Handling for missing itemWidth or itemHeight

### ISSUE THREAD

**Issue by papmodern** [archriss/react-native-snap-carousel#210]
The problem is by forgetting to put itemWidth or itemHeight for Horizontal or Vertical Carousel, the proper error won't shows.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> :warning: You need to fill out the [issue template](https://github.com/archriss/react-native-snap-carousel/blob/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
