### ISSUE TITLE
Red Android screen on first touch..(

### ISSUE THREAD

**Issue by messpublic** [archriss/react-native-snap-carousel#216]
Hi!

This is an excellent plugin, but I can not use it, for several days I can not find a solution. 
I read the instructions, many times I tried to find a solution in a note about android, but unsuccessfully. 

I tried to make the most simple -

![2017-11-14 2 57 57](https://user-images.githubusercontent.com/33529693/32755714-a458dc0a-c8e7-11e7-8af3-5b27d7d42d48.png)

but even here a failure. 

Other plug-ins based on the carousel cause the same error. I do not rule out that my head is just stuck in a dead end, and the solution is simple, but I can not find it. 
I see this screen in my dream....

When I first try to scroll:

![2017-11-14 2 33 01](https://user-images.githubusercontent.com/33529693/32755214-485ad4d2-c8e5-11e7-88e8-f4bafb4cc5b3.png)

In general, I need animation of the map and its markers like here 

![2017-11-14 2 43 25](https://user-images.githubusercontent.com/33529693/32755303-a10fae04-c8e5-11e7-877f-8577d4bac7f0.png)

on idea I can use an "ViewPagerAndroid" instead of "ScrollView" or "Carousel" for Platform Android and I started to do it, but I had a new problem - I can not bind an animation to a region change in map

If I said wrong, sorry, I recently began to study programming and application development. 
I will be grateful for any advice, in advance for your help !!!

P.S. Sorry for my English)

"react": "16.0.0",
"react-native": "0.50.3",
"react-native-snap-carousel": "^3.4.0"

**Comment by bd-arc** [comment]
Hi @messpublic,

First, be aware that **you did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)**! This is a necessary step if you want us to be able to help you.

In [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md), you'll find some input that might help you figure out what's wrong, particularly:
- Have you tried to start with [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example) and to import your own logic in it step by step?
- Have you been able to reproduce the bug on iOS?

Then, you need to provide me with an example that reproduces the issue. Create a new app using https://snack.expo.io/, copy your code and remove things until you’re left with the minimal reproducible demo.

Share your answers as well as a demo and I'll se what I can do about your issue.

As a side note, we've considered implementing `ViewPagerAndroid`. Unfortunately, the preview effect (which is the root of the plugin) can't be implemented with it at the moment.

**Comment by naffiq** [comment]
This happens in my case sometimes, even if I just use ScrollView.

This issue might be helpful https://github.com/facebook/react-native/issues/16522

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.
