### ISSUE TITLE
onScroll doesn't update currentIndex

### ISSUE THREAD

**Issue by QQizi** [archriss/react-native-snap-carousel#219]
I updated the plugin to the last version from 2.x and i have now a problem with the onScroll callback.
It seem that the carousel .currentIndex doesn't update anymore in the callback function.

`<Carousel
ref={(carousel) => { this._carousel = carousel; }}
					sliderWidth={viewportWidth}
					sliderHeight={viewportHeight*55/100}
					itemWidth={viewportWidth}
					itemHeight={65}
					vertical={true}
					firstItem={this.state.activeSlide}
					enableSnap={false}
					inactiveSlideScale={1}
					data={this.state.slide}
					renderItem={this._slides}
					onScroll={(e) => {
						this._changeSlider();
					}}
				/>`

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> :warning: You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
