### ISSUE TITLE
demo Application

### ISSUE THREAD

**Issue by supei328** [archriss/react-native-snap-carousel#22]
hi,the first preview demo App,where i can see.

**Comment by bd-arc** [comment]
@supei328 Hi, you can try our company demo app on [Android](https://play.google.com/store/apps/details?id=fr.archriss.demo.app) and [iOS](https://itunes.apple.com/lu/app/archriss-presentation-mobile/id1180954376?mt=8), but we don't plan on releasing its source code.

Still, [our example](https://github.com/archriss/react-native-snap-carousel/tree/master/example) should get you started and you can learn more about the map implementation in [this thread](https://github.com/archriss/react-native-snap-carousel/issues/11#issuecomment-265147385). Hope this helps!
