### ISSUE TITLE
example maps

### ISSUE THREAD

**Issue by zokypesch** [archriss/react-native-snap-carousel#221]
anyone have a example carousel with maps ???

**Comment by bd-arc** [comment]
Hi @zokypesch,

It shouldn't be to complicated to implement. As stated in the doc:

> You can find some insight about our map implementation [in this comment](https://github.com/archriss/react-native-snap-carousel/issues/11#issuecomment-265147385).
> The folks at [codedaily.io](https://codedaily.io) have created a great tutorial about implementing a similar feature. [Go check it out!](https://codedaily.io/tutorials/9/Build-a-Map-with-Custom-Animated-Markers-and-Region-Focus-when-Content-is-Scrolled-in-React-Native)

**Comment by SKempin** [comment]
@zokypesch I'm trying to implement the carousel inside of the `MapView`. Currently I can only implement it underneath, so the carousel doesn't overlay the map. Did you attempt to do something similar? Thanks

**Comment by LegaciPro** [comment]
@SKempin Try using absolute positioning to place the carousel inside the MapView rather than beneath it.

**Comment by SKempin** [comment]
@LegaciPro Thanks, I had previously figured this out and have added it to the documentation for RN Google maps - https://github.com/react-community/react-native-maps#overlaying-other-components-on-the-map
