### ISSUE TITLE
Render any view as a slide?

### ISSUE THREAD

**Issue by eduardoinnorway** [archriss/react-native-snap-carousel#222]
Trying to figure this out, in your example you have data
{
        title: 'Beautiful and dramatic Antelope Canyon',
        subtitle: 'Lorem ipsum dolor sit amet et nuncat mergitur',
        illustration: 'http://i.imgur.com/UYiroysl.jpg'
    },

So this means, I cant render any view I want? I want to slide charts for example.

**Comment by bd-arc** [comment]
Hi @eduardoinnorway,

You are totally free to render whatever you want, but you need to do it through two props inherited from the `FlatList` component: `data` and `renderItem`.

I think that [this section](https://github.com/archriss/react-native-snap-carousel/#migration-from-version-2x) of the doc will clarify things for you.
