### ISSUE TITLE
react native snap carousel cannot render image from asset folder

### ISSUE THREAD

**Issue by babyjazz** [archriss/react-native-snap-carousel#223]
![image](https://user-images.githubusercontent.com/17084428/33162248-17f07392-d05b-11e7-801b-cfde8acdcda6.png)
Here is my code

![image](https://user-images.githubusercontent.com/17084428/33162252-26429c40-d05b-11e7-83b0-2e7b74881b8f.png)
and this is error

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> :warning: You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

Moreover, this error has nothing to do with the plugin but rather with React Native. Here is a link to the dedicated issues: https://github.com/facebook/react-native/search?q=image+require&type=Issues&utf8=%E2%9C%93

If I recall correctly though, there is a bug when using `require()` with a variable. Using the following might work:
```
entries: [
    { img: require('../assets/images/F_01.png') },
    { img: require('../assets/images/F_01.png') }
]
```
