### ISSUE TITLE
Support for react native v0.50.1

### ISSUE THREAD

**Issue by cruisecoders** [archriss/react-native-snap-carousel#224]
Feature request

Hi, I am getting this error when I updated my React Native version to 0.50.1. I think Parallax image needs to add support for <ImageBackground> Component.
![image](https://user-images.githubusercontent.com/27813353/33255672-baf0d250-d374-11e7-9f5f-38520929edf6.png)

react-native:v0.50.1

**Comment by bd-arc** [comment]
Hi @cruisecoders,

If you take a look at RN's release notes for version `0.50.0`, you'll see the following:
> `<Image>` with nested content is no longer supported. Looking into `<ImageBackground>` instead if this is something you did in our app.

This explains the error. But if you take a look at [the component's source code](https://github.com/archriss/react-native-snap-carousel/blob/master/src/parallaximage/ParallaxImage.js), you'll see that no content is rendered inside `<Animated.Image>`...

Have you been able to reproduce the error with [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

**Comment by cruisecoders** [comment]
Hi, @bd-arc I used this example to create the parallax carousel.It is working good in rn version 0.49.3 but when I updated my rn to 0.50.1 then I got the following error.

**Comment by bd-arc** [comment]
Hi @cruisecoders,

I've updated the example to RN `0.51.0` and I don't seem to have any issue. Can you try it and tell me if it is working properly for you?
