### ISSUE TITLE
ios change tabbar cause white screen

### ISSUE THREAD

**Issue by plimerence** [archriss/react-native-snap-carousel#225]
i make a banner use Carousel ,but when i  click tabbar to change to other screen ,the white screen may appear.
![whitescreen](https://user-images.githubusercontent.com/13290201/33309043-c767c65e-d457-11e7-877d-75a8eb503785.gif)

my core code is here:
<Carousel
                    inactiveSlideScale={1}
                    autoplayDelay={4000}
                    sliderWidth={this.props.itemWidth}
                    sliderHeight={ this.props.sliderHeight}
                    itemWidth={this.props.itemWidth}
                    itemHeight={ this.props.itemHeight}
                    onSnapToItem={(index) => {
                        this.setState({ activeSlide: index })} }
                    autoplay = {true}
                    renderItem={this.props.renderItem}
                    data={this.props.data}
                    loop={this.props.loop}
                >
   renderBannerContent = ({item})=>{
        return (
            <TouchableOpacity activeOpacity={1} onPress={() => this.press(item)}>
                <Image key="project"
                       style={{width: WIDTH, height: NEEDSCALESIZE(310)}}
                       source={item.uri}/>
            </TouchableOpacity>)
    };

my environment ：
	"react": "16.0.0-beta.5",
	"react-native": "0.49.3",
        "react-navigation": "^1.0.0-beta.15",

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> :warning: You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the issue will be closed.**

**Comment by chrise86** [comment]
I think I'm facing a similar issue - did you get any further with your issue @plimerence ?

**Comment by plimerence** [comment]
i do not hava any good idea, if you are hurry about it ,you can create a native module to solve this problem。 ps:andriod device is OK ,so just create ios native module . @chrise86

**Comment by bd-arc** [comment]
@meiqi1992 See #238.
