### ISSUE TITLE
 It's simple feature, not sure if already exist,

### ISSUE THREAD

**Issue by Jaafar-abusair** [archriss/react-native-snap-carousel#228]
### Is this a bug report or a feature request?

It's a question as start.

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel#reporting-an-issue) regarding bug report?

Link not working

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

yes

### Have you made sure that your issue hasn't already been reported/solved?

almost

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

(Write your answer here and specify the iOS/Android versions on which you've been able to reproduce the issue.)

### Is the bug reproductible in a production environment (not a debug one)?

(Write your answer here.)

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

(Write your answer here.)

### Environment

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screencasts/screenshots!)

### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant source code. Then provide instructions to reproduce the issue.)

**Comment by bd-arc** [comment]
Hi @Jaafar-abusair,

I don't see any question in your post; have I overlooked something?

**Comment by Jaafar-abusair** [comment]
I'm sure I wrote it somewhere, but i can't find it here anymore,
Any way, What I was asking about, you have activeSlideAlignment: 'start', 'center', 'end' and it's working as expected, What I'm asking for is to have all items as 'start' except the last item as 'end', so in this way I will not have a white margin at the end

**Comment by bd-arc** [comment]
Unfortunately, it is not possible at the moment.

If you want more info about the issues at stake, you can read #102, and particularly [this comment](https://github.com/archriss/react-native-snap-carousel/issues/102#issuecomment-343880254) as well as [this one](https://github.com/archriss/react-native-snap-carousel/issues/102#issuecomment-343908215).
