### ISSUE TITLE
Android emulator device does not have animation effects, version:  3.1

### ISSUE THREAD

**Issue by songxiaoliang** [archriss/react-native-snap-carousel#229]
ios animation is normal, there is no animation on the Android emulator device。
 version： 3.1
Expect the author to reply as soon as possible, thank you very much

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> :warning: You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

For your information, I've just recorded the following screencast with my Android emulator. As you can see there isn't any issue with it. I cannot help you if you don't provide a reproductible example on [Snack](https://snack.expo.io).

![react-native-snap-carousel](https://i.imgur.com/oWp8b1R.gif)

**Comment by songxiaoliang** [comment]
- Scrolling animations on ios, no scrolling animations on Android devices, version: 3.4

- But I use version 2.4, this problem does not exist


![677fb4e7-0c83-43b0-8daa-c7756d1c41bc](https://user-images.githubusercontent.com/6975588/33919736-4ac3a72c-dff5-11e7-8da0-e2da620e3566.png)

- code  show as below：
```
        <Carousel
          ref='carousel'
          data={ this.state.data }
          renderItem={  this.renderItem }
          sliderWidth={ screen.width }
          itemWidth={ pxToDp(300) }
          enableMomentum={true}
          removeClippedSubviews={false}
          containerCustomStyle={ styles.carouselContainer }
          ontentContainerCustomStyle={ styles.carouselContent }
          onSnapToItem={ (index) => this.onSnapToItem(index) } />
```

**Comment by songxiaoliang** [comment]
@bd-arc

**Comment by songxiaoliang** [comment]
@bd-arc Above is my question, looking forward to reply as soon as possible
