### ISSUE TITLE
JSON value '6'of type NSNumber cannot be converted to NSString

### ISSUE THREAD

**Issue by MatheusParanhos** [archriss/react-native-snap-carousel#231]
Hello all. I've ran into this issue when trying to integrate the example to my app. Anybody know what this can be? Basically what I did was to copy and paste the example
![captura de tela 2017-12-19 as 12 21 16](https://user-images.githubusercontent.com/28205194/34161241-277e30c2-e4b7-11e7-9d71-ce117d79d47c.png)

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> :warning: You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the issue will be closed.**
