### ISSUE TITLE
how to get stack of cards

### ISSUE THREAD

**Issue by swaroopa94** [archriss/react-native-snap-carousel#242]
Hi ,

I want a design like having stack of cards with back of one another and when we siwpe the first one it has to be dsiplayed on the back on left side and right side need to dispalyed remaing cards
Does this possible wiht this module 
I am attaching a screen shots 

without swiping the design should be like this:

![screen shot 2018-01-09 at 11 57 40 am](https://user-images.githubusercontent.com/19324363/34707585-54424052-f534-11e7-9f40-238dacc89d9b.png)

After I swiped first card it should look like this:

![screen shot 2018-01-09 at 11 39 54 am](https://user-images.githubusercontent.com/19324363/34707606-6c255ba0-f534-11e7-93b0-02e87cfcb501.png)

Please respond fast as its important 
Thank you

**Comment by bd-arc** [comment]
Hi @swaroopa94,

Take a look at #195.

Note that I don't know yet if I will be able to implement it because this kind of interaction would usually call for a custom `PanResponder` component whereas the plugin is based on a `ScrollView` one...

**Comment by bd-arc** [comment]
Hi @swaroopa94,

I think that [my recent findings](https://github.com/archriss/react-native-snap-carousel/issues/195#issuecomment-359746362) are really going to interest you ;-)

![react-native-snap-carousel custom animations](https://i.imgur.com/Ta3xHCn.gif)
