### ISSUE TITLE
Change inactive cards background

### ISSUE THREAD

**Issue by alxgeoaln** [archriss/react-native-snap-carousel#246]
can i change the background color of inactive cards and and animated them to get back to normal when their are active?

**Comment by bd-arc** [comment]
Hi @alxgeoaln,

You can't directly do that, but implementing it should be pretty straightforward.

You need to use a custom component in your `renderItem()` function and to keep track of the currently active item with `onSnapToItem(index)`. Then, whenever a change occurs, you could just animate whatever you want.

Take a look at [`PaginationDot`'s source code](https://github.com/archriss/react-native-snap-carousel/blob/master/src/pagination/PaginationDot.js); that's exactly what I've done.
