### ISSUE TITLE
Vertical= true show error

### ISSUE THREAD

**Issue by 2ducanhpham** [archriss/react-native-snap-carousel#249]
react-native-snap-carousel version 3.5.0
react-native version 0.52

![simulator screen shot - iphone 6 - 2018-01-22 at 03 23 08](https://user-images.githubusercontent.com/14899775/35198588-993ac726-ff23-11e7-8eb9-bb481aac76c0.png)

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the issue will be closed.**

**Comment by bd-arc** [comment]
FYI, **you will encounter this error if you forget to specify `itemHeight` when setting `vertical` to `true`**.

Make sure to read the doc as well as your console.

**Comment by 2ducanhpham** [comment]
Thanks @bd-arc , it worked. I do not set **itemHeight**
