### ISSUE TITLE
On swipe right on IOS, the view pulls down

### ISSUE THREAD

**Issue by sabbyt** [archriss/react-native-snap-carousel#25]
Not sure why but only seems to be happening on IOS. Works fine when swiping left but when change direction, the first swipe, will pull down the view revealing the main container. Could this be incompatibility with being nested inside a tab bar view?

**Comment by bd-arc** [comment]
@sabbyt Hi. Indeed, there might be a conflict with how libraries interact with each other. Could you try with version 1.4.0 of the plugin? We started handling touch events with version 1.5.0 in order to provide better momentum handling, but some fine tuning might be needed.

**Comment by sabbyt** [comment]
@bd-arc Thanks for suggestion but issue still persisting. Using the react-native TabBarIOS.

**Comment by Exilz** [comment]
I've never tested the component inside `TabBarIOS`.
You might try to use [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) instead, we've already used it with snap-carousel and it worked like a charm.

As you can see in this gif : 
![](https://camo.githubusercontent.com/a26d08bfbf8a02590ba4a4f0f0433d7781b87edb/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f365a735539675757727659746f676f772f67697068792e676966)

**Comment by sabbyt** [comment]
@Exilz actually started with react-native-tab-view but the issue was present. So thought we'd try with TabBarIOS. Have you tried implementing with TabBar in the footer?

**Comment by Exilz** [comment]
Nope I haven't tried it. Can you put the header on top just to be sure this
isn't the issue ?
Le lun. 23 janv. 2017 à 14:38, Sabrina Tee <notifications@github.com> a
écrit :

**Comment by bd-arc** [comment]
@sabbyt Hi there! Any news about the issue? Did you have a chance to try @Exilz's suggestion?

Also, have you tried disabling swipe gestures betweens tabs, e.g. `<TabViewPagerPan swipeEnabled={false} />`? FYI, we use version 0.40.0 of react-native-tab-view. There were some breaking changes since then, so I'm not sure if this still applies...

**Comment by bd-arc** [comment]
Closing the issue as there was no further feedback. Feel free to reopen if needed.

**Comment by ishigamii** [comment]
@Exilz did you block the swipe of the tabView to be able to do so ? 
@bd-arc Is there any way to be able to swipe the carousel without having to disable the tab swipe ? 

I am currently trying to add the carousel into a tab made with the lib [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) but this is very frustrating.

**Comment by gaffarmalik** [comment]
@sabbyt Any luck yet resolving it?
The swipes intended for the carousel(react-native-snap-carousel) pulls the tabs(react-native-tab-view) instead.
This still happens on Android.
