### ISSUE TITLE
Release version causes white screen

### ISSUE THREAD

**Issue by rogerkerse** [archriss/react-native-snap-carousel#252]
So when I have <Carousel /> anywhere in there code to render out, then the whole app turns white. And this happens only in release builds on Android and iOS. On develop/debug builds it works and looks as intended. Any ideas?

Internally it gives an error:
`TypeError: undefined is not an object (evaluating 'this._subscribableSubscriptions.forEach')`

**Comment by rogerkerse** [comment]
Ok this problem gets fixed when React Native is upgraded to atleast 0.52

**Comment by bd-arc** [comment]
Hi @rogerkerse,

`this._subscribableSubscriptions` is not part of the carousel logic; therefore I suspect a RN issue.

Good to know that updating to RN `0.52.0` fixed your issue though.
