### ISSUE TITLE
Purpose of this.setState({ slider1Ref: c }) in example ?

### ISSUE THREAD

**Issue by pcooney10** [archriss/react-native-snap-carousel#254]
### Is this a bug report or a feature request?

General question

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

### Is the bug reproductible in a production environment (not a debug one)?

N/A

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

N/A

### Environment

  Environment:
    React: 16.0.0
    React native: 0.50
    react-native-snap-carousel: 3.5.0

  Target Platform:
    Android (8.1)
    iOS (11.2.2)

### Steps to Reproduce

In your example, there's a [line (52)](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/index.js#L52) that looks like this:
```js
<Carousel
     ref={(c) => { if (!this.state.slider1Ref) { this.setState({ slider1Ref: c }); } }}
     ...
 />
```
Is the purpose of this line just for the pagination component ([L80](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/index.js#L80)), or does it serve another purpose?  In dev mode I sometimes get a warning that looks like this:

> Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is no-op.
Please check the code for the Carousel component.

I'm not using the `Pagination` component, so I wouldn't think I need this at all. For those using the pagination component, they might be able just to define it like this: `ref={c => { this. slider1Ref = c }}` and reference it like this: `carouselRef={this.sliderRef}` or this: `carouselRef={this.sliderRef && this.sliderRef}` to avoid an unneeded `this.setState()` call & re-render.

**Comment by bd-arc** [comment]
Hi @pcooney10,

As usual, you're spot on ;-)

You've probably noticed that, in the documentation I wrote and in every sample code I've given, I've **always** used the following `<Carousel ref={ c => this._carousel = c } />`.

Indeed, this otherwise useless `setState()` is only there to prevent an error with the `<Pagination />` component. I do not recommend doing so and, at that time, I just went for the easiest path :-) I forgot about it but I will definitely fix that. Thanks!

**Comment by jzhw0130** [comment]
@bd-arc  The setState() is used to prevent the <Pagiantion /> bug.
The bug as follows:

`
    renderList(guideData) {
        
        return (
            <Content>
                <Carousel
                    ref = {(carousel) => {console.log(`.......${carousel}`);  if(!this.state.carouselRef) {this.setState({carouselRef: carousel})}}}
                    data = {guideData}
                    renderItem = {this._renderItem}
                    sliderWidth = {vWidth}
                    itemWidth = {vWidth}
                    onSnapToItem={(index) => this.setState({ activeSlide: index }) }
                />
                { this._renderPagination() }
            </Content>
        )
    }

    _renderItem = ({item, index}) => {
        return (
            <CardItem>
                <Text> {_.get(item, 'title')} </Text>
            </CardItem>
        )
    }

    _renderPagination = () => {
        const {carouselRef, activeSlide} = this.state;
        console.log(`--------${carouselRef}`);
        return (
            <Pagination
                carouselRef = {carouselRef}
                tappableDots = {!!carouselRef}
                dotsLength = {this.guideData.length}
                activeDotIndex = {activeSlide}
                containerStyle = {{ backgroundColor: 'white' }}
                dotStyle = {{
                    width: 10,
                    height: 10,
                    borderRadius: 5,
                    marginHorizontal: 0,
                    backgroundColor: '#f05523'
                }}
                inactiveDotScale = {1}
                inactiveDotStyle = {{
                    width: 10,
                    height: 10,
                    borderRadius: 5,
                    marginHorizontal: 0,
                    backgroundColor: '#b3b3b3'
                }}
            />
        )
    }
`
For the first time to render:
--------null
.......[object Object]

It means the Pagiantion will not get a valid ref to Carousel, so you can not tap the dot to switch the page.

So we need to call setState to reRender the component, then log as follows:
--------[object Object]
.......null
.......[object Object]

Now you can tap the dot to switch the page.

**Comment by bd-arc** [comment]
@jzhw0130 I've refactored the example since then and had no issue with [the current setup](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/index.js#L53-L84), which doesn't require altering the state of the component.

Have you tried it?

**Comment by jzhw0130** [comment]
@bd-arc 
It seems like an issue of package, not the example.
