### ISSUE TITLE
i want to stop the user from control the Carousel

### ISSUE THREAD

**Issue by Q8hma** [archriss/react-native-snap-carousel#255]
### Is this a bug report or a feature request?

no

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

yes buy im noob and new in RN

### Have you made sure that your issue hasn't already been reported/solved?

i cant find it

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

ios i didnt try android

### Steps to Reproduce

im try to make it auto start and loop and the user cant move it or change the image

### Expected Behavior

i can move the image any place

Im so sorry because my english is very bad but the project im working on it have 2 Carousel both of them the user dont have control to change the scroll and only see the image moving 

this is my problem im so sorry if its sloved before i told u before im noob

**Comment by Q8hma** [comment]
this is the code i made
`

 <Carousel
            data={this.state.data}
            renderItem={this.renderItem}
			inactiveSlideOpacity={1.5}
            inactiveSlideScale={1.5}
            sliderWidth={sliderWidth}
            itemWidth={itemWidth}
            loop={true}
            enableMomentum={false}
            lockScrollWhileSnapping={true}
            autoplay={true}
            itemHeight={150}
            sliderHeight={150}
            autoplayDelay={500}
            autoplayInterval={3000}
            /> 
            `

**Comment by bd-arc** [comment]
Hi @Q8hma,

Make sure to take a look at [this section](https://github.com/archriss/react-native-snap-carousel#inherited-props) of the documentation ; I think that prop `scrollEnabled` is what you're after.

**Comment by Q8hma** [comment]
Thanks for this one im so sorry to miss it

but there are any things i can do to make Carousel=1 go from right to left , Carousel=2 go from left to right its like ..
its like one normal moving and the other one is reverse

thanks and sorry to reopen it

**Comment by bd-arc** [comment]
You're in luck because I'm currently working on implementing a way for users to specify their own custom animations to carousel's items. I hope to release it before the end of the week.

Stay tuned!

**Comment by Q8hma** [comment]
wow thanks thanks thanks thanks thanks thanks thanks thanks thanks 
i will wait on fire then  :)

**Comment by bd-arc** [comment]
@Q8hma Feature released in [version `3.6.0`](https://github.com/archriss/react-native-snap-carousel/releases/tag/v3.6.0).
