### ISSUE TITLE
It there a possible way to implement a marquee like behavior using this component?

### ISSUE THREAD

**Issue by jswxwxf** [archriss/react-native-snap-carousel#256]
As the title.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

---

This is not the intended use of the plugin, but I'm aware of one user who actually did it. Take a look at #208, you'll even find a working example there.
