### ISSUE TITLE
Stop scroll event propagation

### ISSUE THREAD

**Issue by cranberyxl** [archriss/react-native-snap-carousel#258]
### Is this a bug report or a feature request?

No

### Environment

  Environment:
    React: 16.2
    React native: 0.52
    react-native-snap-carousel: 3.6

  Target Platform:
    Android (6.0)
    iOS (10.3)

### Steps to Reproduce

1. Carousel nested in `react-navigation` `TabNavigation`
2. scroll to either end of the carousel and then the scroll event is propagated to the tab view

### Question
I tried `onScroll={(e)=>{e.stopPropogation()}}`, but onScroll doesn't fire at the ends. Is there another event I can hook into? Something I'm overlooking? Happy to write a PR if there is a good way to add this as a flag. My use case also doesn't work with `loop=true`

**Comment by bd-arc** [comment]
Hi @cranberyxl,

Using two different components that both respond to swipe events can lead to madness in no time. Moreover, I don't think you can stop the event propagation this way.

I see two potential workarounds:
- Wrap the carousel in a custom [`PanResponder`](https://facebook.github.io/react-native/docs/panresponder.html#basic-usage) and see where you can go with callbacks like `onStartShouldSetPanResponder()`, `onStartShouldSetPanResponder()`...
- Set the `TabNavigator` [option `swipeEnabled`](https://reactnavigation.org/docs/navigators/tab#TabNavigatorConfig) to `false` (I would personally go with this solution).

**Comment by cranberyxl** [comment]
Thanks, I'll do some research and report back here in case others are interested.

**Comment by bd-arc** [comment]
Yes, do not hesitate to share your findings. I'll even make an example out of it if you find something useful ;-)

**Comment by bd-arc** [comment]
@cranberyxl I previously forgot [that every view can become the touch responder](https://facebook.github.io/react-native/docs/gesture-responder-system.html#responder-lifecycle).

You can use methods like `onStartShouldSetResponder()`, `onMoveShouldSetResponder()` and such directly on the `Carousel` component (in fact, [that's what we did](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L1218:L1219)).

Note that `onResponderRelease()` will be overridden, so you might want to modify the source code if you need to use this prop.
