### ISSUE TITLE
Carousel Initial Index

### ISSUE THREAD

**Issue by filiipake** [archriss/react-native-snap-carousel#261]
### Is this a bug report or a feature request?

Bug Report

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?
Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

### Is the bug reproductible in a production environment (not a debug one)?
Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

No

### Environment

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1. Create Carousel with this config
```
<Carousel
            ref={(c) => { this._carousel = c}}
            data={this.state.milkingPositions}
            renderItem={this._renderItem}
            sliderWidth={width}
            itemWidth={width * 0.8}
            firstItem={17}
          />
```
2. Carousel only initiate on index 9 instead index 17. For index smaller than 09 it works.

### Expected Behavior

Carousel initiate on index 17.

### Actual Behavior

Carousel Initiate on Index 09 instead index 17.

### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant source code. Then provide instructions to reproduce the issue.)

**Comment by bd-arc** [comment]
Hi @filiipake,

This is the same issue as #235.

Take a look at [this comment](https://github.com/archriss/react-native-snap-carousel/issues/235#issuecomment-354996464) to learn more about the matter and to find out potential workarounds.

**Comment by filiipake** [comment]
Ops, sorry man, i try to find in your repo and didnt found anything. Thanks!
