### ISSUE TITLE
Multi image in Slide

### ISSUE THREAD

**Issue by Donhv** [archriss/react-native-snap-carousel#263]
I want show multi image like this( List img have 10 image and previous 3 image).
Image not selected have Opacity.
How I can do with this lib. thanks

![screen shot 2018-02-09 at 2 04 27 pm](https://user-images.githubusercontent.com/16864971/36023194-3483b9ec-0dbe-11e8-98ef-1696b16640a5.png)

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Regarding your question, see #259 and particularly [this comment](https://github.com/archriss/react-native-snap-carousel/issues/259#issuecomment-362212146).**
