### ISSUE TITLE
Using Animated.createAnimatedComponent(Carousel) results in undefined carouselRef methods

### ISSUE THREAD

**Issue by harrysolovay** [archriss/react-native-snap-carousel#271]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes. I've extensively researched the topic. Nevertheless, I do apologize if I missed the solution and am wasting anyone's time.

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes. Beautiful library!!!

### Have you made sure that your issue hasn't already been reported/solved?

Yes. I couldn't find anything that helped.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

I've only tried on iOS.

### Is the bug reproductible in a production environment (not a debug one)?

I'm unsure.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

Yes

### Environment

Environment:
    React: 16.2.0
    React native: 0.52.0
    react-native-snap-carousel: 3.6.0

  Target Platform:
    iOS (11.2)

### Steps to Reproduce

1. create an AnimatedCarousel component with Animated.createAnimatedComponent (Carousel as the argument)
2. have the AnimatedCarousel's ref callback assign the ref to this.carouselRef
3. instantiate the Pagination with the carouselRef and tappableDots properties like this:
```
  <Pagination
    activeDotIndex={ this.state.activeTab }
    dotsLength={ 3 }
    tappableDots={ !!this.carouselRef }
    carouselRef={ this.carouselRef }
  />
```
4. attempt to tap on a pagination dot (results in: carouselRef._getPositionIndex is not a function)
5. log carouselRef on componentDidMount (snapToIndex method does not exist... attempting to call the method from carouselRef._component does not work either)

### Expected Behavior

I'd expect that tapping on a pagination dot triggers the correct snapping behavior.

### Actual Behavior

<img width="374" alt="screen shot 2018-02-21 at 2 02 10 pm" src="https://user-images.githubusercontent.com/4893548/36499630-e13267d8-170f-11e8-9c3a-7a912d991df4.png">

### Reproducible Demo

The imported Header component responds properly to scrolling. Everything works as expected, except for pagination presses triggering the snapToItem method.

```

  import React, { Component } from 'react'
  import { View, Animated } from 'react-native'
  import { Header } from 'components'
  import Carousel, { Pagination } from 'react-native-snap-carousel'
  import { HEADER_HEIGHT, SCREEN_WIDTH } from 'constants'
  import { Posts, Capture, Account } from 'screens'
  
  const AnimatedCarousel = Animated.createAnimatedComponent(Carousel)
  
  const INITIAL_TAB = 0
  
  class TabsView extends Component {
  
    constructor(props) {
      super(props)
      this.state = {
        initialTab : INITIAL_TAB,
        activeTab : INITIAL_TAB,
        scrollX : new Animated.Value(INITIAL_TAB)
      }
    }

    render() {

      let headerTranslation = this.state.scrollX.interpolate({
        inputRange : [ 0, SCREEN_WIDTH, SCREEN_WIDTH * 2 ],
        outputRange : [ 0, -HEADER_HEIGHT, 0 ]
      })

      return (
        <View style={{ flex : 1 }}>

          <Header
            style={{ transform : [{ translateY : headerTranslation }] }}
          />
  
          <AnimatedCarousel
  
            ref={ ref => this.carouselRef = ref }

            data={[ <Posts />, <Capture />, <Account /> ]}
            renderItem={ ({ item, i }) => item }

            firstItem={ this.state.initialTab }

            onScroll={ Animated.event([
              { nativeEvent : { contentOffset : { x : this.state.scrollX } } }
            ], { useNativeDriver : true }) }
            onSnapToItem={ i => this.setState({ activeTab : i }) }
  
            sliderWidth={ SCREEN_WIDTH }
            itemWidth={ SCREEN_WIDTH }
            slideStyle={{ width : SCREEN_WIDTH }}
            inactiveSlideOpacity={ 1 }
            inactiveSlideScale={ 1 }
          />

          <Pagination
            activeDotIndex={ this.state.activeTab }
            dotsLength={ 3 }
            tappableDots={ !!this.carouselRef }
            carouselRef={ this.carouselRef }
          />

        </View>
      )

    }

    componentDidMount() {
      console.log(this.carouselRef) // has no snapToItem method
    }

  }

  export default TabsView

```

Thank you so much for taking the time to look over this issue! I hope that me bringing this to your attention is helpful. My best bet is that constructing an AnimatedCarousel component means that the actual Carousel component is less exposed. I tried to find a solution to this in the Animated documentation without success. One solution could be to create a new property "onMethodsLoaded" (a callback that returns a list of methods)... granted this might have an adverse effect on performance or be an anti-pattern. Just throwing this out there as an idea. Anyways, thank you again for taking the time.

Kind regards,

Harry

**Comment by bd-arc** [comment]
Hey @harrysolovay,

Thanks for putting in the time required to produce a high quality issue ;-)

The bad news is that you should definitely avoid creating an `Animated` component from the `Carousel`. The good news is that [it's already an `Animated` component](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L19:L20) :-) Moreover, it is [native-powered](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L139:L152) and the native `scroll` event is exposed.

The issue you're having is a classic when using `createAnimatedComponent()` with a component that is already animatable: refs are lost in the sea, dubious errors start to pop out of the blue... Trust me and avoid it like plague; I've learned that lesson the hard way!

Depending on what you're after, you could either:
- Wrap the carousel in an `<Animated.View />` and animate the latter (in order to provide an opacity effect when data has been fetched, for example).
- Use the [inherited prop `onScroll`](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L759:L761) that receives the native event.

Does this answer your need?

**Comment by harrysolovay** [comment]
Hi @bd-arc,

Thank you for getting back to me so quickly! Definitely a good lesson: re-wrapping an already-Animated component with createAnimatedComponent seems messy.

Maybe I'm misunderstanding your suggestion, but I want the carousel to trigger an Animation event for the adjacent Header component (I'm not trying to animate the carousel itself). I tried wrapping the carousel in an Animated.View, as well as setting the onScroll prop to trigger the animated event:

```
  <Animated.View>
    <Carousel
      ref={ ref => this.carouselRef = ref }
      data={[ <Posts />, <Capture />, <Account /> ]}
      renderItem={ ({ item, i }) => item }
      firstItem={ this.state.initialTab }
      onScroll={ Animated.event([
        { nativeEvent : { contentOffset : { x : this.state.scrollX } } }
      ], { useNativeDriver : true }) }
      onSnapToItem={ i => this.setState({ activeTab : i }) }
      sliderWidth={ SCREEN_WIDTH }
      itemWidth={ SCREEN_WIDTH }
      slideStyle={{ width : SCREEN_WIDTH }}
      inactiveSlideOpacity={ 1 }
      inactiveSlideScale={ 1 }
    />
  </Animated.View>
```

Did I improperly implement what you suggested, or is there another solution for my use case?

Thank you!!!!!!!

**Comment by bd-arc** [comment]
My mistake: I haven't been precise enough. Here is what you need to do:
- Remove the `Animated.View` wrapper; it is useless for your use case.
- Implement the following:
```
export default class MyExample extends Component {

    constructor (props) {
        super(props);
        this._onScroll = this._onScroll.bind(this);
    }

    _onScroll (event) {
        const scrollX = event.nativeEvent.contentOffset.x;
        console.log('OFFSET', scrollX);
    }

    render () {
        const { entries } = this.props;
        return (
            <Carousel
              // other props
              onScroll={this._onScroll} // <--- As simple as this
            />
        );
    }
}
```
- Use the value of `scrollX` to animate your header component.

And this is it ;-)

**Comment by harrysolovay** [comment]
The header animation was working before. Making the change above broke the onScroll animation. Instead of restoring it to its previous form, I tried swapping out the Animated.event(...) with the following _onScroll:
```
  _onScroll = (e) => {
    this.state.scrollX.setValue(e.nativeEvent.contentOffset.x)
  }
```
The animation is working again and corresponds to the scrollX, but pressing on the pagination dots still results in an error:
<img width="375" alt="screen shot 2018-02-21 at 4 47 11 pm" src="https://user-images.githubusercontent.com/4893548/36507332-54175184-1727-11e8-96ea-6ef9619ceff8.png">

The pagination control is what I'm struggling with... I'm not sure if by adding an onScroll callback I unintentionally override something related to pagination?

Thank you for providing me suggestions!!!

**Comment by bd-arc** [comment]
Could you create a [Snack](https://snack.expo.io/) example that reproduces the issue?

It would really make it easier for me to help you :-)

**Comment by harrysolovay** [comment]
No need–I just got it working!!!

I didn't realize, but I'd accidentally command+z'd back to using the Carousel component made from Animated.createAnimatedComponent(Carousel). Upon fixing that, using the _onScroll method from my last post worked without creating conflict for the pagination control.

Thank you so much for all of your suggestions. It's really nice to know that other developers have my back!!! I hope this is helpful to others as well. And I really do mean it when I say that this is a B E A U T I F U L library. I'll without a doubt use it in more projects.

**Comment by bd-arc** [comment]
Thanks for the kind words!

Happy to know that everything is now working as expected and that you're going to create awesome apps with this plugin ;-)
