### ISSUE TITLE
when loop true and scroll from last item to first item, it sometimes comes up a weird behaviour

### ISSUE THREAD

**Issue by keung7251** [archriss/react-native-snap-carousel#274]
Is this a bug report or a feature request?
Bug report.

Have you read the guidelines regarding bug report?
Yes.

Have you read the documentation in its entirety?
Yes.

Have you made sure that your issue hasn't already been reported/solved?
Yes.

Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?
Both.

Is the bug reproductible in a production environment (not a debug one)?
Yes.

Have you been able to reproduce the bug in the provided example?
Yes.

Environment
Environment:
React: 16.2.0
React native: 0.53.3
react-native-snap-carousel: 3.6.0

Target Platform:
Android (6.0)
iOS (11.2)

Steps to Reproduce
Refer to minimal example below.

Expected Behavior
the last item and first item should be same behaviour
Actual Behavior
when loop true and scroll from last item to first item, it sometimes comes up a weird behaviour.

[Bug gif](https://giphy.com/gifs/dCCWVQqnVnaxkxLNRC)

```
 _renderItem ({item, index,} , parallaxProps) {
        return (
            <View style={{marginTop: getAbsoluteResp(10)}}>
                <View style={{justifyContent: 'center', alignItems: 'center'}}>
                    <Text style={{fontFamily: 'LucidaGrande', fontSize: getHorizontalResp(14), fontWeight: 'bold', lineHeight: getVerticalResp(35), color: '#FFFFFF'}}>W-inds 15th Anniversary Live Tour</Text> 
                    <Text style={{fontFamily: 'LucidaGrande', fontSize: getHorizontalResp(12), lineHeight: getVerticalResp(20), color: '#FFFFFF'}}>March 27, 2018</Text> 
                    <Text style={{fontFamily: 'LucidaGrande', fontSize: getHorizontalResp(12), lineHeight: getVerticalResp(20), color: '#FFFFFF'}}>HONG KONG COLISEUM</Text>   
                </View>
                <View style={{marginTop: getAbsoluteResp(20), justifyContent: 'center', alignItems: 'center'}}>   
                    <ParallaxImage
                        source={item.image}
                        containerStyle={{width: 320, height: 400}}
                        style={{width: 320, height: 400}}
                        parallaxFactor={0}
                        {...parallaxProps}
                    />
                </View> 
            </View>    
        );
    }

    render() {

        return (
            <Carousel
                ref={(c) => { this._carousel = c; }}
                data={this.props.concerts}
                renderItem={this._renderItem}
                inactiveSlideScale={0.94}
                inactiveSlideOpacity={0.7}
                sliderWidth={screenWidth}
                itemWidth={320}
                layout={'default'}
                hasParallaxImages={true}
                activeAnimationType={'spring'}
                activeAnimationOptions={{
                    friction: 4,
                    tension: 40
                }}
                loop={true}
            />    
        );
    }

```

one more thing, how can I set all image same size??

**Comment by bd-arc** [comment]
Hi @keung7251,

This is a bug I've sometimes seen in a dev environment, but never in a production one.

I've previously tried fixing it, but it was rooted in miscellaneous issues with the `ScrollView` component; therefore, there was apparently nothing I could do about it.

Still, it would help if you could provide a [Snack](https://snack.expo.io/) example that reproduces the issue so I can get a closer look at it.

**Comment by keung7251** [comment]
Thanks a lot.

**Comment by haipv01** [comment]
could you please show me the solution
