### ISSUE TITLE
Render resized images on top/bottom of carousel instead of in the middle!

### ISSUE THREAD

**Issue by meurling** [archriss/react-native-snap-carousel#276]
### Is this a bug report or a feature request?

Feature request

As it is right now, when using the carousel with images having the `resizeMode: 'contain'`, the image is vertically centered. My request is to make it customizable, so that I.E the images always will be rendered at the top of the carousel. 
I.E. the following screenshot, the carousel is bordered by the red borderlines, and I would like to make the cute coala picture appear on top of the carousel!
![28554595_10214401382562422_691990832_o](https://user-images.githubusercontent.com/26538245/36754783-55462cc8-1c0a-11e8-8ac0-849f78fbae23.png)

Thank you!

**Comment by bd-arc** [comment]
@meurling I'm not sure that I've properly understood what you're after.

Can you share a minimal [Snack](https://snack.expo.io/) example with the "koala" setup? This way I can quickly make a few tests and tell you how to achieve the desired layout.

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.
