### ISSUE TITLE
Call custom function inside renderitem gives error

### ISSUE THREAD

**Issue by barron9** [archriss/react-native-snap-carousel#277]
outrun(){
	alert('aa')
	this.props.navigation.navigate('ProductDetail', { name: uri.replace('/product/','') , token:this.state.token })
	}
 _renderItem ({item, index}) {
	 var self=this;
	 
        return (
            <TouchableOpacity onPress={()=>this.outrun()} style={{height:180,backgroundColor:'#fbb034'}}>
		<Image style={{width:Dimensions.get('window').width,height:150}} resizeMode={'contain'}  source={{uri: 'https:'+item.Image}}/>
                <Text style={{fontSize:18,color:'white'}}>{ item.Description }</Text>
            
		</TouchableOpacity>
        );
    }

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Your issue looks like a classing binding mistake and has nothing to do with the plugin. See [this comment](https://github.com/archriss/react-native-snap-carousel/issues/9#issuecomment-268195473) for more info.**

**There is also [an entire section of the doc](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/TIPS_AND_TRICKS.md#implementing-navigation) dedicated to implementing navigation. Please read it!**
