### ISSUE TITLE
Swipe several slides

### ISSUE THREAD

**Issue by sweatC** [archriss/react-native-snap-carousel#280]
Hey, is there a way to scroll several items that depends on how strong/fast the swipe is?

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

---

Regarding your question, take a look at [prop `enableMomentum`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior).
