### ISSUE TITLE
Undefined is not an object data.length

### ISSUE THREAD

**Issue by amyogiji** [archriss/react-native-snap-carousel#281]
Undefined is not an object data.length

i am using default one

<Carousel layout={'stack'} layoutCardOffset={`18`} />

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Make sure to read the doc, particularly the section about [the required props](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#required).**

**Comment by machester4** [comment]
you are not sending the property `data` or you are sending it empty.  in your code I do not see `renderItem`

**Comment by rohit280** [comment]
<Carousel
              ref={(carousel) => { this._carousel = carousel; }}
           
              onSnapToItem={(index) => this.setState({ activeSlide: index }) }
              enableSnap={true}
            >
                {this.renderImages()}
            </Carousel>
            <Pagination
              dotsLength={this.state.product.images.length}
              activeDotIndex={this.state.activeSlide}
              containerStyle={{ backgroundColor: 'transparent',paddingTop: 0, paddingBottom: 0, marginTop: -15 }}
              dotStyle={{
                  width: 10,
                  height: 10,
                  borderRadius: 5,
                  marginHorizontal: 2,
                  backgroundColor: 'rgba(255, 255, 255, 0.92)'
              }}
              inactiveDotOpacity={0.4}
              inactiveDotScale={0.6}
            />

someone help me to solve this issue..

**Comment by valeriashpiner** [comment]
@rohit280 you need to add line `data={this.state.product}` to you <Carousel />
