### ISSUE TITLE
It takes too long to render the content

### ISSUE THREAD

**Issue by abhi06991** [archriss/react-native-snap-carousel#284]
Initially I thought I was having some content rendering issues, but then I noticed it was taking around 5 minutes just to render a simple text. The way I found out that it took so long was, when I was typing my issue of content not getting rendered to post in here and noticed it just got rendered. Even If I navigate to previous screen and come back, it takes a long time to render. Tested this out 3 times. It works but just takes more than 5 minutes to render.

My Environment:
**react-native-snap-carousel@3.6.0
react-native@0.52.0**

Testing it directly in my Moto G4 plus, Android-7.0

My Code:
```

import React, { Component } from 'react';
import { View, Text, Dimensions } from 'react-native';
import Carousel from 'react-native-snap-carousel';

class ImageSlider extends Component {
	

  renderItem({item, index }) {
  	console.log(index);
  	console.log(item);
      return (
          <View style={styles.tile}>
              <Text style={{ textAlign: 'center',fontSize: 17, color: 'black' }}> { item } </Text>
          </View>
      );
  }


	render() {
		const customdata = [
			"text1text1text1text1text1text1text1text1",
			"text2text2text2text2text2text2text2text2",
			"text3text3text3text3text3text3text3text3",
			"text4text4text4text4text4text4text4text4",
		];

		return (
            <View style={styles.container}>
                <Carousel
                  data={customdata}
                  renderItem={this.renderItem}
                  itemWidth={Dimensions.get('window').width * 0.85}
                  sliderWidth={Dimensions.get('window').width}
                  containerCustomStyle={styles.carousel}
                  slideStyle={{ flex: 1 }}
                />
            </View>
		);
	}
}

const styles = {
    container: {
        height: 300
    },
    carousel: {
        flex: 1,
        backgroundColor: 'red'
    },
    tile: {
        flex: 1,
        width: Dimensions.get('window').width * 0.85,
        backgroundColor: 'yellow'
    }
};

export default ImageSlider;
```

**Comment by bd-arc** [comment]
@abhi06991 Five minutes to render a simple text?! There must be something really wrong with your code.

Here are two basic Snack examples you can try out in order to check that everything loads instantly:
- https://snack.expo.io/SkNX1hqDf
- https://snack.expo.io/@akyker20/react-native-snap-carousel-bug

If you can't find out where the issue is coming from, please share a Snack example that reproduces the problem so I can take a look at it.

**Comment by abhi06991** [comment]
It worked out. I guess may be it was a problem with the way the it bundles the app. I had to plug out the device, then plug in and re run the command `react-native run-android` and it worked. 
Closing the issue
