### ISSUE TITLE
You have a large list that is slow to update

### ISSUE THREAD

**Issue by emregurler** [archriss/react-native-snap-carousel#285]
### Is this a bug report or a feature request?

Bug, actually may be performance issue.

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes.

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes.

### Have you made sure that your issue hasn't already been reported/solved?

No. It is not reported. I havent seen anything about this.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

On both platforms, It is living thing.

### Is the bug reproductible in a production environment (not a debug one)?

Always happening.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

(Write your answer here.)

### Environment

Environment:
    React: 16.0.0-beta.5
    React native: 0.49.2
    react-native-snap-carousel: 3.3.3

  Target Platform:
    Android (6.0)
    iOS (10.3)

### Expected Behavior

Slider should run fast

### Actual Behavior

I have Map component from react-native-maps and I am rendering Carousel component in Map Component.
I make SliderEntry for each location information on map(like airbnb did). Map component draws SliderEntry as much as my location size. Each slider entry has just a few text and a button. I swipe left or right for changing location. Everything is fine till here.
This performans issue occurs when I get more than 500 location. App is not crashed, but at the beginning slider is so slow( approximately for 5 - 15 seconds depending on location size). When I look up console, it warns me that` You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {dt: 505, prevDt: 1906, contentLength: 50468}`

I am sorry that I am writing this issue without demo, but maybe you can try to draw 1000 or more SliderEntry on your demo and test the rendering performance at first. If I can install the demo without error, I will try my opinion and I will edit my Issue here.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

**Comment by bd-arc** [comment]
@emregurler Unfortunately, this clearly looks like a `FlatList` issue. The component is not as good as it's supposed to be with a large dataset.

You can try to load smaller chunks of data and add some more when the user scrolls to the end of the carousel (see the inherited [`onEndReached`](https://facebook.github.io/react-native/docs/virtualizedlist.html#onendreached) prop). In fact, for your use case I would only load the current slide and the prev/next 2, and then update them dynamically after each swipe.

Also, make sure you've implemented everything described in [this section regarding performance optimization](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/TIPS_AND_TRICKS.md#optimizing-performance).

**Comment by gamingumar** [comment]
What if we want to scroll to higher index value initially? 
https://stackoverflow.com/questions/54540375/performant-way-of-rendering-huge-list-with-initial-index-in-react-native

**Comment by bd-arc** [comment]
@gamingumar Well, I haven't been able to find a good workaround for that. It is a `FlatList` built-in limitation.

My goal is to switch to a more performant and less buggy scroll component, but I am yet to find one that meet all the criteria.

**Comment by anastely** [comment]
@bd-arc Are you found something help you in this case?
