### ISSUE TITLE
FirstItem index does open wrong index when length of list is greater than 6.

### ISSUE THREAD

**Issue by GarimaMathur07** [archriss/react-native-snap-carousel#288]
```
<Carousel
					data={this.props.storeLocations} // length is 570
					renderItem={({ item, index }) => {
						//
					}}
					sliderWidth={sliderWidth}
					itemWidth={itemWidth}
					firstItem={this.props.initialDetailIndex} // wrong item display
					containerCustomStyle={styles.carouselStyle}
				/>
```

@bd-arc Can you please suggest any solution of this issue

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Regarding your issue, see [this comment](https://github.com/archriss/react-native-snap-carousel/issues/235#issuecomment-354996464).**
