### ISSUE TITLE
scroll not working efficiently

### ISSUE THREAD

**Issue by adityak16** [archriss/react-native-snap-carousel#290]
HI, 
I am using version 3.6.0 and and scroll not working properly if someone slides image fast, it comes back to first image.

react-native: 0.48.4

This is my code : 

        <Carousel
              data={ _.get(this.props, 'userDropDetails')}
              sliderWidth={deviceWidth}
              itemWidth={deviceWidth / 2}
              inactiveSlideScale={0.53}
              inactiveSlideOpacity={0.6}
              removeClippedSubviews={false}
              apparitionDelay={1500}
              contentContainerCustomStyle={{alignItems: 'center'}}
              onSnapToItem={(item) => this.changePost(item)}
              renderItem={this._renderSlider}
              firstItem={_.get(this.props, 'index', 0)}
            />

**Comment by Akarsh08** [comment]
+1

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**=> Can you share a screencast of the issue?**

Also, note that the plugin is tested only on the most recent versions of React Native. Indeed, it is based on the built-in `FlatList` component that is regularly updated by the Facebook team.

**Comment by alexlevy0** [comment]
+1
