### ISSUE TITLE
Bug: When inside of Tabs for react-native-router-flux, slides don't show until you begin to swipe

### ISSUE THREAD

**Issue by dwilt** [archriss/react-native-snap-carousel#292]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes.

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

I'll be honest, probably not.

### Have you made sure that your issue hasn't already been reported/solved?

I've done a very thorough check through the  issues with as many keyword searches as possible because putting together the reproduction steps for this was a PITA (though I completely appreciate why it has to be).

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

I've only been testing on iOS.

### Is the bug reproductible in a production environment (not a debug one)?

Yes, it still exists when the scheme for iOS is set to "Release".

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

I didn't try. I just created a fresh React Native project and installed the carousel (along with [react-native-router-flux](https://github.com/aksonov/react-native-router-flux).

### Environment

Environment:
    React: 16.3.0-alpha.1
    React native: 0.54.2
    react-native-snap-carousel: 3.6.0 
    react-native-router-flux: 4.0.0-beta.28

  Target Platform:
    iOS (11.2)

### Steps to Reproduce

When you put the carousel inside of `<Tabs>` for [react-native-router-flux](https://github.com/aksonov/react-native-router-flux), the images don't show until you begin to swipe.

1. Clone out https://github.com/dwilt/react-native-snap-image-bug
2. Start the packager
3. Fire up a SIM for iOS (`react-native run-ios`)
4. Click on the Detail tab at the bottom

### Expected Behavior

The images for the carousel would always be there - not just when I begin to swipe. This _may_ be a [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) problem but I wasn't sure so I'm posting here. Because it works on other pages in the app along with other components, I thought this really was probably a problem with this plugin. It seems like some sort of layout issue.

Notice below how you can see, when using the Inspector in the SIM, that the `CellRenderer` (`flatlist-item-6`) for the slide is visible in the SIM when I hover over the avatar.:

![image](https://user-images.githubusercontent.com/1065539/37869718-2a8e8e96-2fbd-11e8-9ae8-c84b52070603.png)

But when I hover over the next avatar `CellRenderer` (`flatlist-item-7`) that should be visible, notice where it is positioned invisible off the screen:

![image](https://user-images.githubusercontent.com/1065539/37869761-fd3a1824-2fbd-11e8-8e3b-fb19a79a158d.png)

### Actual Behavior

As described above, when you navigate to a `<Tab>` page, the carousel isn't displaying all of the slides correctly:

![image](https://user-images.githubusercontent.com/1065539/37869666-0c5df8fe-2fbc-11e8-84d0-48a5c99186f3.png)

But, once you begin to swipe, they immediately pop back in:

![image](https://user-images.githubusercontent.com/1065539/37869669-1ab08a66-2fbc-11e8-891c-f05beed6a59d.png)

### Reproducible Demo

https://github.com/dwilt/react-native-snap-image-bug

I've put together a repo with the latest version of React Native, this plugin, and react-native-router-flux to demonstrate.

**Comment by bd-arc** [comment]
Hi @dwilt,

This looks like #238; I think you'll find some useful information there ;-)

To sum up: this is an unfortunate [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues/238#issuecomment-354536859). I've exposed two ways of dealing with:

> `triggerRenderingHack (offset)` | Call this whenever needed to work around [a random `FlatList` bug](https://github.com/facebook/react-native/issues/1831) that keeps content hidden until the carousel is scrolled. Note that the `offset` parameter is not required and will default to either `1` or `-1` depending on current scroll position.

> `useScrollView` | Whether to use a `ScrollView` component instead of the default `FlatList` one. The advantages are to avoid rendering issues that can arise with `FlatList` and to provide compatibility with React Native pre- `0.43`. The major drawback is that you won't benefit from any of `FlatList`'s advanced optimizations. **We recommend activating it only with a small set of slides and to test performance thoroughly in production mode.**

**Comment by iuliuvisovan** [comment]
Hello, one question. I have "snapToItem" to a high index, say 30, and it scrolls to the ninth position, and only after that loads the next items. Will `triggerRenderingHack` help in this case? If yes, when exactly should I call it? I'm calling before and after calling `snapToItem`, is there anything else I'm missing? :/
