### ISSUE TITLE
Swiper with optimized initial rendering

### ISSUE THREAD

**Issue by Akilasusmy** [archriss/react-native-snap-carousel#297]
How can I improve the time taken for initial rendering when the data set is huge? 
Precisely, is there a way to pass "onEndReached" ,"initialPageSize" props to carousel for flatlist optimizations?

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Make sure to read the doc: particularly [this section on inherited props](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#inherited-props) and [this one on performance optimization](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/TIPS_AND_TRICKS.md#optimizing-performance) .**
