### ISSUE TITLE
Hi, How to do this UI？

### ISSUE THREAD

**Issue by RoarRain** [archriss/react-native-snap-carousel#299]
<img width="268" alt="swiper" src="https://user-images.githubusercontent.com/10494442/38228193-b71435f4-3734-11e8-9a38-a28b4dcf59ca.png">
<img width="500" alt="swiper" src="https://img.ctolib.com/uploadImg/20180224/20180224203645_591.gif">

I want to do like this。swipe past one below the next card like the right. please help me. thx

@bd-arc

**Comment by bd-arc** [comment]
@RoarRain You have [an entire documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md) dedicated to custom interpolations.

Be aware of [the miscellaneous caveats](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md#caveats) though.

**Comment by RoarRain** [comment]
thx very mach!
