### ISSUE TITLE
Carousel not working with dynamic data

### ISSUE THREAD

**Issue by zeeshanjan82** [archriss/react-native-snap-carousel#300]
I am trying to assign the dynamic data from api to the carousel in the below code:

![image](https://user-images.githubusercontent.com/8342604/38346171-fc142d58-38b0-11e8-942f-5946b6f1a3df.png)

however I am getting the following error:

![image](https://user-images.githubusercontent.com/8342604/38346149-dd3d54d6-38b0-11e8-9890-443fe38d0e67.png)

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Regarding your issue, see #253.**

**Comment by zeeshanjan82** [comment]
np I was able to resolve the issue :)

**Comment by SaraChicaD** [comment]
@zeeshanjan82 how did you resolve it? Anyone else: The issue I'm getting with dynamic data is that I'm trying to always have a set of 3 items, swap out the first and last, but then Carousel never recognizes that there are more than 3 items in the array. 

Does anyone have an example of how they solved this or got around it? 

So I have this: `data = [first, second, third]` and I have logic that's constantly updating _all three_ images, but the Carousel will only ever let me swipe to the 3 items.
