### ISSUE TITLE
firstItem does not work with Android.

### ISSUE THREAD

**Issue by cyphire** [archriss/react-native-snap-carousel#302]
### Is this a bug report or a feature request?

Bug Report

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

I didn't see it anywhere, other than the reference to the instability of the indexing on Android.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android

### Is the bug reproductible in a production environment (not a debug one)?

Yes - built it in production mode.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

No.  I would wonder if there were many people with the problem but with gitHub not providing any feedback loop other than creating a issue, there doesn't seem to be any way to know if it was a mistake using this repository.  I've used 4 different sliders like this, only this one seems not to use the native built in indexing but use a calculated offset.  Since it works on the first 10 or so items in my array, but not on any further down the list, I am sure that this is a problem with the way the firstItem is being calculated and if so - should be a warning to only use this for iOS.

### Environment

  Environment:
    React: 16.0.0
    React native: 0.51
    react-native-snap-carousel: 3.6.0

  Target Platform:
    Android (API 27)

### Steps to Reproduce

1.  First small number of items will correctly pick the correct item.
2.  Anything about 20 or so items in the array will NOT start with the correct index.

### Expected Behavior

I expected when I send an array of data to the carousel that it would start at the correct item in the array.  It does not.  It does not work in production either.  I would love to know if this is a known bug or issue.

### Actual Behavior

Very simple.  Does NOT go to the index as sent in.

### Reproducible Demo

					<Carousel layout={'default'}
						ref={(c) => { this._carousel = c; }}
						data={this.state.theData}
						firstItem={this.state.full_page_index}
						renderItem={(item, index) => this._renderItem(item, index)}
						sliderWidth={this.sn.tw}
						itemWidth={this.sn.height3}
						onSnapToItem={index => {
							this.setState({full_page_index: index}, 
								this._setNavigationParams(item.id));
				
						}}
						hasParallaxImages={true}
					/>

**Comment by bd-arc** [comment]
@cyphire This is an unfortunate `FlatList` bug that has been referenced in #63, #159, #235, #261 and #288.

Take a look at [this comment](https://github.com/archriss/react-native-snap-carousel/issues/235#issuecomment-354996464) to learn more about the exact matter and to find out potential workarounds.
