### ISSUE TITLE
At the example when loop true and scroll from last item to first item, it  comes up a flicker behaviour

### ISSUE THREAD

**Issue by xiaoshuangshuang** [archriss/react-native-snap-carousel#303]
At the example when loop true and scroll from last item to first item, it  comes up a flicker behaviour

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Regarding your issue, see #232**
