### ISSUE TITLE
feature request: willSnapToItem - callback triggered onPress release

### ISSUE THREAD

**Issue by jfrense** [archriss/react-native-snap-carousel#305]
### Is this a bug report or a feature request?

Feature Request

Feature:

for the onSnapToItem calllback, I noticed it gets triggered when the item has fully snapped into its next position (index). 

Is there a way for a new callback to get triggered so that when we know the delta threshold has been reached that will trigger a snapToItem, that a new callback is triggered as soon as the user releases a press from the item which would be called before the onSnapToItem callback.

maybe  "willSnapToItem" perhaps ?

**Comment by bd-arc** [comment]
@jfrense Wish granted in version `3.7.0` ;-)

A new callback method has been introduced: [`onBeforeSnapToItem()`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#callbacks). Enjoy!
