### ISSUE TITLE
[Feature request] flag for whether to trigger callback for snapToItem

### ISSUE THREAD

**Issue by jlo1** [archriss/react-native-snap-carousel#307]
Would like to add flag so that `onSnapToItem` can be disabled when the carousel is manually snapped via the method `snapToItem`.
e.g. `carousel.snapToItem(4, {:animated true :callback false})` would _not_ trigger the `onSnapToItem` callback.

Reason being that we want to trigger the callback when the item is snapped via the user swiping, but we don't want to trigger the callback when we programmatically snap to the item.

**Comment by bd-arc** [comment]
@jlo1 Wish granted in version `3.7.0` ;-)

[`snapToItem()`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#available-methods) now accepts an optional third parameter for this use case.
