### ISSUE TITLE
There's any way to disable scrolling by the touch, and scroll to specific item by index ?

### ISSUE THREAD

**Issue by betonix** [archriss/react-native-snap-carousel#309]
There's any way to disable scrolling by the touch, and scroll to specific index item?

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Regarding your question, the answer is yes. You'll find everything you need in [the doc](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md).**
