### ISSUE TITLE
Parallax image is not showing

### ISSUE THREAD

**Issue by sujitpk-perennial** [archriss/react-native-snap-carousel#310]
Hello team,

     Thanks for creating such fabulous library. I am using carousel to show the images in sections. I wrote following code. 

  ```
_renderCarouselRow({item, index}, parallaxProps) {
    return (
        <View style={{flex:1}}>
            <ParallaxImage
                style={{ marginLeft: 2, marginRight: 2, flex:1}}
                source={{uri:item.image}}    
                containerStyle={{width:sliderWidth - 30, height:300, backgroundColor:'red'}}
                parallaxFactor={0.4}
                blurRadiusStart={3}
                blurRadiusEnd={1}
                unBlurDuration={1000}
            />
            <Text style={{top:100,color:'black', alignSelf:'center'}} numberOfLines={2}>
                { item.title }
            </Text>
        </View>
    );
}

```
   Here I can't see the image on the screen. I can see red background color. My image uri is correct. I can see only loading indicator. I tried by hardcoding the image path, but still no luck. Also in the view I can't see text also. 
   Am I missing something? Please guide me.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the issue will be closed.**

Also, I don't know how you did come up with the following props as they never were implemented: `blurRadiusStart`, `blurRadiusEnd` and `unBlurDuration`.

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.

**Comment by ardyfeb** [comment]
where the solution ?

**Comment by thanh90** [comment]
I have the same issue
