### ISSUE TITLE
Example app error

### ISSUE THREAD

**Issue by hoangvuanhdevelopervn** [archriss/react-native-snap-carousel#311]
**I clone example app and run but it's not success. This is error.**

![simulator screen shot - iphone 6 - 2018-04-20 at 14 53 34](https://user-images.githubusercontent.com/29293495/39037410-a11110a0-44aa-11e8-9f34-60d496917001.png)

**Comment by bd-arc** [comment]
@hoangvuanhdevelopervn `npm` sometimes have trouble with relative file paths. Edit the example's `package.json` file and modify [line 13](https://github.com/archriss/react-native-snap-carousel/blob/master/example/package.json#L13) to the following:

`"react-native-snap-carousel": "3.7.0"`

This should solve your issue.

**Comment by IronTony** [comment]
I tried but I get the same error.
