### ISSUE TITLE
[react-native-snap-carousel] firstItem option not work

### ISSUE THREAD

**Issue by alexma01** [archriss/react-native-snap-carousel#312]
Hi guys,

I set firstItem={2} but not work, why?

Thanks

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the issue will be closed.**

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.
