### ISSUE TITLE
3.7.0  android , if set firstItem Greater than 4 or 5，the firstItem only display 4

### ISSUE THREAD

**Issue by neilzhengzx** [archriss/react-native-snap-carousel#313]
### Is this a bug report or a feature request?

bug report

in android ,i use Carousel with 8 page, when i set firstItem 7, Carousel only go to 4 page.but in ios, Carousel go to the current page.

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

yes

### Have you made sure that your issue hasn't already been reported/solved?

yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

only in android

### Is the bug reproductible in a production environment (not a debug one)?

yes

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?
 
```
<Carousel
          ref={this.setViewPager}
          data={data}
          renderItem={this._renderPage}
          onSnapToItem={this.onChangePage}
          loop={true}
          firstItem={7}
          sliderWidth={pageWidth}
          itemWidth={pageWidth}
          slideStyle={{ width: pageWidth, height: pageHeight }}
          apparitionDelay={0}
          autoplay={false}
 />
```
i have 8 page in data.

### Environment

  Environment:
    React: 16.2.0
    React native: 0.53.3
    react-native-snap-carousel: 3.7.0

  Target Platform:
    Android (8.0)

### Steps to Reproduce

<Carousel
          ref={this.setViewPager}
          data={data}
          renderItem={this._renderPage}
          onSnapToItem={this.onChangePage}
          loop={true}
          firstItem={7}
          sliderWidth={pageWidth}
          itemWidth={pageWidth}
          slideStyle={{ width: pageWidth, height: pageHeight }}
          apparitionDelay={0}
          autoplay={false}
 />
i have 8 page in data.
but in android, it goto 5 item;

### Expected Behavior

Carousel should be in 8 item;

### Actual Behavior

Carousel  be in 5 item;

### Reproducible Demo

its in my  whole project, so cant give a demo.
Thanks.

**Comment by cklinx** [comment]
Same problem here. I think is a rendering issue cause if you set a big value in 

> initialNumToRender={50}

it render more objects list but rendering performance decrease; Even if you set

> firstItem={49}

list show the 27 item.

**Comment by bd-arc** [comment]
@neilzhengzx @cklinx  This is an unfortunate `FlatList` bug that has been referenced in #63, #159, #235, #261, #288, #302...

Take a look at [this comment](https://github.com/archriss/react-native-snap-carousel/issues/235#issuecomment-354996464) to learn more about the exact matter and to find out potential workarounds.
