### ISSUE TITLE
 Is it possible to disable ios's right slide return?

### ISSUE THREAD

**Issue by iwangx** [archriss/react-native-snap-carousel#315]
### Is this a bug report or a feature request?

feature request

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

yes

### Have you made sure that your issue hasn't already been reported/solved?

no

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

both

### Is the bug reproductible in a production environment (not a debug one)?

yes

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

yes

### Environment

 Environment:
    React: 16.0.0
    React native: 0.51.0
    react-native-snap-carousel: 3.7.0

  Target Platform:
    Android (6.0)
    iOS (10.3)

### Expected Behavior

Disable ios's right slide return

### Actual Behavior

No such attribute

**Comment by bd-arc** [comment]
Hi @iwangx,

Can you explain what you mean by *"ios's right slide return"*?

If you're talking about the overflowing (or "bouncing") ability, read the section about [inherited props](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#inherited-props) again and set the `bounces` prop to `false`.
