### ISSUE TITLE
snapToItem animation with ease

### ISSUE THREAD

**Issue by QQizi** [archriss/react-native-snap-carousel#316]
### Is this a bug report or a feature request?

Feature request

Is it possible to snapToItem with animated as true with an ease ? So the animation look a little bit more natural ?

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

Yes

### Environment

 React: 16.0.0
 React native: 0.50.3
 react-native-snap-carousel: 3.5

### Steps to Reproduce

I'm using this plugin as a wheel that the user is supposed to throw. I want to add a button for the throw to happen. I'm using snapToItem with animated, works fine but the animation have no ease and is not natural. Is there a way to add an ease to snapToItem ?

### Actual Behavior

(Write what happened. Add screencasts/screenshots!)

**Comment by jonixj** [comment]
+1 The snap effect feels very unnatural.

**Comment by bd-arc** [comment]
@QQizi I totally get what you're after, and I'd really love to be able to implement it, but unfortunately this is out of my hands. Unless the Facebook team improves the `ScrollView` component and provides an option to do so, there is nothing I can do about it.

See #203 for more info and to vote for React Native's feature request.

**Comment by bd-arc** [comment]
See also #189 ;-)
