### ISSUE TITLE
At react-native-snap-carousel@3.7.0 not display inside the carousel ?

### ISSUE THREAD

**Issue by isurugajasinghe** [archriss/react-native-snap-carousel#317]
At react-native-snap-carousel@3.7.0 
first app launch it is not render the cards, after I click somewhere of screen or swap da carousel view, then display cards.

  _renderCarouselItem_Cards({ item, index }) {
    console.log('ITEEEEMMMMM : ', item.image) // this **log working with image names**
    return (
      <Image key={index} source={item.image} style={{
        height: 180,
      }} resizeMode="contain" />
    );
  }

  renderCarousel_Cards(cardList) {

    console.log('cardList : ', cardList)
    return (
      <Carousel
        vertical={false}
        sliderWidth={325} itemWidth={285}
        data={cardList}
        renderItem={this._renderCarouselItem_Cards}
        layout={'tinder'}
        loop={true}
      />
    );
  }

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the issue will be closed.**

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.
