### ISSUE TITLE
Example use of snapToItem()

### ISSUE THREAD

**Issue by Jonarod** [archriss/react-native-snap-carousel#32]
Dumb question but... How can I programaticaly jump to a given Item respecting animation ?
I see the documentation exposes a  snapToItem() method but... do you have some example of using it please?

**Comment by Jonarod** [comment]
Step 1: Define a Ref for the carousel

```
<Carousel
     // ... classic props
      ref={(myCarousel) => { this._myCarousel = myCarousel; }}
>
  <View />
  <View />
  <View />
</Carousel>
```
Step 2:  `this._myCarousel` now inherits methods from the Carousel component... So we can use it anywhere like this:

```
onPress={() => this._myCarousel.snapToItem() }
``` 

Cool methods are referenced in the [README](https://github.com/archriss/react-native-snap-carousel#methods)


@bd-arc @Exilz  I let you decide if this is relevant to be pushed to the docs or not. :)

**Comment by bd-arc** [comment]
@Jonarod [Done ;)](https://github.com/archriss/react-native-snap-carousel#methods) We thought this was pretty self-explanatory, but you're right: this can be tricky for developers who never had to use refs before. As a result, I've documented the two ways of keeping a reference to a component (as a string attribute or as a callback method).

Thank you for pointing this out!
