### ISSUE TITLE
Active item styling 

### ISSUE THREAD

**Issue by barnir** [archriss/react-native-snap-carousel#322]
Heya guys, i'm using this as a horizontal picker sort to speak... with text data (almost like the simple example on start page)
Is there a way to style the active item?

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Regarding your question, see #320.**
