### ISSUE TITLE
When set itemWidth={WINDOW_WIDTH * 0.8} doesn't works well

### ISSUE THREAD

**Issue by falcon11** [archriss/react-native-snap-carousel#323]
Environment:
"react": "16.3.1",
"react-native": "0.55.3",
iOS 11.3, iPhone 8 Plus

Unexpected bahavior:
when i set `itemWidth={WINDOW_WIDTH * 0.75}` works well, when i set `itemWidth={WINDOW_WIDTH * 0.8}` works unexpected as the gif show.

gif:
<img width=375 src="https://raw.githubusercontent.com/falcon11/Light/master/2018-05-12%2002_31_55.gif" />

this is my code, thanks.
````js
const WINDOW_WIDTH = Dimensions.get('window').width;

_renderItem({ item }) {
        return (
            <View style={styles.container}>
                <Text style={styles.welcome}>{item}</Text>
            </View>
        )
    }

    render() {
        return (
            <View>
                <View style={{ marginTop: 8 }} />
                <Carousel
                    ref={(c) => { this._carousel = c; }}
                    data={[1, 2, 3, 4, 5]}
                    renderItem={this._renderItem}
                    sliderWidth={WINDOW_WIDTH}
                    itemWidth={WINDOW_WIDTH * 0.8}
                    loop={true}
                    loopClonesPerSide={2}
                    autoplay={true}
                    autoplayDelay={500}
                    autoplayInterval={3000}
                />
            </View>
        )
    }

const styles = StyleSheet.create({
    container: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'green',
        height: 200,
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
    },
});
````

**Comment by falcon11** [comment]
It works fine on iPhone 8, but still works unexpected in iPhone 8 Plus.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Regarding your question, please read again the description of [the `loopClonesPerSide` prop](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#loop).**
