### ISSUE TITLE
[SOLVED] Implement dynamic autoplayInterval to display Images at different times.

### ISSUE THREAD

**Issue by PabloJimenez** [archriss/react-native-snap-carousel#325]
### Is this a bug report or a feature request?

Feature request...

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the feature specific to iOS or Android? 

Both

### Environment

    React: 16.0.0
    React native: 0.52.0
    react-native-snap-carousel: 3.7.0

  Target Platform:
    Android (6.0)+
    iOS (10.3)+

### Steps to Reproduce
I'm trying to achieve this with the current props and logic.

1. Set a dynamic autoplayInterval with a time state.
    a: Got a data array with 2 images, title, viewing_time_seconds, etc.
    b: Got a time state that would get the intervalTime of the data array -> this state updates (setState) whenever onSnapToItem prop gets called. (this works and I got some logs to see that it update correctly).

2. I'm sure that this "time" state its being update whenever the image change (from 1 image to another), but the autoplayInterval prop doesn't recognized the new time (even the time state has changed) and keeps updating at the same time forever.

3. In my example, I set the time state for 3 and 9 seconds, with 2 images (data>ads). When the index displayed its 0, it should wait 3 seconds -> change the image and and then it should wait 9 second before change to the first image, but it isn't doing this behavior... UNTIL: 
I manually 'scroll' to the next image, then the autoplayInterval props get the correct time of the selected image (for example it updates to 9 seconds) and then: IT STUCK in 9 seconds forever before I manually scroll again and then it gets the new intervalTime (that depends on the index of the data array).

### Expected Behavior

Feature:
It should wait the current autoplayInterval before change and slide to the next image. Example:
Wait 3 seconds to slide, then 9 seconds, then 3 seconds and so on.

### Actual Behavior

The carousel slide every 3 seconds and if I manually slide to the next image (and this image has its time attribute different: 9 seconds) -> it starts to slide every 9 seconds and stuck like that forever until I manually slide...

### My Carousel Code:

```
<Carousel
    ref={(c) => { this._carousel = c; }}
    data={ads}
    layout={'default'}
    renderItem={this.setViewItemsToCarousel}
    sliderWidth={windowSize.width}
    sliderHeight={windowSize.height}
    itemWidth={itemWidth}
    itemHeight={itemHeight}
    loop={true}
    autoplay={true}
    autoplayDelay={0} 
    autoplayInterval={this.handleTimeReturn()} // This method get the current time
    onSnapToItem={(index) => {
            this.setState({ indexInterval: ads[index].viewing_time_seconds }) // This works
    }}
/>

// Set images to the carousel.
setViewItemsToCarousel = () => {
 return (
    <View >
        <Image
            source={{ uri: adds.item.thumbnail }}
            style={{ height: adds.item.itemHeight, width: adds.item.itemWidth, marginTop: 30 }}
        />
    </View>
}

// get the current time of autoplayInterval
 handleTimeReturn = () => {
        return parseInt(this.state.indexInterval)
 }
```

Hope I explain myself correctly, thank you in advance!

**Comment by bd-arc** [comment]
Hi @PabloJimenez,

I can confirm that the current logic of the carousel doesn't allow for what you're after; some updates are required.

I'll look into it as soon as I can, but to be honest I haven't had much time recently to focus on the plugin. If you feel like working on a PR, do not hesitate ;-)

**Comment by PabloJimenez** [comment]
Hello I did solve my problem with the props of the Carousel and some logic, it is not the best way to do it because I have some minnor render issues with the Carousel and the transition of the images, but as they're minnor view issues it isn't a problem to us.

**What I did to achieve my problem:**

First I set a ref to my Carousel as the doc says:
`  ref={(c) => { this._carousel = c; }}
`


Then I set the autoplay prop as true so the Carousel starts alone:
 ```
  loop={true}
  autoplay={true}
  autoplayDelay={0}
```


Then I have to set this props:
```
enableMomentum={true}
lockScrollWhileSnapping={false}
```
If I did not set the enableMomentuns and lockScroll as I did (true and false), the carousel lose its behavior and starts to act strange.


Then the main core to achieve my goal was using the autoplayInterval prop with onSnapToItem prop as this:
```
 autoplayInterval={
                        this.handleTimeReturn()
                    }
```
where the handleTimeReturn looks like this:
```
    handleTimeReturn = (c) => {
        return parseInt(this.state.indexInterval)
    }
```
and the indexInterval state its just: 
```
this.state = {
            indexInterval: 3000,
        }
```


And the onSnapToItem props looks like this:
```
 onSnapToItem={(index) => {
                        this.setState({ indexInterval: ads[index].viewing_time_seconds })
                        this._carousel.stopAutoplay()
                        this.handleNextImage()
                    }}
```
Lets understand what are all of this:
First the setState of the indexInterval, it receive my Dynamic array of time interval in seconds, the INDEX value its the index of the element that the Carousel itself its displaying at the moment, this array its the DATA that I set to the carousel (`data={ads}`).
The second line stops the autoPlay of the carousel, it is necessary because it 'restarts' the values of carousel component itself... (I need more testing to be 100% sure of this XD)


The next its a method to handle the next image:
```
handleNextImage = (c) => {
        setTimeout(() => { this.nextImage(this._carousel) },    parseInt(this.state.indexInterval))
    }
```
With this method I 'force' with the setTimeout method, to sleep for 'N' (indexInterval) seconds the transition of images of the Carousel.


Then the nextImage method that would be called after the indexInterval seconds looks like this:
```
nextImage(carousel) { // I have to force pass the carousel prop because sometimes 'this._carousel' ref its null (Don't know why)
        if (this._carousel) {
            this._carousel.snapToNext()
        }
    }
```
This method use the ref of the carousel (that we previously set) and calls the "snapToNext()" that according to the Carousel documentation -> it "Snap to next item programmatically"...


This was 'all' the things (in reality they are easy to understand) I have to do to achieve: "Dynamic autoplayInterval to display Images at different times" 

**All the code example:**

```
return (
            <View>
                <Carousel
                    slideStyle={{ backgroundColor: '#FFFFFF00' }}
                    ref={(c) => { this._carousel = c; }}
                    data={ads}
                    layout={'default'}
                    renderItem={this.setViewItemsToCarousel}
                    loop={true}
                    autoplay={true}
                    autoplayDelay={0}
                    enableMomentum={true}
                    lockScrollWhileSnapping={false}
                    autoplayInterval={
                        this.handleTimeReturn()
                    }
                    onSnapToItem={(index) => {
                        this.setState({ indexInterval: ads[index].viewing_time_seconds })
                        this._carousel.stopAutoplay()
                        this.handleNextImage()
                    }}
                />
            </View>
        )
```

The methods are in the comment, except the setViewItemsToCarousel that its only a return of a View with a Image...

Hope it help some one :)

**Comment by bd-arc** [comment]
Hey @PabloJimenez,

Thanks a lot for sharing your solution! I'm sure this will come in handy for some users ;-)

**Comment by PabloJimenez** [comment]
Hello Benoit,

No problem man, if I have the time, I will try to improve it and make a
upload of the solution :)

Regards~
