### ISSUE TITLE
How to get currentItem on render / if onSnapToItem not fired.

### ISSUE THREAD

**Issue by tayfunyasar** [archriss/react-native-snap-carousel#326]
### Is this a bug report or a feature request?

Neither both. This is a simple question.

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes I did. But couldn't find.

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes I did. But couldn't find.

### Have you made sure that your issue hasn't already been reported/solved?

Yes I did. But couldn't find.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Trying on iOS simulator.

### Is the bug reproductible in a production environment (not a debug one)?

Nope.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

I didn't tried. Should I?

### Environment

Environment:
    React: 16.3.1
    React native: 0.55.3
    react-native-snap-carousel: ^3.7.0

  Target Platform:
    iOS (11.3 15E217)

### Expected Behavior

I'm expecting currentCard variable should be set on render.
I'm calling onCardActionActivateDeactivate() method without sliding(or snap?) cards and this.state.currentCardDetail is an empty object.

### Actual Behavior

currentCard variable be set after "onSnapToItem" method is fired.

### Reproducible Demo

```
class Cards extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      currentCardDetail: {}
    };
  }

  onCardActionActivateDeactivate() {
    this.props.navigator.showModal({
      screen: 'cards.activateCard',
      passProps: {
        cardDetail: this.state.currentCardDetail
      }
    });
  }

  renderCardItem ({item, index}) { 
      return (
        <View>
            <Button onPress={() => onCardActionActivateDeactivate()}><Label>{I18n.t('Cards.appealButton')}</Label></Button>
        </View>
      ); 
  }

  renderCards() {
    let cardsWithRequestNewCard = this.props.cards.cards.slice();
    cardsWithRequestNewCard.push({
      isRequestNewCard: true
    });
    return (
      <Carousel
        ref={(c) => { this._carousel = c; }}
        data={cardsWithRequestNewCard}
        renderItem={this.renderCardItem.bind(this)}
        sliderWidth={555}
        sliderHeight={55}
        itemWidth={555}
        onSnapToItem={(index) => {
          this.setState({ currentCardDetail: cardsWithRequestNewCard[index] }) // This works
        }}
      />
    );
  }

return (
      <Base>
        {this.renderCards()}
      </Base>
    );

  }
```

**Comment by bd-arc** [comment]
Hi @tayfunyasar,

I think you should be able to use [the `currentIndex` getter](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#getters).

**Comment by guisszo** [comment]
thanks this helped a lot.... ;)
