### ISSUE TITLE
example can not run.

### ISSUE THREAD

**Issue by pheromone** [archriss/react-native-snap-carousel#330]
example can not run.
<img width="310" alt="2018-05-29 4 17 03" src="https://user-images.githubusercontent.com/14305431/40646447-c11377e2-635b-11e8-9048-d86e8afbb577.png">

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Take a look at the error log; you'll see this has nothing to do with the plugin itself.**

**Comment by pheromone** [comment]
@bd-arc 
Let me just run your example.
I run the following environment:
![image](https://user-images.githubusercontent.com/14305431/40653706-8b411d78-636e-11e8-94bc-274f7e3cc9d2.png)
