### ISSUE TITLE
Switch to the next image, reset, and start again

### ISSUE THREAD

**Issue by pheromone** [archriss/react-native-snap-carousel#332]
Switch to the next image, reset, and start again.
npm -v  5.6.0
node -v  v8.11.2
"react-native": "0.55.4"
"react-native-snap-carousel": "^3.7.0",

code:
 {/*轮播*/}
                    <Carousel
                        data={data}
                        onSnapToItem={(index) => this.setState({ activeSlide: index }) }
                        renderItem={this._renderItem}
                        sliderWidth={width}
                        itemWidth={width - 60}
                        autoplay={true}
                        autoplayInterval={2500}
                        layoutCardOffset={20}
                        loop={true}
                    />
                    {/*轮播角标*/}
                    { this.pagination }

**Comment by pheromone** [comment]
fix ok, need to render the interface when the data request arrives......

**Comment by a289459798** [comment]
same +1

**Comment by a289459798** [comment]
@pheromone 怎么解决的？我现在是只要setState 就会重置

**Comment by pheromone** [comment]
@a289459798   忘了
