### ISSUE TITLE
Loop set to true will cause index to skip on loading.

### ISSUE THREAD

**Issue by daveteu** [archriss/react-native-snap-carousel#333]
### Is this a bug report or a feature request?

Bug Report

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes.

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

I'm only using iOS

### Is the bug reproductible in a production environment (not a debug one)?

Both Release and Production build.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Unable to test.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

When set loop = true, and you do your first swipe, it will jump a couple of images to the right instead of next image. This happens both in Simulator and phone.
```
        <Carousel
              ref={(c) => { this._carousel = c; }}
              data={images}
              renderItem={this._renderItem}
              sliderWidth={width}
              itemWidth={width}
              onSnapToItem={(index) => this.setState({ activeSlide: index }) }
              //loop={true} 
            />
```

### Environment

  Environment:
    react-native: 0.55.4
    react-native-snap-carousel": "^3.7.0"

  Target Platform:
    iOS (10.3)

### Steps to Reproduce

1. Install Snap Carousel
2. Set Loop to False and Swipe. 
3. Set Loop to True and Swipe

### Expected Behavior

When loop set to True, you should be able to swipe to next image. However, the first swipe will cause the image to jump several indexes.

### Actual Behavior

It jumped a few images to the right ( to the 2nd last image, instead of the 2nd image). It happened both in simulator and on attached device Iphone Plus and Iphone X

![carousel](https://user-images.githubusercontent.com/18649392/41038405-96768574-69c8-11e8-900d-2c2085b5e98b.gif)

Subsequent swipes after the first swipe is okay.

**Comment by shukiAnavi** [comment]
@daveteu 
How did you solve that?
I'm having the same problem.
