### ISSUE TITLE
Input inside Carousel Item causes jump back to previous item on swipe

### ISSUE THREAD

**Issue by steverob** [archriss/react-native-snap-carousel#336]
### Is this a bug report or a feature request?

This is a bug that happens when you have `<TextInput>` elements inside the carousel items.

When you swipe from `cardA` to `cardB`, if the `cardA` has an input and the user happens to be swipping by touching over the input, as `cardB` comes into view, the carousel snaps back to `cardA` and the input that was touched gains focus. It must be noted that when this happens `cardA` is not completely in view, the carousel stops as soon as the cursor is in view.

Here is a video showing the issue - https://nofile.io/f/J8OgZNggOHx/Input+issue+in+swiper.MP4

Here is the ReactNativeSnapCarousel example project edited with our issue reproduction - https://github.com/Hari70a/react-native-snap-carousel/blob/master/example/src/components/SliderEntry.js

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes 

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

Yes. Attached code above.

### Environment

    React: 16.3.0
    React native: 0.55.4
    react-native-snap-carousel: 3.6.0

### Steps to Reproduce

1. Add a `<TextInput>` element into the carousel items
2. Swipe the carousel by touching over the text input

### Expected Behavior

Carousel should move to the next item smoothly.

### Actual Behavior

Often, the carousel snaps back to the previous item and the `<TextInput>` gains keyboard focus.

https://nofile.io/f/J8OgZNggOHx/Input+issue+in+swiper.MP4

### Reproducible Demo

Here you go - https://github.com/Hari70a/react-native-snap-carousel/blob/master/example/src/components/SliderEntry.js

This is the official example project edited with our code that demonstrates the issue.

**Comment by bd-arc** [comment]
Hi @steverob,

Thanks for taking the time to put together a qualitative issue!

My guess is that the input focus messes with the scroll animation and therefore with the inner logic of the carousel ([some important code](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L745-L747) will never be triggered if the carousel hasn't had a chance to scroll to the new item position).

Is enabling prop `lockScrollWhileSnapping` having any effect? Another workaround might be to apply `pointerEvents={'none'}` to the inputs of every slide but the current one, and then to use `onSnapToItem()` to set it to `auto`.

**Comment by steverob** [comment]
@bd-arc AWESOME! :) The `pointerEvents` solution worked perfectly. `lockScrollWhileSnapping` did not work though.

Thanks so much!

**Comment by bd-arc** [comment]
@steverob You're welcome :-)
