### ISSUE TITLE
snap multiple items on fast scroll

### ISSUE THREAD

**Issue by geolabZura** [archriss/react-native-snap-carousel#341]
I am uploading  video record of my example. 

I want vertical scroll pagination. But it seems to have a bug while I am scrolling fast,  it is not snapping to next item, it returns on the active page. Also, I want to disable snapping multiple items simultaneously on fast and long swipe, I want to make it snap one by one in all cases. 

https://media.giphy.com/media/28evzIAPMMunZEnQBC/giphy.gif

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Regarding your issue, have you read [this section](https://github.com/archriss/react-native-snap-carousel#important-note-regarding-android) of the doc? See also #296 for more information about the 1-slide snap feature.**

**Comment by bd-arc** [comment]
Closing since no further feedback nor additional info were provided.

**Comment by jaroslav009** [comment]
have same issue
