### ISSUE TITLE
Pagination dots colours depending not only on active/inactive state? Is that possible?

### ISSUE THREAD

**Issue by AmeliaZielinska** [archriss/react-native-snap-carousel#343]
Hi, what I'm trying to achieve is showing something like 'completed steps' by carousels pagination, i.e.:
![zrzut ekranu 2018-06-26 o 09 44 08](https://user-images.githubusercontent.com/38068065/41896686-85523b78-7925-11e8-97b2-55fadca85799.png)
So when user is currently on step 2, then both first and second dot should be specific colour, not only the active (second) one. Is that even possible? If it is I'd appreciate any kind of help because despite reading the docs I haven't managed to do that on my own.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

---

Regarding what you're trying to do, you can't achieve that with the build-in `Pagination` component.

I recommend creating a custom component that will simply update its own state once, and to leverage prop `onSnapToItem(index)` to make it happen. See [this](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/index.js#L71)  for example.

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.
