### ISSUE TITLE
scrolling one slide at a time

### ISSUE THREAD

**Issue by sridhard** [archriss/react-native-snap-carousel#344]
Hi,

I am using react-native-snap-carousel to scroll one item/slide at a time. I have set enableMomemtum to false. 

When the user scrolls the slide fast, carousel will first scroll 3-4 slides forward and then comeback to the next slide. How to resolve this issue.

this problem is same as #27 and also #90

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**There is already an opened issue for that (#296), which contains an explanation about why this is not currently possible.**
