### ISSUE TITLE
last item scroll up broken

### ISSUE THREAD

**Issue by vish2595** [archriss/react-native-snap-carousel#345]
when my vertical stack carousel reaches the last item, I am not able to scroll back up normally, then only way the scroll works is if i scroll at the left or right margin.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the issue will be closed.**

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.

**Comment by riglar** [comment]
I can confirm this exists, I will write up a full issue template under a new ticket.

**Comment by riglar** [comment]
Re-raised in https://github.com/archriss/react-native-snap-carousel/issues/486
