### ISSUE TITLE
Support immutable object!

### ISSUE THREAD

**Issue by datvtwakumo** [archriss/react-native-snap-carousel#346]
### Is this a bug report or a feature request?

Feature Request

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes
### Have you made sure that your issue hasn't already been reported/solved?

Yes
### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

### Expected Behavior
Support Immutable data.
Current react-native-snap-carousel using Flatlist, which only support normal javascript object, however Immutable Object hasnot been support yet! Can you create one with VirtualList?
Thank for your support!

**Comment by bd-arc** [comment]
@datvtwakumo Unfortunately, swapping `FlatList` for `VirtualizedList` is not trivial by any means.

I'll accept a PR for that if you're willing to work on it and if you're able to do so without altering any the plugin features...
