### ISSUE TITLE
how to loop rotation when scroll to end of slide

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [archriss/react-native-snap-carousel#347]
![screen shot 2018-07-04 at 11 57 17 am](https://user-images.githubusercontent.com/33291479/42257604-71ba085e-7f81-11e8-8f15-634b5a2d1873.png)
i want to loop rotate per 1 side

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the issue will be closed.**

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.
