### ISSUE TITLE
Vertical Scroll view adds some extra vertical padding around inactive items.

### ISSUE THREAD

**Issue by ajaykumar97** [archriss/react-native-snap-carousel#348]
I am using react-native-snap-carousel for vertical carousel. But when I set vertically=true, inactive items get vertical padding like the below screenshot:
![simulator screen shot - iphone 6s - 2018-07-04 at 18 02 51](https://user-images.githubusercontent.com/38132295/42277297-849d9124-7fb4-11e8-80e0-06e793d72240.png)

My Carousel component looks like:
<Carousel
                    ref={(c) => { this._carousel = c; }}
                    data={this.state.data}
                    renderItem={this._renderItem}
                    vertical={true}

                    sliderHeight={200}

                    itemWidth={size.width}
                    sliderWidth={size.width}
                    itemHeight={250}
                    inactiveSlideOpacity={1}
                    inactiveSlideScale={0.6}
/>

And my render function looks like: 
_renderItem({ item, index }, parallaxProps) {
        return (
                <View
                    style={{
                        borderWidth: 1,
                        borderColor: 'yellow',
                        minHeight: 250,
                        alignItems: 'center',
                        justifyContent: 'center',
                        padding: 0,
                        margin: 0
                    }}
                >
                    <Text style={{ color: '#FFFFFF' }} >Demo Text</Text>
                </View>
        );
    }

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the thread will be closed.**

**Comment by ajaykumar97** [comment]
Here is snack.expo.io working example of the issue

https://snack.expo.io/@ajaykumar97/demo

**Comment by bd-arc** [comment]
What you call "vertical padding" is the necessary result of the scale effect. As you can see below, if you set `inactiveSlideScale` to `1` no extra padding is added.

![react-native-snap-carousel #348](https://i.imgur.com/M1zuTxuh.png)

**Comment by ajaykumar97** [comment]
But I need to have effect like as image below: 
 
![step1gif](https://user-images.githubusercontent.com/38132295/42287860-c45147cc-7fd5-11e8-91ce-79979618e585.gif)

Setting inactiveSlideScale to 1 will no longer be scaling inactive item. I changed animation style in defaultAnimationstyle from scale to scaleY to achieve vertical scaling.

**Comment by bd-arc** [comment]
If you need a custom animation, you should take a look at [the 'custom interpolations' section](https://github.com/archriss/react-native-snap-carousel#custom-interpolations) of the documentation.
