### ISSUE TITLE
slowly snapping, the onSnapToItem not run [Android]

### ISSUE THREAD

**Issue by little-buddy** [archriss/react-native-snap-carousel#350]
### Is this a bug report or a feature request?
This is a bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?
Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?
Yes

### Have you made sure that your issue hasn't already been reported/solved?
Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?
Android

### Is the bug reproductible in a production environment (not a debug one)?

no production environment

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

I think it's [React Native bug], but I don't see anyone newIssue at ReactNative[ Issue ], so I new Issue here(because I used the react-native-snap-carousel, then find the bug ), want to you can tell me something about feature of ScrollView(horizontal) in Android.I find that the carousel don't work  when I slowly snap, it can't back.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?
Yes 

### Environment

  Environment:
    React: 16.3.1
    React native: 0.55.4 => 0.55.4
    react-native-snap-carousel: 3.7.0

  Target Platform:
    Android (8.0.0)

### Steps to Reproduce

(Write your steps here:)

1. Android[ horizontal ], 
2. useScrollView
3. slowly snap , it don't work

### Expected Behavior
I want to Implement a DateComponent by your frame, this is can scroll and stop at ActiveItem

### Actual Behavior

Actually, it can't back activeItem, and it will stop between two Item then can't trigger fn[ onSnapToItem ]. I use react-native ScrollView[ single ] to test, find when use horizonatl, slowly snap. the onMomentumScrollEnd will not work, so it will be react native [bug]. Do you kone about it? If you konw, I hope you can tell me about you meet some problem when you create the carousel.

### Reproducible Demo
![image](https://user-images.githubusercontent.com/30054881/42417849-3eace3f8-82c6-11e8-92ac-2abbf9c09976.png)

The code :
![image](https://user-images.githubusercontent.com/30054881/42417844-2d8bd8c2-82c6-11e8-9c36-52df0d3e4d65.png)

**Comment by bd-arc** [comment]
Hi @little-buddy,

Could you share a [Snack example](https://snack.expo.io/) that reproduces the issue? Otherwise, there is no way for me to help you.

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.

**Comment by CrazyStoneJy** [comment]
Bad Attitudes, are you really want to solve this problem? @bd-arc
