### ISSUE TITLE
Slider align vertical

### ISSUE THREAD

**Issue by karimkhamwani** [archriss/react-native-snap-carousel#351]
How to slides items in vertical direction? not in horizontal direction

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Please read the doc, there is a dedicated prop for that: `vertical`.**
