### ISSUE TITLE
When I selected default layout,how can I  set the layoutCardOffset

### ISSUE THREAD

**Issue by qym790838213** [archriss/react-native-snap-carousel#352]
I want to set the distance of each card item,plz help me~~

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Please read [the doc](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/TIPS_AND_TRICKS.md#margin-between-slides) and take a look at prop `inactiveSlideScale`.**
