### ISSUE TITLE
Error when using the carousel in Animated.View

### ISSUE THREAD

**Issue by NdozHH** [archriss/react-native-snap-carousel#354]
### Is this a bug report or a feature request?

Bug

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

I only tried it on Android

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

Yes

### Environment

Environment:
    React: 16.3.1
    React native: 0.55.4
    react-native-snap-carousel: 3.7.2

  Platform:
    Android (5.1)

### Steps to Reproduce

1. I have a view with an animated Scrollview that contains an animated header that contracts when scrolling
2. The header had an image and I exchanged it for a carousel to have several images.

### Expected Behavior

I want the slide to work and the elements to respond to the onPress event when I place the carousel in an animated view within the scrolview.

### Actual Behavior

The carousel as a stand-alone component works well even if I wrap my images with touchableopacity (which is what I want to do when the slide works), but in the animated view, the manual slide does not work and does not respond to the TouchableOpacity onPress event.

### Reproducible Demo

`return (
      <View style={styles.Container}>
        <Animated.ScrollView
          style={styles.Container}
          scrollEventThrottle={1}
          onScroll={Animated.event(
            [{nativeEvent: {contentOffset: {y: this.state.HeaderScrollY}}}],
            {useNativeDriver: true}
          )}
        >
        {this._renderScrollViewContent()}
        </Animated.ScrollView>
        <Animated.View
          pointerEvents="none"
          style={[styles.Header, {transform: [{translateY: HeaderTraslate}]}]}
        >
        <Animated.View
          style={[styles.SitePhotoContainer, {opacity: ImageOpacity, transform: [{translateY: ImageTraslate}]}]}>
          <View style={{flex:1, backgroundColor: 'blue'}}>
            <Carousel
              ref={(c) => { this._carousel = c; }}
              data={this.state.SitePhotos}
              renderItem={this._renderItem}
              sliderWidth={width}
              itemWidth={width}
            />
          </View>
        </Animated.View>
        </Animated.View>
        <Animated.View
          style={[styles.TittleBar,{transform: [{scale: TittleScale}, {translateY: TittleTraslate}]}]}
        >
          <Text style={styles.Tittle}>{Name}</Text>
        </Animated.View>
      </View>
    );`

![imagen](https://user-images.githubusercontent.com/25773289/42551149-81d00486-849b-11e8-91d6-55206c66b1df.png)

**Comment by bd-arc** [comment]
Hi @NdozHH,

From a quick glance at your code, I can see that your `Carousel` is wrapped in an `Animated.View` with `pointerEvents="none"`. Couldn't it be the root of your issue?

**Comment by NdozHH** [comment]
@bd-arc Thanks, of course I did, that's it; I hadn't thought about it.
