### ISSUE TITLE
Feature/Question: Programmatically Scroll variable amount

### ISSUE THREAD

**Issue by joecaraccio** [archriss/react-native-snap-carousel#356]
### Is this a bug report or a feature request?

Feature Request.. more of a question as I wouldn't be suprised if it is already implimented

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md) regarding bug report?

Yes
### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

Does anyone know of a way to scroll a variable amount? I know there is a method to snap to items, where I can programmatically switch from item 0 to item 1.

Does anyone  know of a way, or a way to implement a scroll to position feature, where if I wanted to scroll by 10, or 20, or 25 (with snapping off obviously) I could? I think thats built into scrollview but I am not sure how I would do it here.

Any ideas? Does something like this exist?

Sorry if this is a dumb question! I couldn't find anything like it in the documents

**Comment by bd-arc** [comment]
Hi @joecaraccio,

I confirm that the plugin [inherits `ScrollView`'s props and methods](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#inherited-props). You should therefore be able to call [`scrollTo()`](https://facebook.github.io/react-native/docs/scrollview#scrollto) whenever needed, as long as [a reference to the component](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#reference-to-the-component) is available.

One word of caution though: you might experience hazardous behaviors when doing so. Enter at your own risk ;-)
