### ISSUE TITLE
carousel stop when i swiper to right, it can't loop

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [archriss/react-native-snap-carousel#358]
![screen shot 2018-07-04 at 11 57 17 am](https://user-images.githubusercontent.com/33291479/42854575-a11ea4f2-8a66-11e8-9ea9-e45388486e55.png)
my code:
```
<Carousel
                    layout={'default'}
                    data={this.state.entries}
                    renderItem={this._renderItem.bind(this)}
                    sliderWidth={viewportWidth}
                    itemWidth={viewportWidth*0.575}
                    loop={true}
                    firstItem={2}
                    loopClonesPerSide={10}
                    //enableMomentum={true}
                    enableSnap={true}
                    inactiveSlideScale={0.95}
                    inactiveSlideOpacity={0.8}
                    onSnapToItem={(index) => this.setState({currentSwiperFilm:index}) }
/>
```
example when i swiper end of right, slider not loop
![68747470733a2f2f692e696d6775722e636f6d2f574e4f4259666c2e676966](https://user-images.githubusercontent.com/33291479/42922191-c8a35138-8b49-11e8-9c66-057142854898.gif)

**Comment by nguyenvanphuc2203** [comment]
i had add gif image demo my issue, please help me :(

**Comment by nguyenvanphuc2203** [comment]
![screen shot 2018-07-19 at 11 56 30 am](https://user-images.githubusercontent.com/33291479/42922476-daae1d9e-8b4a-11e8-9963-c8fca5f42c2b.png)
i see in docs props , Number of clones to append to each side of the original items, but it not append to end of right

**Comment by bd-arc** [comment]
@nguyenvanphuc2203 Ok, so you not only don't care about what's asked of you in order to assist you (e.g. reading and filling the issue template, providing a snack example), you also downvote the very people who are devoting their spare time to maintain/improve the plugin and help others.

This behavior is not appreciated here and is not going to get you anywhere. Good luck figuring things out on your own!

**Comment by LuisRodriguezLD** [comment]
@bd-arc Hello, I am so sorry on how you get treated sometimes. I strongly believe open source project maintainers are extremely underrated. 

I have made a [snack](https://snack.expo.io/@luisrodriguezld/snap-carousel-bug) showing the issue, but there is something weird going on, it works on expo's web simulator but not on device.

The issue again, is the it loops to the left but not to the right.

If you have the time, please test the snack on a real iOS device using the Expo App

**Comment by bd-arc** [comment]
Hi @LuisRodriguezLD,

I'll soon be working on an update that, hopefully, will fix a lot of issues like this one. Fingers crossed though, because it will still rely on `ScrollView` and `FlatList` which have a long history of not being that reliable...

**Comment by hikopublic** [comment]
> Hi @LuisRodriguezLD,
> 
> I'll soon be working on an update that, hopefully, will fix a lot of issues like this one. Fingers crossed though, because it will still rely on `ScrollView` and `FlatList` which have a long history of not being that reliable...

does it resolve ????

**Comment by RuzenDev** [comment]
i am having the same problem. Has anyone fixed this issue

**Comment by kevingo710** [comment]
Hi everyone, I have opened a [PR](https://github.com/meliorence/react-native-snap-carousel/pull/1012) with a possible solution for this issue.
