### ISSUE TITLE
Is it possible to refresh the control manually?

### ISSUE THREAD

**Issue by gersonmontenegro** [archriss/react-native-snap-carousel#359]
I don't know under what template put this question. Is not a bug, is not a problem actually, I just wanna to know if it is possible, just in case.

If not, there is any way to do that?. Thanks

**Comment by bd-arc** [comment]
I'm not entirely sure about what you're trying to do. Does [this SO thread](https://stackoverflow.com/questions/43397803/how-to-re-render-flatlist) answers your question?

> Note that our `Carousel` component is based upon the `FlatList` one.

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.
