### ISSUE TITLE
Invariant Violation: VirtualizedList: The windowSize prop must be present and set to a value greater than 0

### ISSUE THREAD

**Issue by yasir-netlinks** [archriss/react-native-snap-carousel#360]
I am getting error as shown in the title
react-native: 0.56.0
react-native-snap-carousel: ^3.7.2

```
const horizontalMargin = 20;
const slideWidth = 280;

const sliderWidth = Dimensions.get("window").width;
const itemWidth = slideWidth + horizontalMargin * 2;
const itemHeight = 100;
//

_renderItem = ({ item }) => {
    return (
      <View style={style.slide}>
        <View style={style.slideInnerContainer} />
      </View>
    );
  };
  render() {
    return (
      <View style={style.container}>
        <Carousel
          data={[{ key: "1" }, { key: "2" }, { key: "3" }]}
          renderItem={this._renderItem}
          slideWidth={sliderWidth}
          itemWidth={itemWidth}
        />
      </View>
    );
  }
```

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the thread will be closed.**

**Comment by yasir-netlinks** [comment]
I created a a fresh project, installed `react-native-snap-carousel` and simply ran the app with the code above, and I'm getting this error, I honestly don't know what else to tell you

**Comment by yasir-netlinks** [comment]
Ok I added `windowSize={1}` and it worked

**Comment by gautham20** [comment]
I'm facing the same issue, and `windowSize={1}` did not fix it

**Comment by CristopherAguilarh** [comment]
maybe you passed the "slideWidth" property as string, that expect a integer.

**Comment by viv3kk** [comment]
provide both
sliderWidth={400}
itemWidth={400}

**Comment by bardiarastin** [comment]
for anyone reaching here this lib warns in case you do not specify sliderWidth and itemWidth while they are required in horizontal mode
```
react-native-snap-carousel: You need to specify both `sliderWidth` and `itemWidth` for horizontal carousels
```
actually if you take a look at prop types
```
itemWidth: PropTypes.number, // required for horizontal carousel
itemHeight: PropTypes.number, // required for vertical carousel
sliderWidth: PropTypes.number, // required for horizontal carousel
sliderHeight: PropTypes.number, // required for vertical carousel
```

I believe that these lines 

https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L158
https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L161

should use console.error

because this way the user will see this error

![image](https://user-images.githubusercontent.com/20615964/58552231-2a81dd00-8227-11e9-9b67-7d5eb59bc894.png)

instead of this weird complicated one which is from react native's virtualized list

![image](https://user-images.githubusercontent.com/20615964/58552352-703ea580-8227-11e9-9fc9-7edbe2d3d445.png)

@bd-arc if this seems fine to you i'll be happy to make a PR.

**Comment by bd-arc** [comment]
@bardiarastin You're totally right! Looking forward to seeing that PR ;-)

**Comment by bardiarastin** [comment]
@bd-arc there you go https://github.com/archriss/react-native-snap-carousel/pull/528 <3

**Comment by ChauVV** [comment]
react-native: 0.59.9
react-native-snap-carousel: ^3.8.0

my app crash with same this error.

**Comment by sagarrs** [comment]
> I'm facing the same issue, and `windowSize={1}` did not fix it

hi @gautham20 kill the app and try restarting it, it worked for me. hope this helps

**Comment by ZeroCool00** [comment]
Any solution to this problem 
![Simulator Screen Shot - iPhone 11 - 2020-05-06 at 12 11 46](https://user-images.githubusercontent.com/18139594/81144997-eea4db00-8f92-11ea-90de-66fb63bd00b5.png)

**Comment by ZeroCool00** [comment]
I always get this error first time, when I open this page.
 I have to restart application, and its working, Any solution to this problem.

**Comment by rafaeldalpra** [comment]
FWIW I had this issue when I was trying to use `em` for slide width. Changing to a `Number` fixes the issue.

**Comment by Annsh5** [comment]
The app crashes and bug report gives this error. Was wondering if anyone knows a particular way to reproduce this issue on iphone?

**Comment by Annsh5** [comment]
The app crashes and bug report gives this error. Was wondering if anyone knows a particular way to reproduce this issue on iphone?

**Comment by sandeepDevJs** [comment]
> const sliderWidth = Dimensions.get("window").width;
> const itemWidth = slideWidth + horizontalMargin * 2;

That worked for me! Thanks man!

**Comment by choseonghwan91** [comment]
저는 속성을 잘못 지정해서 똑같은 에러가 발생했습니다.

```
     <Carousel
              data={[1, 2, 3, 4, 5]}
              renderItem={component}
              slideWidth={360}
              itemWidth={360 * 0.68}
            />
```

slideWidth -> sliderWidth

```
     <Carousel
              data={[1, 2, 3, 4, 5]}
              renderItem={component}
              sliderWidth={360}
              itemWidth={360 * 0.68}
            />
```
