### ISSUE TITLE
Paginagion:When I clicked dot, the picture was switched, but the timer did not start again.

### ISSUE THREAD

**Issue by shx1545** [archriss/react-native-snap-carousel#361]

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the thread will be closed.**

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.
