### ISSUE TITLE
Change Pagination vertical margin

### ISSUE THREAD

**Issue by matteoferigo** [archriss/react-native-snap-carousel#362]
Hi, I'm working with version `3.7.2`.

How can I change Pagination vertical margin/padding? I tried setting values to containerStyle, dotContainerStyle and dotStyle… but nothing changes.

**Comment by bd-arc** [comment]
Hi @matteoferigo,

Could you please provide a simple [Snack example](https://snack.expo.io/) with your setup so I can take a look at it?

**Comment by matteoferigo** [comment]
Hi @bd-arc , here is my sample: https://snack.expo.io/@matteoferigo/carousel-dots
I would like to reduce the edge between the carousel and the image below. How can I do that?

**Comment by bd-arc** [comment]
I'm surprised that changing `containerStyle` didn't have any effect for you in the first place because I've just tested the following and it works as expected:

```
<Pagination containerStyle={{ paddingVertical: 0 }} />
```

Or maybe you've indeed tried with `paddingTop` and `paddingBottom`, but not with `paddingVertical` ;-)

**Comment by matteoferigo** [comment]
You got it. I tried with `paddingTop` and `paddingBottom` but I didn't find the `paddingVertical` reference.
I also found an interesting `marginHorizontal` to apply on `dotContainerStyle`.
Thanks

**Comment by WhiteNightMorningStar** [comment]
hi, bd-arc.
thank you.

**Comment by nickjuntilla** [comment]
It makes sense to not try marginHorizontal or paddingVertical since those don't exist in CSS.
