### ISSUE TITLE
inputRange must be monotonically, what is it ?, excuse I am news in this.

### ISSUE THREAD

**Issue by bpdarlyn** [archriss/react-native-snap-carousel#364]
<img width="321" alt="screen shot 2018-07-27 at 20 33 08" src="https://user-images.githubusercontent.com/13193490/43351166-55da60b2-91dc-11e8-88a5-48a042c02319.png">

**Comment by cauyeung-wco** [comment]
What solved this for me was making sure the prop itemWidth was set properly.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**This question has a direct answer in the doc.**

**Comment by gbettinazzi** [comment]
@bd-arc can you please link where this problem is addressed in the doc?

**Comment by bd-arc** [comment]
@gbettinazzi It's been 3 years, so I might be mistaken, but I think it's [this one](https://github.com/meliorence/react-native-snap-carousel/blob/9c39995f4813f0e8ee1be7797512f4e89708167f/doc/CUSTOM_INTERPOLATIONS.md#prop-scrollinterpolator) (in the "custom interpolations" doc).

Specifically:

> _⚠️ Both arrays must have the same length, otherwise you'll get an error._
