### ISSUE TITLE
problem in landscape orientation

### ISSUE THREAD

**Issue by eng0mustafa** [archriss/react-native-snap-carousel#365]
hello sir,

i use the example but i have problem when i try to rotate device (landscape orientation)
i read the tricks of handling device rotation 

![simulator screen shot - iphone 6 - 2018-08-01 at 11 25 53](https://user-images.githubusercontent.com/29033508/43510338-ffd2eb58-957d-11e8-915a-81fec6758508.png)

is there any way to solve that ?

Thank you

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.

**Comment by parveenBanuS** [comment]
When changing the portrait to landscape the image show perfectly but after rotate the image it shows different images like i have 52 images i am viewing index 10 image but when i change portrait to landscape it shows index 20 or other index image.
