### ISSUE TITLE
Nested Carousels not working

### ISSUE THREAD

**Issue by swati-kholiya** [archriss/react-native-snap-carousel#366]
I have Cards which I am rendering as slides(full screen card) .Each card has galaries of images within it . Is it possible to implement this ? I tried but galaries are not swiping up. Instead on gallery swipe , i see entire Card swiping up.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**
