### ISSUE TITLE
Is it possible to nest fixed height carousels inside full screen carousel? 

### ISSUE THREAD

**Issue by swati-kholiya** [archriss/react-native-snap-carousel#367]
### Is this a bug report, a feature request, or a question?

Question

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - replace the space character between the square brackets (`[]`) by an `x`.)

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Environment

Environment:
    React: 16.3.1
    React native: 0.55.0
    react-native-snap-carousel: 3.7.2

  Target Platform:
    Android (6.0)
    iOS (10.3)

**Comment by bd-arc** [comment]
Hi @swati-kholiya,

I've never done it so far. It is theoretically possible, but I tend to advise against it unless you have a small number of slides to display.

Apparently, nesting components based on `ScrollView` (such as `VirtualizedList`, `FlatList` and this plugin) results in every child being rendered, even those currently off-screen. This will lead to extremely poor performance unless you render only a small set of items.

Do not hesitate to share a Snack example that shows us everything you've tried so far!
