### ISSUE TITLE
How to show edge of previous card in stack layout

### ISSUE THREAD

**Issue by jariwalabhavesh** [archriss/react-native-snap-carousel#370]
### Question

1. How to show bit of edge of previously swipe card in **stack** layout?  any have idea regarding. so it will be like edge of previous card on left and then stack of card,  as i swipe stacked card,  instead of hiding swiped card, It's edge should be visible at left side of stack so user will come to know by seeing that there is card on left he/she can swipe left to get it back.

[X] I have read the guidelines regarding bug report.
[X]  I have reviewed the documentation in its entirety.
[X] I have searched for existing issues and made sure that the problem hasn't already been reported.
[X]  I am using the latest plugin version.
[X]  I am following the issue template closely in order to produce a useful bug report.

Environment:
React: 16.0.0-beta.5
React native: 0.49.0
react-native-snap-carousel: 3.7.2

**What i want is**
![screenshot_20180809-130817](https://user-images.githubusercontent.com/10993666/43885625-0a881e4c-9bd7-11e8-80da-2f0b08585c37.jpg)

**Comment by bd-arc** [comment]
@jariwalabhavesh This should be pretty easy, thanks to [custom interpolations](https://github.com/archriss/react-native-snap-carousel#custom-interpolations). I'll try to do it and put it in a Snack example for you ;-)

In the meantime, make sure to read [the dedicated documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md), particularly the "drawbacks" section.

**Comment by jariwalabhavesh** [comment]
@bd-arc 
Thanks for response and reference link

**Comment by bd-arc** [comment]
@jariwalabhavesh I didn't have time to create a Snack example, but it should work if you reuse stack effect's [interpolator](https://github.com/archriss/react-native-snap-carousel/blob/master/src/utils/animations.js#L116-L124) and [styles](https://github.com/archriss/react-native-snap-carousel/blob/master/src/utils/animations.js#L125-L198), and then change lines [186 to 193](https://github.com/archriss/react-native-snap-carousel/blob/master/src/utils/animations.js#L125-L198) to the following:
```
                inputRange: [-1, 0, 1, 2, 3],
                outputRange: [
                    0, // This is the value that needs to be changed
                    0,
                    getTranslateFromScale(1, card1Scale),
                    getTranslateFromScale(2, card2Scale),
                    getTranslateFromScale(3, card2Scale)
                ],
```

**Comment by jariwalabhavesh** [comment]
@bd-arc 
Thanks, i am able to do it with you hint.
Thanks a lot for quick response.

**Comment by AlirezaAzizi145** [comment]
how did you solve it?

**Comment by AlirezaAzizi145** [comment]
i am new in react native and i want to show edge of previous too. i read documentation but still i cant create that
