### ISSUE TITLE
Add a note in the docs about turning "Slow animations" off (iOS Simulator only)

### ISSUE THREAD

**Issue by rapind** [archriss/react-native-snap-carousel#374]
### Is this a bug report, a feature request, or a question?

Documentation suggestion.

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - replace the space character between the square brackets (`[]`) by an `x`.)

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

iOS Simulator only. Documentation.

I just wanted to suggest that you add a note to the documentation about turning off the iOS simulator's "Slow Animations" in the "Debug" menu. I was evaluating the library and moving between animations was horribly slow. Spent about 30 minutes to an hour poking around before landing on an  Open but unrelated issue where someone else solved their problem by turning off "Slow Animations".

It's completely common sense that we should turn this off, but I suspect I'm not the only one who "forgot" about the "Slow animations" setting and instead figured something was either wrong with their setup or that this library wouldn't work for them.

In my case, everything perfect now that I've turned it off!

**Comment by bd-arc** [comment]
@rapind Thank you for this sound suggestion!

I've just [added it](https://github.com/archriss/react-native-snap-carousel#important-note-regarding-ios) to the doc, with a screenshot in order to make things perfectly clear ;-)
