### ISSUE TITLE
using KeyboardAvoidingView

### ISSUE THREAD

**Issue by 3luyka** [archriss/react-native-snap-carousel#377]
It's possible to use "KeyboardAvoidingView" with carousel? Inside or Outside carousel?

**Comment by bd-arc** [comment]
@3luyka You shouldn't have any issue including the carousel inside a `KeyboardAvoidingView`. I wouldn't do it the other way though.

Do not hesitate to create a [Snack example](https://snack.expo.io/) with your trials and to share it with us.
