### ISSUE TITLE
How to set paddingRight on slide container?

### ISSUE THREAD

**Issue by tgmcguire** [archriss/react-native-snap-carousel#378]
Hey there! I have a carousel where I'm trying to eliminate the `paddingRight` after the slides:

<img width="391" alt="screenshot 2018-08-21 11 13 22" src="https://user-images.githubusercontent.com/2480113/44420596-3a9bbc00-a533-11e8-9153-ce1af65e9a1d.png">

I tried specifying the `contentContainerStyle` with something like `paddingRight: 20`, like so:

```jsx
<Carousel
	{...props}
	ref={c => {
		this._carousel = c;
	}}
	layout={"default"}
	renderItem={this._renderItem}
	sliderWidth={sliderWidth}
	itemWidth={itemWidth}
	loop={false}
	inactiveSlideScale={1}
	inactiveSlideOpacity={1}
	activeSlideAlignment={"start"}
	containerCustomStyle={{ paddingRight: 20 }}
/>
```

... but it looks like `_getComponentStaticProps` overrides any padding specified in the `contentContainerStyle` prop:

```js
const contentContainerStyle = [
    contentContainerCustomStyle || {},
    vertical ? {
        paddingTop: this._getContainerInnerMargin(),
        paddingBottom: this._getContainerInnerMargin(true)
    } : {
        paddingLeft: this._getContainerInnerMargin(),
        paddingRight: this._getContainerInnerMargin(true)
    }
];
```

To try this out, I swapped `paddingRight: this._getContainerInnerMargin(true)` with `paddingRight: 20`, and achieved my ideal result:

<img width="388" alt="screenshot 2018-08-21 11 15 49" src="https://user-images.githubusercontent.com/2480113/44420752-a2ea9d80-a533-11e8-9886-3a1f65b276e8.png">

I'm newer to React overall – is there any way I can get around this to manually specify the `paddingRight` value I'm hoping for? 😄 

Thanks so much!

**Comment by bd-arc** [comment]
@tgmcguire Unfortunately, by doing so you might have messed with the inner logic of the carousel. Is `onSnapToItem(index)` still called with the proper index and at the right time?

If yes, then you're clearly onto something ;-)

If no, please see [this comment](https://github.com/archriss/react-native-snap-carousel/issues/102#issuecomment-343880254) and the follow-up discussion.

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.
