### ISSUE TITLE
Android slide disappear

### ISSUE THREAD

**Issue by 3luyka** [archriss/react-native-snap-carousel#379]
I'm using "TextInput" inside carousel slide and when keyboard is showing on Android slide is disappear.

Versions of packages:
RN: 0.56
Snap-carousel: 3.7.2
Android OS: Android 6.0

**Comment by naomipol** [comment]
@3luyka I also have this issue and found it is caused by ta React Native bug reported here:
https://github.com/facebook/react-native/issues/21867
