### ISSUE TITLE
Question - How to control rendering timing ?? 

### ISSUE THREAD

**Issue by miya1201** [archriss/react-native-snap-carousel#384]
Instead of rendering at the same time, I want to render a few and render a new slide at the same time as snapping.
How to do this ?

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

**Comment by miya1201** [comment]
### Is this a bug report, a feature request, or a question?

question

Instead of rendering at the same time, I want to render a few and render a new slide at the same time as snapping.
How to do this ?

![untitled 3x](https://user-images.githubusercontent.com/37892222/44776843-fef89600-abb3-11e8-880a-f01ba64e477d.png)

![untitled2 3x](https://user-images.githubusercontent.com/37892222/44776850-061fa400-abb4-11e8-98d2-10c6ac3915b9.png)



### Have you followed the required steps before opening a bug report?

- [ x ] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [ x ] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [ x ] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [ x ] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [ x ] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

ios

### Environment


    React: 16.3.1
    React native: 0.55.3
    react-native-snap-carousel: 3.7.2

  Target Platform:
    iOS 11.4

**Comment by bd-arc** [comment]
@miya1201 Short answer: leverage props `onEndReached` and `onEndReachedThreshold` which are inherited from `VirtualizedList`.

Long answer: this question has been addressed in #139, #308, #201, #285, #297... Take a look at this threads for more information and some user feedback.

**Comment by miya1201** [comment]
@bd-arc thank you
