### ISSUE TITLE
Feature request - Support pagination on both sides of the list. 

### ISSUE THREAD

**Issue by srameshr** [archriss/react-native-snap-carousel#386]
### Is this a bug report, a feature request, or a question?

Feature request

Could you try to support pagination on either side of the list? More explanation here: https://github.com/facebook/react-native/issues/20500

### Have you followed the required steps before opening a bug report?

- [x ] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [ x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x ] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [ x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [ x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Specifically, it is a feature request for FlatList. I am not sure, if you would try to support this feature until RN adds this in FlatList.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

BOTH

### Is the bug reproductible in a production environment (not a debug one)?

YES

### Environment

Environment:
    React: 16.4.1
    React native: 0.55
    react-native-snap-carousel: 3.7.2

  Target Platform:
    Android (6.0)
    iOS (10.3)

### Expected Behavior

Use case:
1. For records from **0 to 100,** you load records from **45 to 55** to the UI on the **first mount** of the component and _render 50th element to the user's view._
2. On s**croll left or up** obtain records from **44 to 35** and **prepend** to the list.
3. Vice versa for scroll right or down.

### Actual Behavior

Feature missing for the same.

### Reproducible Demo

None

### Steps to Reproduce

As mentioned in the **Expected Behaviour**

**Comment by bd-arc** [comment]
Hey @srameshr,

While I agree that this would be a top-notch feature, we're not willing to alter `FlatList`'s core since it is already a big buggy mess...

Note that we are currently working on replacing `FlatList` with another component; see #250 if you want more info ;-)

I'm going to close the issue, but make sure to keep us posted if the component is updated by the Facebook team.
