### ISSUE TITLE
installation failed 

### ISSUE THREAD

**Issue by ZeroCool00** [archriss/react-native-snap-carousel#388]
i run this code: `npm install --save react-native-snap-carousel`
and get this error: 
```
code ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! errno ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! request to https://registry.npmjs.org/react-native-snap-carousel failed, reason: Hostname/IP does not match certificate's altnames: Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net

```

npm: 6.2.0
react-native: 0.56
os: macOs high sierra

**Comment by bd-arc** [comment]
**Useful link: http://lmgtfy.com/?q=npm+%22ERR_TLS_CERT_ALTNAME_INVALID%22**

---

**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

**Comment by ZeroCool00** [comment]
Thank you so much for solution.. i didnt realize its that simple.. i thought its library problem..
i solved by using `yarn add react-native-snap-carousel`, you should add this line in documentation.
