### ISSUE TITLE
Non-standard implementation

### ISSUE THREAD

**Issue by NewOldMax** [archriss/react-native-snap-carousel#39]
Hi! Thanks for this awesome library!
Can I build something like this with it?
![asd24](https://cloud.githubusercontent.com/assets/1328473/23306272/d1e7376e-fab3-11e6-8751-c7e174af8ac6.gif)

**Comment by bd-arc** [comment]
@NewOldMax Absolutely :) The only distinctive characteristic of your example is the background animation. In order to do that, you'll need to rely on the `onSnapToItem` prop. It will then be easy to update the color based on current slide's index.

Still, be aware that, as stated in [this issue](https://github.com/archriss/react-native-snap-carousel/issues/34), the callback will be fired immediately after clicking. If this is not a deal-breaker for you, you're good to go.

Do not hesitate to share your experimentations!

**Comment by NewOldMax** [comment]
I already implemented it :)
It works fine with touches, but I have some issues with swipe, for example, i can't swipe to end of carousel at one time, or sometimes position of last element is wrong
![asd25](https://cloud.githubusercontent.com/assets/1328473/23307130/73edd290-fab7-11e6-80db-370c7ad157fd.gif)

**Comment by bd-arc** [comment]
@NewOldMax Cool ;) Regarding your issues:
- Scroll inertia varies depending on slide's size relative to viewport's size, e.g. the larger your slide is, the more difficult it is to swipe more than one slide at a time. You can try playing with [this ScrollView prop](https://facebook.github.io/react-native/docs/scrollview.html#decelerationrate) and see if it helps.

- The positioning issue is clearly the same as #33, but I wasn't able to reproduce it, either on a simulator nor a real device... Would you mind sharing the source code of your project so I can take a look at it? You can mail a zip file to me if you don't want it to go public ;)

**Comment by NewOldMax** [comment]
> Would you mind sharing the source code of your project so I can take a look at it? 

I'll create some reproduction component on next week.

> You can try playing with this ScrollView prop and see if it helps.

Unfortunately I'm working only with android, so this prop couldn't help me :(

**Comment by bd-arc** [comment]
> Unfortunately I'm working only with android, so this prop couldn't help me :(

And does playing with `enableMomentum` change anything for you?

**Comment by NewOldMax** [comment]
As I remember, with momentum behavior was strange, but I'm not sure

**Comment by NewOldMax** [comment]
Seems to I fixed wrong offset with dynamic changing width of items.
````
const itemWidth = width * (index === 2 ? 0.6 : 0.65);
````
where index = 2 - my last item
After this I can't reproduce case with wrong position.

**Comment by bd-arc** [comment]
@NewOldMax Ok, good to know. I confirm that dynamically changing items' width will lead to issues since this value is critical for snap thresholds' calculation and must remain the same for all items.
