### ISSUE TITLE
strange behavior when using long array for data and firstItem prop

### ISSUE THREAD

**Issue by zeropaper** [archriss/react-native-snap-carousel#395]
### Is this a bug report, a feature request, or a question?

Bug report

### Have you followed the required steps before opening a bug report?

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Almost certain

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

It can be reproduced on both platforms.

### Is the bug reproductible in a production environment (not a debug one)?

Yes.

### Environment

  Environment:
    React: 16.3.1
    Expo SDK: 29.0.0 (RN: 0.55.4)
    react-native-snap-carousel: 3.7.2

  Target Platform:
    Android
    iOS

### Expected Behavior

When passing the a value (usually bigger than 10) in the `firstItem` property, it is expected to display the item at the given index.

### Actual Behavior

The `firstItem` is set to 20:
![image](https://user-images.githubusercontent.com/65971/45607160-b0b81380-ba4a-11e8-8473-7d6a3d0f16a6.png)

after clicking once on the "next" button:
![image](https://user-images.githubusercontent.com/65971/45607183-cf1e0f00-ba4a-11e8-95cc-72e89ec61487.png)

After clicking a few times on the "next" button, the values will eventually match.

### Reproducible Demo

https://snack.expo.io/@mwd/snap-carousel-debug

### Steps to Reproduce

Just open the snack, the number at the top should be the same as the one at the bottom (between the 2 buttons).

### Side note

I tried to build a crutch based on my observations (after some clicks, the values will eventually match)...
It's horrible but you can have a look at it here: https://github.com/MWD-Agentur/snap-carousel-debug/commit/a7ccda6ba4ae25708c99a6d06c49fb36ac411ef5

**Comment by bd-arc** [comment]
@zeropaper Unfortunately, this is a `FlatList` issue.

You can learn more about it in [this comment](https://github.com/archriss/react-native-snap-carousel/issues/363#issuecomment-407791298). I've ran the same test on your example, and it sadly proves that `FlatList` remains full of bugs...
