### ISSUE TITLE
[PROPOSAL] forceCallback/forceSnap

### ISSUE THREAD

**Issue by NichAga** [archriss/react-native-snap-carousel#397]
### Is this a bug report, a feature request, or a question?

Feature request, more or less.

Hi @bd-arc ,
I'm again here to ask you for a feature. In my app, I needed the fireCallback of the snapToItem to always being fired, but it wasn't happening. I moved to the code of this dependecy and I introduced a new parameter: forceCallback

This is my modified snapToItem:
```
snapToItem (index, animated = true, fireCallback = true, forceCallback = false) {
        if (!index || index < 0) {
            index = 0;
        }

        const positionIndex = this._getPositionIndex(index);

        if (!forceCallback && (positionIndex === this._activeItem)) {
            return;
        }

        this._snapToItem(positionIndex, animated, fireCallback, false, true, true);
    }
```

And this is _snapToItem:
```
snapToItem (index, animated = true, fireCallback = true, initial = false, lockScroll = true, forceCallback = false) {
        .............

        if (forceCallback || (index !== this._previousActiveItem)) {
            this._previousActiveItem = index;

            // Placed here to allow overscrolling for edges items
            if (lockScroll && this._canLockScroll()) {
                this._lockScroll();
            }

            if (fireCallback) {
                if (onBeforeSnapToItem) {
                    this._canFireBeforeCallback = true;
                }

                if (onSnapToItem) {
                    this._canFireCallback = true;
                }
            }
        }
       .............
    }
```

Could it be good to introduce in one of your releases?
Thanks,
Nicholas Bertazzon

**Comment by bd-arc** [comment]
Hi @NichAga,

It would be easier for me to properly understand the implications if you could open a PR with your changes.

I'll close the thread and let you open a dedicated issue. Rest assured that it will be reviewed as soon as possible ;-)

**Comment by NichAga** [comment]
Of course, just a question: is another parameter allowed in snapToItem? Does they start to become too many? (index, animated = true, fireCallback = true, initial = false, lockScroll = true, forceCallback = false)

**Comment by bd-arc** [comment]
No worries; go ahead and add it.

Still, I think I'll need to convert this to an option object pretty soon :-)
