### ISSUE TITLE
Unable to access Carousel ref

### ISSUE THREAD

**Issue by EmptyCrown** [archriss/react-native-snap-carousel#401]
### Is this a bug report, a feature request, or a question?

Bug report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - replace the space character between the square brackets (`[]`) by an `x`.)

- [x ] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x ] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x ] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x ] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x ] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

(Write your answer here.)

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

iOS 10

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Environment

React: 16.3.1
React native: Expo SDK 30.0.0
react-native-snap-carousel: 3.7.4

### Expected Behavior

I followed the documentation to access functions like `snapToItem`. I want to be able to snap to a specific index using the `ref` of the Carousel component.

### Actual Behavior

I'm having some issues accessing the ref to call `snapToItem` etc. Namely, `this._carousel` remains undefined throughout the lifecycle of the parent component. Thus, I'm unable to call `this._carousel.snapToItem`. 

### Reproducible Demo

Here's my component:
```
<Carousel
  ref={c => {this._carousel = c}}
  data={...}
  renderItem={({ item, index }) => (
     ...
  )}
  onBeforeSnapToItem={slideIndex => {
     this.setState({ selectedDayIndex: slideIndex - 1 });
  }}
  sliderWidth={Dimensions.get('window').width}
  itemWidth={Dimensions.get('window').width}
/>
```
### Steps to Reproduce

(Write your steps so that anyone can reproduce the issue in the Snack demo you provided.)

1. Define a Carousel component
2. Save the ref to `this._carousel`
3. Access it again

**Comment by bd-arc** [comment]
@EmptyCrown Can you provide a [Snack example](https://snack.expo.io/) that reproduces the issue?

Also, have you tried playing with the provided example? You can see in the code how accessing the carousel's reference is done.

**Comment by EmptyCrown** [comment]
Hi @bd-arc -- I got it to work following the example. The issue from before was that the Carousel was embedded inside one of our own components, and the ref was passing in as a prop. I'm still unsure why that would result in different behavior. For now, we've put the Carousel right into the parent component, and things are working. Thanks!

**Comment by bd-arc** [comment]
@EmptyCrown I can't answer that without looking at some code ;-) Happy to know that you got this sorted!
