### ISSUE TITLE
Infinite scroll (back and forth) possible?

### ISSUE THREAD

**Issue by harrymash2006** [archriss/react-native-snap-carousel#411]
I want to provide the following this. Is this possible with current implementation? Any idea? 
this is related to default carousel style.

Suppose there are 30 pages/views in carousel. Now, when you are on the first page you should be also able to scroll back to left and it should go to 30th page and then 29, 28...etc. Same way when you are on 30th page next page should be #1, then 2, 3, 4...etc

Please let me know if it is possible.

Thanks

**Comment by bd-arc** [comment]
Sure, that's what [the `loop` prop](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#loop) is for.

**Comment by harrymash2006** [comment]
ok but when I enable look it does not show the left element edges when I slide to past slides. This is how it shows the preview when moving to +slides (1,2,3,4...365..etc) and after moving to -slides(like 365, 364, 363..etc). How can I fix it?
![pastslides_before_1](https://user-images.githubusercontent.com/5957516/46872172-0cf73300-ce51-11e8-902c-28999abe4c80.png)
![slides_after_1](https://user-images.githubusercontent.com/5957516/46872173-0cf73300-ce51-11e8-84e7-0d88a0dd693c.png)

**Comment by bd-arc** [comment]
As stated in [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md), you need to provide a Snack example in which the issue can be reproduced for us to be able to help you
