### ISSUE TITLE
Victory-native (SVG) charts not "swipping"

### ISSUE THREAD

**Issue by warlock** [archriss/react-native-snap-carousel#415]
**Version**

"expo": "^30.0.1"
"react": "16.3.1"
"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz"
"react-native-swiper-flatlist": "^1.0.8"
"victory-native": "^30.5.0"

**How to reproduce it**

I have inserted victory-native graphics in Swiper and the swiper-scroll does not work for me. I understand that victory-native uses SVG. I have tested with zIndex of the View Component.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**

**Comment by warlock** [comment]
The solution:
```html
<View pointerEvents="none" >
```
