### ISSUE TITLE
Please don’t publish experimental syntax on npm

### ISSUE THREAD

**Issue by srameshr** [archriss/react-native-snap-carousel#418]
### Is this a bug report, a feature request, or a question?

Yes, trying to use this plugin with react native web is breaking.
https://github.com/material-components/material-components-web-react/issues/107
```
  28 | export default class Carousel extends Component {
  29 | 
> 30 |     static propTypes = {
     |                      ^
  31 |         data: PropTypes.array.isRequired,
  32 |         renderItem: PropTypes.func.isRequired,
  33 |         itemWidth: PropTypes.number, // required for horizontal carousel

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation
```

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - replace the space character between the square brackets (`[]`) by an `x`.)

- [x ] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [ x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x ] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x ] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x ] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

(Write your answer here.)
YES

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Specific to react native web.

### Is the bug reproductible in a production environment (not a debug one)?

React native web

### Environment

  Environment:
    React: 16.0.0-beta.5
    React native: 16.6.0
    react-native-snap-carousel: 3.7.5

  Target Platform:
    react native web 

(Write your answer here.)

### Actual Behavior

(Write what happened. Add screencasts/screenshots!)

### Reproducible Demo

(Paste the link to a [Snack example](https://snack.expo.io/) in which the issue can be reproduced. Please follow [the guidelines](https://stackoverflow.com/help/mcve) for providing a Minimal, Complete, and Verifiable example.)

### Steps to Reproduce

```
28 | export default class Carousel extends Component {
  29 | 
> 30 |     static propTypes = {
     |                      ^
  31 |         data: PropTypes.array.isRequired,
  32 |         renderItem: PropTypes.func.isRequired,
  33 |         itemWidth: PropTypes.number, // required for horizontal carousel

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation
```

(Write your steps so that anyone can reproduce the issue in the Snack demo you provided.)

1. Just npm add it to a cra project.

**Comment by srameshr** [comment]
@bd-arc Could you please transpile the experimental code and update the lib on npm?

**Comment by bd-arc** [comment]
@srameshr Sorry, but we have no plan on making this plugin compatible with `react-native-web`, especially if it means coping with a syntax that we've been more than happy to forget.

Note that your are absolutely free to create a fork, transpile it for your own usage and publish it on `npm` :-)

**Comment by srameshr** [comment]
That would add to more confusion, keeping it in sync with this repo etc.
It would really help if you could fix this.
