### ISSUE TITLE
Adding dots navigation

### ISSUE THREAD

**Issue by yantakus** [archriss/react-native-snap-carousel#42]
Is there a way to add dots navigation:

![pip app designs copy 2017-03-08 13-06-46](https://cloud.githubusercontent.com/assets/2179726/23699442/3314934c-0400-11e7-9236-832c2044d6e1.png)

**Comment by Exilz** [comment]
Hi,
it’s not implemented by default but it should be relatively easy to do thanks to the `onSnapToItem` prop.

**Comment by yantakus** [comment]
@Exilz Yes, exactly. Thanks!
