### ISSUE TITLE
vertical behavior is not working in Android 

### ISSUE THREAD

**Issue by ps0305** [archriss/react-native-snap-carousel#420]
### Is this a bug report, a feature request, or a question?

question

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - replace the space character between the square brackets (`[]`) by an `x`.)

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

followed and made sure

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android oreo

### Is the bug reproductible in a production environment (not a debug one)?

not sure

### Environment
    React native: 0.49.2
    react-native-snap-carousel: 3.3.4

  Target Platform:
    Android (6.0)

### Expected Behavior

On using carousal with vertical as false in behavior the images should change from top to bottom while swiping up and down

### Actual Behavior

on vertical carousal the images should flip,while swiping up and down 
!--
  This step is MANDATORY:

    * It shows that you value and respect the time of the people that are willing to help you; no one wishes to waste his spare time trying to recreate someone else's problem.
    * Issues without reproducible demos have an extremely low priority and will probably be closed without notice.
    * You might figure out the issues yourself as you work on extracting it.
-->

**Comment by bd-arc** [comment]
Hi @ps0305, could you please provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced?

**Comment by bd-arc** [comment]
Also, you are using old versions of both the plugin and React Native. Could you try updating those and see if it works?

**Comment by ps0305** [comment]
@bd-arc, let me try with latest react-native version if won't work i'll share the snippet over Snack.
