### ISSUE TITLE
Properties sliderHeight and itemHeight dont seem to work

### ISSUE THREAD

**Issue by Return-1** [archriss/react-native-snap-carousel#421]
### Is this a bug report, a feature request, or a question?

bug report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - replace the space character between the square brackets (`[]`) by an `x`.)

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

only tried ios

### Is the bug reproductible in a production environment (not a debug one)?

yes

### Environment

Environment:
    React: 16.3.1
    React native: 0.55.4
    react-native-snap-carousel: 3.7.5

  Target Platform:
    iOS (11.2)

### Expected Behavior

I was using the properties:
sliderHeight={number}
itemHeight={number}

i was expecting them to make a difference

### Actual Behavior

It seems like they dont no matter what number input i provide or removing them alltogether. Im certain it isnt an error on my side as im very familiar with RN layouting, for reference, the Carousel is in a Container with flex : 1 and no matter what height properties i provide it with it tries to fill up as much screen as it can, nothing i do affects its height, even tried adding a style property to it to no avail.

### Reproducible Demo

(Paste the link to a [Snack example](https://snack.expo.io/) in which the issue can be reproduced. Please follow [the guidelines](https://stackoverflow.com/help/mcve) for providing a Minimal, Complete, and Verifiable example.)

### Steps to Reproduce

(Write your steps so that anyone can reproduce the issue in the Snack demo you provided.)

1. Use the height properties
2. 
3.

**Comment by bd-arc** [comment]
@Return-1 As stated [in the doc](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#required), those two props are required only for vertical carousels. I might need to add a note explaining that they aren't used at all for horizontal ones — and vice versa.

Make sure to take a look at [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example/src) in order to understand how carousel's height is handled.
