### ISSUE TITLE
Proper parallax image setup based on documentation ( solved, is documentation ok ? )

### ISSUE THREAD

**Issue by Return-1** [archriss/react-native-snap-carousel#422]
### Is this a bug report, a feature request, or a question?

question

### The question

I must be somehow missing a step on the `ParallaxImage` documentation but i dont seem to see what that is. The same example works fine with a plain `Image` component but in the case of `ParallaxImage` no image is rendered.

`parallaxProps` are passed in `renderItem` properly.

If im not missing something let me know and i will file as a bug.

#### The code ( cut down )

```
    _renderItem({ item, index }, parallaxProps) {
        return (
            <View style={{
                height: 150,
            }}>
                <ParallaxImage
                    source={{uri: "any uri"}}
                    style={{ width: "100%", height: "100%" }}
                    parallaxFactor={0.4}
                    {...parallaxProps}
                />
            </View>
        );
    }

    ... in render
     <Carousel
                    layout={"default"}
                    ref={(c) => { this._carousel = c; }}
                    data={this.state.entries}
                    renderItem={this._renderItem}
                    sliderWidth={Dimensions.get("window").width}
                    itemWidth={Dimensions.get("window").width * 0.7}
                    hasParallaxImages={true}
                />
```

### UPDATE

Providing the `dimensions` property makes the image appear but this property is marked as `optional`. Will leave open in case revision to the documentation is required.

**Comment by bd-arc** [comment]
@Return-1 I confirm that prop `dimensions` is optional. Take a look at [the example's source code](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/components/SliderEntry.js#L20-L28) for instance.

Have you tried replacing your prop `style` with `containerStyle`?
