### ISSUE TITLE
problem in renderItem

### ISSUE THREAD

**Issue by codex7** [archriss/react-native-snap-carousel#429]
When I use return in renderItem, an empty slide is displayed
My code is as follows

```
<Carousel
             ref={(c) => { this._carousel = c; }}
             data={object}
             renderItem={({item, index}) => this.render(item, index)}
             sliderWidth={sliderWidth}
             itemWidth={ITEM_WIDTH}
             contentContainerCustomStyle={{alignItems: 'center'}}
             activeSlideAlignment={'start'}
             inactiveSlideScale={1}
             inactiveSlideOpacity={1}
             inverted={true}
/>

render(item, index){
if(index == 1)
{
return;
}
else{
  return(<View><Text>1</Text></View>)
}
}
```

please help

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**

**Comment by codex7** [comment]
expo link :
https://snack.expo.io/HJpyEWmAX

When I use return in renderItem, an empty slide is displayed
Please scroll the number **1**, you will see an empty slide

**Comment by bd-arc** [comment]
@codex7 I don't know what you expect. Of course, if you return nothing, nothing gets rendered...

**Comment by codex7** [comment]
An empty slide should not be displayed. what should I do?
There is no problem with flatlist

```
<FlatList
             data={object}
             renderItem={({item, index}) => this.render(item, index)}
             inverted={true}
/>
```

please help

**Comment by codex7** [comment]
Okay, I'm going to implement a slide to show 2 rows of data depending on the input in each slide, a solution that I thought came up with using the array as below, but it also displays an empty slide.

```
render(item, index){
if(index % 2 == 0)
{
return(<View>global</View>)
}
else{
  global[index] = <View>simple</View>
}
}
```

What is your solution?

**Comment by bd-arc** [comment]
Well, there is no `return` statement in your `else` condition. Therefore nothing gets shown.

It would help to have a clear understanding of what you're after.

**Comment by codex7** [comment]
I do not want to show an empty slide, what's the solution? (It displays an empty slide)

**Comment by bd-arc** [comment]
I mean what is the end result you're after? What does your app look like? What's the end feature?

**Comment by codex7** [comment]
A small sample of my original program

I need you, like the link below:
https://photos5.appleinsider.com/gallery/21614-24967-astorecomposite-top-l.jpg
subject:
new games we love
new appa we love

**Comment by bd-arc** [comment]
Ok, but I still don't see why you need to avoid rendering some slides. Can't you deal with that in the data array directly?

**Comment by codex7** [comment]
When the renderItem runs, the slide is displayed. What is the solution if I intend to have 2 rows of data in each slide? Can you give an example(without empty slide)?

**Comment by codex7** [comment]
There are two problems
First:
Data is loaded from the database (dynamic). 
Second:
5 data may be loaded (odd number)

**Comment by bd-arc** [comment]
1) There is no problem if you store your data in the state and update it accordingly.

2) Handling this is pretty straightforward:
```
_renderItem ({item, index}) {
    const firstRow = item[0] ? (
        <View style={styles.row}>
            <Text>{ item[0] }</Text>
        </View>
    ) : null;
    const secondRow = item[1] ? (
        <View style={styles.row}>
            <Text>{ item[1] }</Text>
        </View>
    ) : null;

    return (
        <View style={styles.rowContainer}>
            { firstRow }
            { secondRow }
        </View>
    );
}
```
