### ISSUE TITLE
remove whitespace at end of horizontal default, active item left

### ISSUE THREAD

**Issue by Djinne** [archriss/react-native-snap-carousel#430]
Hi, 
how do you remove the whitespace at the end of the list when active item is floated left?

I have tried negative/postitive margins, on the containerCustomStyle and contentContainerCustomStyle.

If I reduce the sliderWidth by a ratio some unintended slider effects happen.
Currently: I have added a onbeforesnap to snap to second last item if user scrolls to last item, but not ideal

Only thing I can think left of trying is pushing the last item after render but that doesn't sound right/

**Comment by bd-arc** [comment]
Hi @Djinne,

Unfortunately you can't.

Please read https://github.com/archriss/react-native-snap-carousel/issues/102#issuecomment-342919321 and the follow-up discussion to understand why — TL;DR: `FlatList` issues all the way!

**Comment by Djinne** [comment]
Thank you, guessing firstItem={1} with activeSlideAlignment={"center"} is good enough! :D This plugin is awesome, too bad you guys seem to be fighting with the flatlist on every turn

**Comment by bd-arc** [comment]
Thanks for the kind words :-)

And yes, `FlatList` is the main limiting factor. A few interesting evolutions have been made to the `ScrollView`/`FlatList` components lately, but unfortunately they've basically introduced even more bugs...
