### ISSUE TITLE
How to add left and right arrow to navigate between slides instead of swipe?

### ISSUE THREAD

**Issue by Rajdeepc** [archriss/react-native-snap-carousel#432]

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**

**Comment by Anzormumladze** [comment]
Thanks , you save my day

**Comment by RianTritiYanuar-ICube** [comment]
Thanks a lot, it's worked! I've tried to find the docs that refers to this method but couldn't find it
