### ISSUE TITLE
Removing items from the carousel makes empty space.

### ISSUE THREAD

**Issue by ravindraguptainfogain** [archriss/react-native-snap-carousel#446]
Hello, I am using this component to show items in carousel. I am using useScrollView={true} as the item list may contain any number of items and FlatList seems buggy.

```
<View style={{ flex: 1, justifyContent: 'center', zIndex: 1 }}>
							<Carousel
								ref={c => this._carousel = c}
								data={this.state.ticketList}
								renderItem={this._renderItemWithParallax}
								sliderWidth={sliderWidth}
								itemWidth={itemWidth}
								contentContainerCustomStyle={{ paddingVertical: 50 }}
								firstItem={this.state.selectedTicketIndex}
								inactiveSlideScale={1}
								inactiveSlideOpacity={0.7}
								useScrollView={true}
								removeClippedSubviews={false}
							/>
						</View>
```

I came to a new requirement to remove items from the list and added the below code
```
onTicketApproveDecline(ticketItem, isApproved) {
		if (this._carousel.currentIndex == this.state.ticketList.length - 1) {
			if (this._carousel.currentIndex == 0) {
				// No item left in carousel
				this.props.navigation.pop()
			} else {
				this.state.ticketList.splice(this._carousel.currentIndex, 1)
				this._carousel.snapToPrev()
			}
		} else {

			let temp = this.state.ticketList.slice()
			temp.splice(this._carousel.currentIndex, 1)
			
			this.setState({
				ticketList: temp
			}, () => {
				this._carousel.snapToNext()
			})
		}
	}
```

Removing the last item seems to work perfectly but the else statement to remove the element other than last one leave a blank space at the same place and remove the last item from the carousel, seems like it just narrow the scroll area but does not shift the items to cover the space created after the item has been deleted.

![simulator screen shot - iphone 5s - 2018-12-27 at 16 48 15](https://user-images.githubusercontent.com/33050484/50478472-4a527200-09f7-11e9-9883-41bd741ff1f5.png)

**Comment by dengue8830** [comment]
i fixed with this

```
componentWillUpdate() {
    this.carousel.snapToItem(0);
  }
```
