### ISSUE TITLE
Changing swiping direction?

### ISSUE THREAD

**Issue by pukhalski** [archriss/react-native-snap-carousel#449]
Question: I want to implement a stack-of-cards type of swiper, but I want user to be able to swipe right instead of left, so stack itself would be on the left side. How's it possible?

Thank you.

**Comment by bd-arc** [comment]
Hi @pukhalski,

The good news is: I've already done that!

Take a look at [the source code for the stack effect](https://github.com/archriss/react-native-snap-carousel/blob/master/src/utils/animations.js#L125-L198) and you'll see that the effect has been reverted between iOS and Android — you can preview the difference [here](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md#preview).

One word of caution though: make sure to read about [custom interpolation's caveats](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md#caveats) and to take a look at #262.

**Comment by pukhalski** [comment]
Thank you, @bd-arc. That was quick ;)

**Comment by emersonhsieh** [comment]
Is there a reason why the effect is reversed for iOS and Android? Just curious :)
