### ISSUE TITLE
SnapToItem doesn't work when pointing to index 0

### ISSUE THREAD

**Issue by ppetrick** [archriss/react-native-snap-carousel#450]
### Is this a bug report, a feature request, or a question?

Bug report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - replace the space character between the square brackets (`[]`) by an `x`.)

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

I couldn't find a related React Native issue

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Tested on IOS only

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Environment

    React: 16.5.0
    React native: 0.57
    react-native-snap-carousel: 3.7.5

  Target Platform:
    iOS (10.3)

### Expected Behavior

SnapToItem should always point to the correct index, but doesn't when pointed at index 0.

### Actual Behavior

SnapToItem doesn't work when pointing at index 0 after being called at other indexes first.

### Reproducible Demo

(Paste the link to a [Snack example](https://snack.expo.io/) in which the issue can be reproduced. Please follow [the guidelines](https://stackoverflow.com/help/mcve) for providing a Minimal, Complete, and Verifiable example.)

https://snack.expo.io/@ppetrick/carousel-issues

### Steps to Reproduce

(Write your steps so that anyone can reproduce the issue in the Snack demo you provided.)

1. Tap on the "Goto next item" button
2. The third time, it's clicked, the item changes to index 0, but the carousel doesn't snap to that item

(I'm happy to dig into the code as well. Would love some pointers on where to look.)

**Comment by bd-arc** [comment]
Hi @ppetrick,

Your issue has nothing to do with the carousel.

Here is what you've written in the `componentDidUpdate()` method of `ListCarousel`:
```
const itemIdx = this.getItemIndex();
if (itemIdx) { ... }
```

When `itemIdx` is equal to `0`, your condition will never get called...

**Comment by ppetrick** [comment]
Yikes! My bad.
