### ISSUE TITLE
Adding Navigation

### ISSUE THREAD

**Issue by anoopmm** [archriss/react-native-snap-carousel#451]
I need to navigate to other page while snaping a carousal item.While using 'onSnapToItem' it calls every time for swipe left or right.Is there any other way to do that?

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**
