### ISSUE TITLE
does not clear views from memory 

### ISSUE THREAD

**Issue by mohsinnaqvi110** [archriss/react-native-snap-carousel#453]
**Is this a bug report or a feature request?**
Feature Request (but this is bug as well)

**Have you read the guidelines regarding bug report?**
Yes

**Have you read the documentation in its entirety?**
Yes

**Description**
It load all the child layouts at once, In my application I have a long sliding of images.
So, imagine 100 images and when carousel render all at once which gradually leads to memory error.

Found this prop

> activeSlideOffset 

> From slider's center, minimum slide distance to be scrolled before being set to active.

But I dun think it will work in this case

**Exception**
There should be some prop which limit the render amount of content in carousel and on user scroll it load new and clear old out of memory but not sure if it is possible with this control.

Since I have checked this base is Flatlist and very well handled for swipe gestures so I think it is possible to implement & show only few images those are in viewport rest of all are clear from memory 

thoughts?

**Comment by mohsinnaqvi110** [comment]
Yes, you are right I did read all that, plus the optimization tip you guys mentioned. Its a really good control.

In my scenario it doesn't work
Actually I have a FlatList inside Flatlist using this carousel control.

As mentioned here

> Make sure the carousel isn't a child of a ScrollView (this includes FlatList, VirtualizedList and many plugins). Apparently, it would render all child components, even those currently off-screen.

I can't use this control outside Flatlist. so what would you suggest?

**Comment by bd-arc** [comment]
@mohsinnaqvi110 As you've understood, I have no control over this issue; it is a React Native one.

Aside from [the performance tips](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/TIPS_AND_TRICKS.md#optimizing-performance) that you've already read, the only thing I can think of is leveraging `VirtualizedList`'s [`onEndReach` prop](https://facebook.github.io/react-native/docs/virtualizedlist#onendreached) in order to load items by batch.

**Comment by gamingumar** [comment]
What is the performant way to render with high initial index value?
https://stackoverflow.com/questions/54540375/performant-way-of-rendering-huge-list-with-initial-index-in-react-native

**Comment by tameem92** [comment]
```
Make sure the carousel isn't a child of a ScrollView (this includes FlatList, VirtualizedList, and many plugins). Apparently, it would render all child components, even those currently off-screen.
```
This is extremely limiting in the case of most cases where you would have multiple carousels within a Sectionlist or FlatList. Is there any way around this?
