### ISSUE TITLE
add dynamic content to slides

### ISSUE THREAD

**Issue by roeib** [archriss/react-native-snap-carousel#458]
I don't know what information I get from my server
i want to print all of it

  renderItem = (elem) => (
    <TouchableOpacity >
        {Object.keys(elem.item).map(key=> {
        <Text>{ injury.item[key]} </Text>
        })}
    </TouchableOpacity>
  );

if i console log it i can see it in the console but its don't show on the screen

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**
