### ISSUE TITLE
[Feature Request] Interop with react-native-gesture-handler

### ISSUE THREAD

**Issue by siderakis** [archriss/react-native-snap-carousel#466]
In react-native-snap-carousel the `ScrollView` and `FlatList` implementations are hard coded to the ones provides by "react-native".

Can we add a prop to allow users to provide their own wrapped versions of `ScrollView` and `FlatList`, similar to how `FlatList` allows you to provide a wrapped implementation of `ScrollView` using the `renderScrollComponent` prop.

This would allow users to use the wrapped FlatList and ScrollView provided by `react-native-gesture-handler`.

# Background

`react-native-gesture-handler` allows you to specify a `waitFor` prop on a `ScrollView` that tells the ScrollView to wait for other gesture handlers to become active or not. For example there could be a Slider component within a horizontal scrollview.

**Comment by martinezguillaume** [comment]
Waiting for this !

**Comment by bd-arc** [comment]
If someone wants to jump in and submit a clean PR for that, I'll be more than happy to merge it!

**Comment by martinezguillaume** [comment]
Here we go !
