### ISSUE TITLE
Apply Cutom Css On "onSnapToItem"

### ISSUE THREAD

**Issue by vishalpachpande** [archriss/react-native-snap-carousel#47]
I want to apply custom css "onSnapToItem"  for  this I am  using this.setState({paddingTop: 20})  , I can see this css code when I print "this", but it wont get render, is there anything that I need to do, so that above changes will get reflect on selected item.

**Comment by Exilz** [comment]
Here's a quick example of how you can throw it together. It has nothing to do with the component itself but with how you want to play with React.

```javascript
        const children = [
            { component: View, props: { style: { backgroundColor: 'red' } } },
            { component: View, props: { style: { backgroundColor: 'blue' } } }
        ];
        const coucou = children.map((Child, index) => {
            // meaning you set the active slide in set earlier
            const isActive = this.state.activeSlide === index;
            return <Child.component { ...Child.props} style={[Child.style, styles.myCustomActiveStyle]} />;
        });
        return (
            <Carousel
              ref={'carousel'}
              sliderWidth={sliderWidth}
              itemWidth={itemWidth}
            >
                { coucou }
            </Carousel>
        );
```

You can do this with a lots of different ways. This one is a little bit more complicated but you can set a specific style for each child you pass to the component.

**Comment by vishalpachpande** [comment]
Hey Exilz thanks for you reply , actually I want to highlight active item when I swipe my list and get one item , and this selected item I use to get by using "onSnapToItem" method. and here I am unable to that selected item to apply css.

**Comment by bd-arc** [comment]
@vishalpachpande If you are mapping your slides from an array of data or components, this should be pretty straightforward.

Make sure to update a state variable on `onSnapToItem`:
```
<Carousel
  onSnapToItem={(index) => this.setState({ currentSlideIndex: index })}
  // other props
>
    { this.slides }
</Carousel>
```

And then you can apply a specific style to the current active slide, based on index comparison:
```
get slides () {
    const { entries, currentSlideIndex } = this.state;

    return entries.map((entry, index) => {
        const slideStyle = [
            styles.slide,
            index === currentSlideIndex ? styles.activeSlide : {}
        ];

        return (
            <View
                key={`carousel-entry-${index}`}
                style={slideStyle}
            >
                <Text>{ entry.title }</Text>
            </View>
        );
    });
}
```

Is it what you were after?
