### ISSUE TITLE
Carousel show item view incorrect region.

### ISSUE THREAD

**Issue by jogasinghbajwa** [archriss/react-native-snap-carousel#471]
###Question.

(Write your answer here.)

I'm using your Carousel in my application, which is developing in react native language.
Installation & usage is easy of this carousel.

My carousel open after select an particular item from flat list.
Sometimes it how wrong origin of the view in carousel.

Please look at following screenshots.

![simulator screen shot - iphone xr - 2019-02-06 at 11 18 56](https://user-images.githubusercontent.com/30104394/52322922-0e042f80-2a01-11e9-8ba1-5045a6bf596f.png)
![simulator screen shot - iphone xr - 2019-02-06 at 11 19 01](https://user-images.githubusercontent.com/30104394/52322923-0e042f80-2a01-11e9-9925-00286e4841b4.png)
![simulator screen shot - iphone xr - 2019-02-06 at 11 19 06](https://user-images.githubusercontent.com/30104394/52323186-21fc6100-2a02-11e9-89cd-02a407b82196.png)

Please let me know, if anybody faced this issue.

**Comment by bd-arc** [comment]
Please provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced.

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.
