### ISSUE TITLE
RefreshControl in scrollView inside renderItem should works on iPhoneX device

### ISSUE THREAD

**Issue by dflourusso** [archriss/react-native-snap-carousel#473]
### Is this a bug report, a feature request, or a question?

Bug Report

### Have you followed the required steps before opening a bug report?

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Sure

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

It's an iPhoneX device bug, not simulator

### Is the bug reproductible in a production environment (not a debug one)?

Same bug in production

### Environment

  Environment:
    React: 16.5.0
    React native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
    react-native-snap-carousel: 3.7.5

  Target Platform:
    iOS (12.1.2)

### Expected Behavior

Refresh control in scrollView inside renderItem should works on iPhoneX

### Actual Behavior

I think is a problem with contentContainerStyle.
![refresh](https://user-images.githubusercontent.com/5544901/52342193-d8a91300-29fb-11e9-9e0d-e486f341fe5a.gif)

### Reproducible Demo

[Snack example](https://snack.expo.io/@dflourusso/carroussel-example)

Comment the line 98 to see the problem

### Steps to Reproduce

Just open the snack and everything should works. Comment the line 98 for the snack and it will stop work in the iPhoneX device (not simulator)

**Comment by bd-arc** [comment]
Hi @dflourusso,

Two questions at this point:

1. I assume it doesn't work if you replace `height: this.state.contentContainerHeight` with `flex: 1`, does it?
1. What are you using to handle the safe area view on iPhone X?

**Comment by N1ghtly** [comment]
@dflourusso Did you ever find a solution to this? Currently facing the same problem here.

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.

**Comment by panda6412** [comment]
Same here face the problem, any solution ?

**Comment by panda6412** [comment]
> @dflourusso Did you ever find a solution to this? Currently facing the same problem here.

I turn out to find the solution from ScrollView component, actually ,I did not find the reason cause this bug, so I took some trick on scrollView.

Let scrollView offset y always at `1`.

```
<ScrollView
  ref={ref => { this.scrollView = ref }}
  scrollIndicatorInsets={{ right: 1 }}
  contentOffset={{ x: 0, y: 1 }}
  onScroll={e => {
    const { y: offsetY } = e.nativeEvent.contentOffset
    this.scrollViewY = offsetY
  }}
  onMomentumScrollEnd={() => {
    if (this.scrollViewY === 0) {
      this.scrollView.scrollTo({ y: 1 })
    }
  }}
  refreshControl={
    <RefreshControl
      refreshing={refreshing}
      onRefresh={async () => {
        try {
          this.setState({ refreshing: true })
          await actions.refreshExportProgress()
        } catch (e) {
          console.warn(e)
        } finally {
          this.setState({ refreshing: false })
        }
      }}
    />
  }
>
    ...
</ScrollView>
```

**Comment by milennaj** [comment]
Hi,

Is there a solution for this problem? For iOS refresh doesn't work or with workaround from panda6412 it works only once if we add  scrollEventThrottle={0}. Without it on second attempt error is fired:

You specified `onScroll` on a <ScrollView> but not `scrollEventThrottle`. You will only receive one event. Using `16` you get all the events but be aware that it may cause frame drops, use a bigger number if you don't need as much precision.
