### ISSUE TITLE
remove spacing in carousel

### ISSUE THREAD

**Issue by arnoldc** [archriss/react-native-snap-carousel#475]
Hi guys

is there a way to remove the spacing in the carousel

for example this one, I would like to remove the spacing between the cards, 
would like something that sits next to each other , any feedback is appreciated 

![carousel](https://camo.githubusercontent.com/7590ec7e6b705a6e8e381397247d576c6db72147/68747470733a2f2f692e696d6775722e636f6d2f653157625a63752e676966)

try already looking in the docs, seems that is not there an option

**Comment by bd-arc** [comment]
Please take a look at #187.

**Comment by arnoldc** [comment]
thanks already figured it out.

applied some of the properties correctly like, seems good fine now
- inactiveSlideScale={1}
- sliderWidth={}
- itemWidth={}
