### ISSUE TITLE
Wrong position when rendering large list

### ISSUE THREAD

**Issue by dnish** [archriss/react-native-snap-carousel#479]
I'm having an issue when rendering a large list and setting the <code>firstItem</code> to an item within the list. When I render the carousel, it suddenly looks like this:

![img_2d08fee859c1-1](https://user-images.githubusercontent.com/7636313/52733718-b139e380-2fc3-11e9-9e9b-e8a237938c61.jpeg)

This is how the carousel looks on a small list:

![img_c05a8c392d1d-1](https://user-images.githubusercontent.com/7636313/52733761-c878d100-2fc3-11e9-98f5-d032f3facccb.jpeg)

This is how I init the component:

```
   <Carousel
                    ref="covers"
                    data={this.getUserFiles()}
                    renderItem={this.renderCover}
                    sliderWidth={viewportWidth}
                    itemWidth={viewportWidth * 0.8}
                    inactiveSlideScale={0.9}
                    inactiveSlideOpacity={0.6}
                    snapOnAndroid={true}
                    onSnapToItem={this.onSnap}
                    firstItem={PlayerStore.playlist.currentIndex}
                    layoutCardOffset={18}
                />


const styles = StyleSheet.create({

    covers: {
        height: viewportWidth * 0.8,
    },
    cover: {
        width: viewportWidth * 0.8,
        height: viewportWidth * 0.8
    },

});
```

If I set <code> useScrollView = true</code> it is working fine again, but I want to use the FlatList component due to performance reasons. Any idea how I can fix the wrong position?

Tested on iPhone XS.

**Comment by bd-arc** [comment]
This is a well-known and unfortunate `FlatList` bug.

See #363 for more info. #250 seems like the only way to get rid of it...
