### ISSUE TITLE
Error when using RN 0.42.3

### ISSUE THREAD

**Issue by yaronlevi** [archriss/react-native-snap-carousel#48]
I've created a barebones react-native init@0.42.3 project and copied the carousel:

```
<View style={styles.container}>
        <Carousel ref={'carousel'} sliderWidth={200} itemWidth={100}>
          <Text>aaa</Text>
        </Carousel>
      </View>
```

And getting this error:
![screenshot_20170322-141944](https://cloud.githubusercontent.com/assets/5398977/24197569/cc109c84-0f0a-11e7-9b6c-3e5f248017ec.png)

**Comment by bd-arc** [comment]
@yaronlevi This error is triggered when the carousel only has one children. I thought I had already pushed a fix, but I apparently forgot. I'll do it shortly.

In the meantime, can you confirm that with two or more children the error is gone?

**Comment by yaronlevi** [comment]
Ok, I've tried putting two child Image elemnts, and the error is gone, but now I only see the first image. When I swipe to second one, I see just white background. As if the image was not loaded.

I've created a repo to reproduce the bug:

https://github.com/yaronlevi/carousel

**Comment by bd-arc** [comment]
@yaronlevi I've just downloaded and built your project, but I didn't face any issue. You can see the result with [this gif](http://www.giphy.com/gifs/xUPGcmrfDMCKMsDFXa).

You might be facing #38. Can you try on an emulator, on another device, and/or with another Android version?

**Comment by yaronlevi** [comment]
Mmm very strange
My device is nexus 5
lollipop
how can this be related to the device...?

**Comment by bd-arc** [comment]
@yaronlevi Well, this kind of issues has only been experimented on Google devices; this might be linked to React Native's `ScrollView` implementation.

Unfortunately, we haven't been able to reproduce the issues so far (it works properly on every one of our Android devices, including a LG G3). This makes them pretty complicated to debug.

We're working on implementing a custom [PanResponder](https://facebook.github.io/react-native/docs/panresponder.html) that may resolve the issue, but it's not going to be released in the near future.

**Comment by bd-arc** [comment]
Follow-up discussion about the Android issue will take place in #38
