### ISSUE TITLE
Module `react-native-snap-carousel` does not exist in the Haste module map

### ISSUE THREAD

**Issue by Buddikazz** [archriss/react-native-snap-carousel#484]

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**

**Comment by samscarsella** [comment]
It's hard to know without a code sample, but this is very often a bundler/caching issue.

You can try:
- clearing Watchman: `watchman watch-del-all`,
- deleting your node_modules: `rm -rf node_modules/`,
- clearing your Metro bundler cache: `rm -rf /tmp/metro-bundler-cache-*`,
- clearing RN packager: `rm -rf /tmp/haste-map-react-native-packager-*`
then re-`npm`/`yarn` install your packages and build again.

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.
