### ISSUE TITLE
Extra height is added below Carousel.

### ISSUE THREAD

**Issue by spyshower** [archriss/react-native-snap-carousel#489]
### Is this a bug report, a feature request, or a question?

Question.

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both platforms.

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Environment

    Expo: 32 (latest)
    React: 16.5
    React native: 0.58
    react-native-snap-carousel: 3.7.5 (latest)

  Target Platform:
    Android (6.0)
    iOS (10.3)

### Expected Behavior

I use a vertical Flatlist to show some users. Each list item has a Carousel component. The images in it should be at the appropriate height, like this:

<img width="330" alt="screenshot 2019-03-05 at 01 34 06" src="https://user-images.githubusercontent.com/7046283/53770173-d648b480-3ee6-11e9-83d0-174edc0a20c0.png">

### Actual Behavior

Instead, extra height (from padding/margin maybe?) are added:

<img width="390" alt="screenshot 2019-03-05 at 01 28 46" src="https://user-images.githubusercontent.com/7046283/53770162-d21c9700-3ee6-11e9-8ef2-8ebf96cc57ed.png">

Notice that the below user's photo is visible, which clearly shouldn't be, giving me the impression that the images are placed in an absolute way or something (not sure if this matter)

I thought this has something to with the Pagination component (which I don't use) but then again extra height is added on top of it, so it should be a problem with the Carousel itself.

My code:

```
<Carousel
              ref={(c) => { this._carousel = c; }}
              data={this.props.item.images}
              renderItem={this._renderItem}
              inactiveSlideScale={1}
              inactiveSlideOpacity={1}
              layoutCardOffset={0}
              callbackOffsetMargin={6} // default is 5
              sliderWidth={windowWidth*0.9}
              // sliderHeight={windowWidth*0.9}
              itemWidth={windowWidth*0.9}
              // itemHeight={windowWidth*0.9}
              showsHorizontalScrollIndicator={false}
              // style={{ width: windowWidth*0.9,  borderRadius: 10, overflow: 'hidden'}}
              onBeforeSnapToItem={(index) => {
                console.log('got called')
              }}
            />
```

```
_renderItem ({item, index}) {
      return (
        <Image source={{ uri: "http://res.cloudinary.com/blabla/image/upload/" + item }} style={{ width: windowWidth*0.9, height: windowWidth*0.9 }} />
      );
    }
```

PS: Let me know if a Snack is needed here, although there is pretty nothing other relevant to show I think.

**Comment by KaneNguyen** [comment]
same issue :( can't set height for carousel

**Comment by andriinegustorov** [comment]
the same problem =(

**Comment by bd-arc** [comment]
Hi @spyshower,

I haven't used vertical carousels in a while so yes, it would really help if you could provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced :-)

**Comment by bd-arc** [comment]
@spyshower I'd still appreciate a Snack though, because I never had this kind of issue with the carousel.

**Comment by spyshower** [comment]
https://snack.expo.io/ByBzfMnIV

Try playing with a combination of commenting line 39 and 54-56. I don't even get this behavior, and while it's not 100% identical with my local build, I can say it's not exactly predictable :P

**Comment by ryanostrom** [comment]
The issue is a result of implementation of the <Pagination /> element. This element defines a style for `paddingVertical: 30`. This style can be overridden by the received prop `containerStyle`. So to solve:

```
<Pagination
  containerStyle={{paddingVertical: 0}}
/>
```

**Comment by gi** [comment]
@spyshower Try setting the `Carousel` prop `containerCustomStyle.flexGrow` to `0`:
```javascript
<Carousel
  {/* ... */}
   containerCustomStyle={{
    flexGrow: 0,
  }}
  {/* ... */}
/>
```
I had a similar issue when rendering a `Pagination` component below the carousel, where there was lots of excess space between the two components.

**Comment by bd-arc** [comment]
Thank you @spyshower, @ryanostrom and @gi for your valuable contributions. The issue can now be closed.

As a side note, the `Carousel` is basically a `ScrollView` which has a built-in style that includes `{ flexGrow: 1 }`. There's a note about it [in the doc](https://github.com/archriss/react-native-snap-carousel/blob/4d2a955add2f4abfc57fd88b1b50a56cbeabfc39/doc/TIPS_AND_TRICKS.md#carousels-stretched-height) ;-)
