### ISSUE TITLE
Question - Change the animation behavior

### ISSUE THREAD

**Issue by joakimalbert** [archriss/react-native-snap-carousel#490]
How do I change the animation behaviour? I don't want the items that are coming in our out of screen to be resized during but instead keep the same size.

**Comment by bd-arc** [comment]
The question has been answered numerous time. Have you done your due diligence?

You'll find your answer in [the props documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#style-and-animation).

**Comment by joakimalbert** [comment]
Yes, I have read that part again and again and I still don't understand how to change it from coming from behind to being the same size as the items.

**Comment by bd-arc** [comment]
`inactiveSlideScale={1}`
