### ISSUE TITLE
Example ?

### ISSUE THREAD

**Issue by jbrodriguez** [archriss/react-native-snap-carousel#5]
Hi, the component looks interesting.

Any example to better show how widths should be calculated ?

**Comment by bd-arc** [comment]
@jbrodriguez Hi there. We will make sure to add an example as soon as we find the time to do so. Unfortunately, this might take a couple of weeks.
Is there any way to help you get a better understanding in the meantime? Maybe with an example of your own for which you need some insight?

**Comment by imjameshall** [comment]
Yeah its really unfortunate theres really no hope how to get it started . This seems like such a great component but I can't even get anything to show on the scroll.

**Comment by bd-arc** [comment]
@imjameshall We totally understand you. Ok, you got us motivated; you'll have an example by the end of the week :)

**Comment by cbilgili** [comment]
+1

**Comment by bd-arc** [comment]
Ok guys, as promised you can now play with the following [example](https://github.com/archriss/react-native-snap-carousel/tree/master/example). Hope this will help you get started!

![react-native-snap-carousel](http://i.imgur.com/FxMg5md.gif)
