### ISSUE TITLE
currentIndex how to work with it ?

### ISSUE THREAD

**Issue by shrinandhini2801** [archriss/react-native-snap-carousel#50]
I need to get which item is showing or brought to front now . Is it possible through current index? There is no sample provided. Can you help on it ?

**Comment by bd-arc** [comment]
@shrinandhini2801 You need to keep a reference to your carousel's instance like this :
```
<Carousel
  ref={(carousel) => { this._carousel = carousel; }}
  // other props
/>
```

Then, whenever needed, you can call the following:
```
if (this._carousel) {
    alert(this._carousel.currentIndex);
}
```

If you need to update your state every time a change of slide occurs, make sure to use the `onSnapToItem` prop instead.
