### ISSUE TITLE
How does Android turn pages like this?

### ISSUE THREAD

**Issue by SemperChen** [archriss/react-native-snap-carousel#500]
![68747470733a2f2f692e696d6775722e636f6d2f633770553472542e676966](https://user-images.githubusercontent.com/12069583/55679275-4fe71e80-593b-11e9-96d7-64fe87b6cc0a.gif)

**Comment by bd-arc** [comment]
Please read [the dedicated doc](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md).
