### ISSUE TITLE
[Feature request] slide vertical AND horizontal both

### ISSUE THREAD

**Issue by thinking0** [archriss/react-native-snap-carousel#502]
vertical or horizontal slide are fine current version.
can i set up sliding vertical and horizontal both.

when user slide down the screen than whole items are came down.
otherwise when user slide left the screen than whole items are gone to left.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.
