### ISSUE TITLE
Problem in change slide while previous swipe has setState, and finally slider return to previous slide.

### ISSUE THREAD

**Issue by miladbahramii** [archriss/react-native-snap-carousel#503]
I have a slider for select transport type(like Uber).
when I try to swipe next slide, while the previous slide is still changing state(setState), slider return to the previous slide.
if I wait to change state and then try to swipe the next slide, it will be work.
this problem only happened in Android.
![20190409_182934_1_1](https://user-images.githubusercontent.com/32452626/55806828-49e96d00-5af6-11e9-9af0-59c66ac2be33.gif)

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.
