### ISSUE TITLE
Add standard flat layout

### ISSUE THREAD

**Issue by Xerus2000** [archriss/react-native-snap-carousel#504]
This is a Feature Request.

When using the carousel, I noticed that there is no simple flat animation, so that, when scrolling, the items only move horizontally without being scaled or other fancy stuff.
I know that I can probably create this by myself, but it sounds like a trivial yet pretty common use-case, that should imo be supported out of the box.

**Comment by richeterre** [comment]
You can simply set `inactiveSlideScale={1}` to make items move horizontally.

**Comment by Xerus2000** [comment]
Thanks!
