### ISSUE TITLE
CellRenderComponent

### ISSUE THREAD

**Issue by MokumJ** [archriss/react-native-snap-carousel#505]
Hi I am facing some issues with clipped views on android.

On iOs everything works fine see screenshot
<img width="343" alt="Schermafbeelding 2019-04-12 om 12 06 06" src="https://user-images.githubusercontent.com/33216498/56030209-957d6000-5d1c-11e9-88e4-68a27ce9f229.png">

**The header with opacity from the next slide is not shown on android.**

Therefor I am trying to incorporate the following package within the flatlist of your package
https://github.com/entria/react-native-view-overflow

as the docs form the overflow package show we can use the ViewOverflow like this:
`<FlatList
  data={this.state.data}
  keyExtractor={item => item.id}
  CellRendererComponent={ViewOverflow}
  renderItem={({ item, index }) => (
      <ViewOverflow style={styles.item}>
      // item....
      </ViewOverflow>
   )}
/>`

I am trying to pass the CellRenderComponent in the carousel like the following:

`<Carousel
                    loop
                    ref={c => { this._carousel = c; }}
                    style={styles.pager}
                    data={subscriptionList}
                    contentContainerCustomStyle={{ zIndex: 1, elevation: 1}}
                    sliderWidth={Dimensions.get('window').width}
                    itemWidth={Dimensions.get('window').width}
                    inactiveSlideScale={1}
                    inactiveSlideOpacity={3}
                    removeClippedSubviews={false}
                    onScroll={() => { this.onScrolling(); }}
                    CellRenderComponent={ViewOverflow}
                `

But in seems not to get passed: 
<img width="552" alt="Schermafbeelding 2019-04-12 om 12 11 01" src="https://user-images.githubusercontent.com/33216498/56030438-218f8780-5d1d-11e9-8c91-f0346f9bb7d7.png">

the View from the CellRenderer is clipping the header.
Am I doing this right? Is it possible to pass the CellRenderComponent like this? Or does anybody else sees a proper workaround?

Thanks in advance.

**Comment by MokumJ** [comment]
Haha My god: typo: it is CellRendererComponent instead of CellRenderComponent:

For anybody else looking for a way to work around clipping I don't remove the issue.

**Comment by pixelize** [comment]
@MokumJ can you provide your solution please ? Cannot make it work :(
