### ISSUE TITLE
Query related to elastic animation while swiping

### ISSUE THREAD

**Issue by saikiranoptisol** [archriss/react-native-snap-carousel#514]
Hi, while swiping left/right how to get elastic animation in react-native. i was looking something like [this](https://github.com/lkzhao/ElasticTransition) animation for my onbording. can you please help me i was trying from 3 days but no luck in it.

**Comment by bd-arc** [comment]
There's absolutely no way of doing that with the plugin at this time.

**Comment by saikiranoptisol** [comment]
@bd-arc  okay thank you. But can you please give me any suggestion regarding this animation because i have only 4 screens in onbording and i need to animate like that. I'm new to react native and looking for this kind of animation from the past 5 days

**Comment by bd-arc** [comment]
@saikiranoptisol [Codrops](https://tympanus.net/codrops/2014/12/15/elastic-svg-elements/) has some great transitions example. Browse the website to find more of them.

They are JS and SVG based, so maybe you can figure out something.
