### ISSUE TITLE
滚动到最后一张时图片会闪一下，有人遇到过吗

### ISSUE THREAD

**Issue by webzhangle** [archriss/react-native-snap-carousel#515]
### Is this a bug report, a feature request, or a question?

(Write your answer here.)

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - replace the space character between the square brackets (`[]`) by an `x`.)

- [ ] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [ ] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [ ] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [ ] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [ ] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

(Write your answer here.)

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

(Write your answer here and specify the iOS/Android versions on which you've been able to reproduce the issue.)

### Is the bug reproductible in a production environment (not a debug one)?

(Write your answer here.)

### Environment

(Write your answer here.)

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screencasts/screenshots!)

### Reproducible Demo

(Paste the link to a [Snack example](https://snack.expo.io/) in which the issue can be reproduced. Please follow [the guidelines](https://stackoverflow.com/help/mcve) for providing a Minimal, Complete, and Verifiable example.)

### Steps to Reproduce

(Write your steps so that anyone can reproduce the issue in the Snack demo you provided.)

1.
2.
3.

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**

**Comment by webzhangle** [comment]
您好，这个问题已经解决，但是在有的华为的手机里面他不会一直像一个方向滚动，当滚动到最后一张的时候突然快速的像左滚动到第一张，在向右滚动。除此之外，ios打包后，当页面上进行进入，退出等操作的时候轮播图的图片有时候不显示，用手滑动一下又显示了，这些问题您遇到过吗

**Comment by neohuiji** [comment]
@webzhangle  请问下你是怎么解决这个问题的

**Comment by tanjiaweiGitHub** [comment]
我在ios上遇到了同样的问题，请问是如何解决的？

**Comment by coldrainc** [comment]
你好这个怎么解决的

**Comment by tanjwGit** [comment]
> 你好这个怎么解决的

https://github.com/tanjwGit/react-native-carousel。
