### ISSUE TITLE
not compatible with RN 0.37

### ISSUE THREAD

**Issue by cinder92** [archriss/react-native-snap-carousel#52]
Hello i just want to install this plugin but i receive this error...

![captura de pantalla 2017-03-27 a la s 00 20 25](https://cloud.githubusercontent.com/assets/4725556/24343367/4a987f92-1283-11e7-9725-0d5a7bcf03b1.png)

how can i fix this?

**Comment by bd-arc** [comment]
@cinder92 Hi! This error shouldn't necessarily prevent you from using the plugin. This just means that it's looking for a version of React that is, at least, 15.4.2.

However, RN 0.37 uses version 15.3.1 and version 15.4.0 introduces [some specific changes](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html). You should try the plugin anyway and see if you run into any issue.

**Comment by cinder92** [comment]
@bd-arc  ok cool, thanks!
