### ISSUE TITLE
ComponentWillReceiveProps deprecated

### ISSUE THREAD

**Issue by subhechhu** [archriss/react-native-snap-carousel#530]
![WhatsApp Image 2019-06-04 at 11 34 21 AM](https://user-images.githubusercontent.com/13517085/58855177-07d74480-86bd-11e9-907f-adedbe284182.jpeg)

I have been experiencing this warning.
I am currently using react-native: 0.59.6
The current react-native-snap-carousel is 3.8.0

Can you help me out to deal with this one please?

**Comment by Tristan1075** [comment]
You can use componentDidUpdate and compare actual props with prevProps instead of nextProps :)

**Comment by albertogasparin** [comment]
The deprecation warning is not fired from consumers code but from the `Carousel` component itself. Indeed internally it has `componentWillReceiveProps` defined

**Comment by BSoD38** [comment]
The Pagination component also has this issue. The package does need an update to replace componentWillReceiveProps.

**Comment by srhtylmz19** [comment]
any update ?

**Comment by dpyeates** [comment]
+1

**Comment by bd-arc** [comment]
Hi guys,

@kiarashws was kind enough to submit a PR for that (see #568).

Now I need you to try it in order to make sure that everything is working properly. Once I get enough positive feedback, this will get merged :-)

**Comment by bd-arc** [comment]
Available in version `3.8.1`.
