### ISSUE TITLE
Change default pagination dot spacing

### ISSUE THREAD

**Issue by nguyenhoanglam** [archriss/react-native-snap-carousel#534]
How can I change the pagation dots spacing ?

**Comment by l0h1t** [comment]
It's mentioned in the pagination usage section:
https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PAGINATION.md#note-on-dots-colors

Change the **marginHorizantal** field in the **dotStyle** from 8 to desired value

**Comment by nguyenhoanglam** [comment]
@l0h1t still not working.

**Comment by voisinhugo** [comment]
I think the marginHorizontal is not on the `dotStyle`, but on the `dotContainerStyle` prop of Pagination. So you can give a style with an given value of `marginHorizontal` to overwrite the default value

**Comment by nguyenhoanglam** [comment]
@voisinhugo your suggestion works correctly!

**Comment by Foskas** [comment]
Hi
This is not working for me, the space is always the same between the dots. Any ideas ?
@nguyenhoanglam @voisinhugo

**Comment by shekharskamble** [comment]
Can confirm its not working...

**Comment by NielXu** [comment]
Set the spacing betwene dots:
```javascript
dotContainerStyle={{ marginHorizontal: 5 }}
```
