### ISSUE TITLE
[Question] Slide Alignment

### ISSUE THREAD

**Issue by pixelize** [archriss/react-native-snap-carousel#536]
### Is this a bug report, a feature request, or a question?

Feature request/Question

### Have you followed the required steps before opening a bug report?

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Nope

### Environment

  Environment:
    React: 16.8.6
    React native: 0.59.8
    react-native-snap-carousel: 3.8.0

  Target Platform:
    Android (6.0)
    iOS (100)

### Actual Behavior

My carousel is not infinite. I would like the first item to be snapped on the left and the last item snap to the right. In between the active slide should be centered. Is it possible to achieve this behavior please ?

![Group](https://user-images.githubusercontent.com/2931627/59426968-d277d880-8dd9-11e9-8731-f32b530adf7c.png)

**Comment by pixelize** [comment]
@bd-arc any hint on this please ? :) thanks in advance

**Comment by bd-arc** [comment]
Hi @pixelize,

Unfortunately, this is not possible at the moment. I've previously tried implementing it by leveraging `ScrollView`'s `snapToAlignment` prop but this one was so buggy that I had to give up.

You'll find a lot of insights about this in #102. Some users have been ok with the workaround described at the end of the thread — but note that it will probably mess with the callbacks.

There's hope however!  I've been thinking about a new implementation for a few months, but still haven't had time to really work on it...

**Comment by pixelize** [comment]
@bd-arc awesome, thanks for the clarification @bd-arc :)

**Comment by aldimirprincipal** [comment]
As of 06/04/2020, has this feature been implemented? Thanks for this awesome package tho <3

**Comment by bd-arc** [comment]
@aldimirprincipal The timing is spot on!

I think you're going [to really like this](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/VERSION_4.md), and particularly the `useExperimentalSnap` feature ;-)

**Comment by aldimirprincipal** [comment]
@bd-arc I've just made a workaround for this! x)
If someone wants to know how I just added some margin here:
`sliderContentContainer: {
        marginLeft: "5%",
        paddingVertical: 10 // for custom animation
  },
`
