### ISSUE TITLE
issue related to react-native-render-html

### ISSUE THREAD

**Issue by saikiranoptisol** [archriss/react-native-snap-carousel#555]
HI @bd-arc  i know i should not post this issue here. but i can see your name in the author list of https://github.com/archriss/react-native-render-html so please check this [issue](https://github.com/archriss/react-native-render-html/issues/274)    i have an immediate release and facing issue with the component now

**Comment by bd-arc** [comment]
Try tagging @Exilz in your thread since he's the one that created `react-native-render-html`.

**Comment by saikiranoptisol** [comment]
@bd-arc thanks

**Comment by saikiranoptisol** [comment]
@bd-arc  can you please check with him to reply for that issue. i got struck still in that and i need to fix that as soon as i can
