### ISSUE TITLE
zoom feature 

### ISSUE THREAD

**Issue by chris-topher19** [archriss/react-native-snap-carousel#558]
Does the library has zoom feature?

**Comment by bd-arc** [comment]
@chris-topher19 No, but you can refer to #264 to discover how others have implemented it on top of the carousel — source code included.

**Comment by chris-topher19** [comment]
@bd-arc tried the suggestions mentioned in the #264 , but faced the issue while scrolling when put the zoom feature on top of it. It sometimes gets stuck while scrolling. Any help will be appreciated, 
What I tried was using react-native-image-zoom over this component. I am facing this issue in both android and iOS.

Also i have tried using react-native-gallery-image, which provides both zoom and swipe feature, but it is not infinitely scrolling. Tried a view over it to make it scroll infinitely does not make it smooth and sometimes making it stuck.

**Comment by bd-arc** [comment]
Hi @chris-topher19,

Unfortunately I've never implemented the kind of feature you're after. Your best bet might be to leave a message in #264...

**Comment by sirajalam049** [comment]
Can we expect this feature in the future? As this is a fundamental requirement, it is needed in most cases.

**Comment by andresliu-mks** [comment]
`react-native-pinchable` is probably what everyone is looking for here
