### ISSUE TITLE
Reduce height pagination

### ISSUE THREAD

**Issue by Dr1992** [archriss/react-native-snap-carousel#577]
How can I reduce height of pagination ?
Because when I put style and change the height attribute the dots disappear.

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes, I am.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?
Both

(Write your answer here and specify the iOS/Android versions on which you've been able to reproduce the issue.)

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Environment

react-native-cli: 2.0.1
react-native: 0.59.5
react-native-snap-carousel: "^3.8.0",

**Comment by bd-arc** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) completely. **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced, as well as a complete description of everything you've tried, we won't be able to help you and the thread will be closed.**

**Comment by IvanKolechkin** [comment]
{ paddingVertical: 30 }
Here is a possible solution
[Here](https://github.com/archriss/react-native-snap-carousel/issues/191)

**Comment by rwest88** [comment]
This solution needs to be heard across the globe. Sigh.

**Comment by amit13091992** [comment]
> { paddingVertical: 0 }
> [Here](https://github.com/archriss/react-native-snap-carousel/issues/191) is a possible solution

Thanks worked for me. +1

**Comment by MudassirAziz** [comment]
{ paddingVertical: 0 }
Here is a possible solution
@IvanKolechkin worked like a #charm

**Comment by pepasibble** [comment]
Just to spell this out completely, that's:

```typescript
<Pagination containerStyle={{ paddingVertical: 0 }} />
```
