### ISSUE TITLE
Remove the shadow/elevation of slide

### ISSUE THREAD

**Issue by RenanNeitzel** [archriss/react-native-snap-carousel#578]
How can I remove the shadow/elevation default of the slide ?

I tryed subscribe the style with 'slideStyle' and all other prop style and animation. Both active and inactive, I don't want the slide to have a shadow/elevation. Only a border.

My carousel, it is config:

        <SlideCarousel
          pagination
          data={messages}
          renderItem={renderItem}
          sliderWidth={itemWidth}
          itemWidth={itemWidth}
          inactiveSlideScale={0.7}
          slideStyle={style.slide}
          contentContainerCustomStyle={style.containerSlide}
        />

![Captura de Tela 2019-09-23 às 19 45 59](https://user-images.githubusercontent.com/41584304/65468564-d97f9f80-de3a-11e9-8ff8-07ffa3558bac.png)

Thanks for help ! =)

**Comment by bd-arc** [comment]
Can you please provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced?

**Comment by RenanNeitzel** [comment]
Even small, the image above shows that there is a bottom shadow.
Not a problem, but a need to remove shadow / elevation as requested by the design area.
In the doc, there is no style prop where we can best style the container for each item, whether it is active or inactive.

**Comment by RenanNeitzel** [comment]
I'm sorry. The shadow/elevation it was in the component built for rendering within the slide.
I'm closing this issue.
