### ISSUE TITLE
Default layout item offset

### ISSUE THREAD

**Issue by JakeHadley** [archriss/react-native-snap-carousel#579]
### Is this a bug report, a feature request, or a question?

Question

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using 3.8.1 (https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

### Is the bug reproductible in a production environment (not a debug one)?

Again, not really a bug, just a question.

### Environment

Both

### Expected Behavior

I'm wondering if there is a way to shrink the space between items. I have `loop` set to true, so you can see the item on the left. But I want to be able to see a sliver on the right. I saw in the docs that this is possible with stack and tinder layouts, but I didn't see anything with default. Is there something simple I'm missing? I've also tried shrinking the itemWidth to 50% of the screen with the same result.

### Actual Behavior

![Screenshot_20190924-224513](https://user-images.githubusercontent.com/35585841/65570207-8cc0c500-df1d-11e9-8625-1da069562e05.jpg)

### Reproducible Demo

Not necessary

### Steps to Reproduce

(Write your steps so that anyone can reproduce the issue in the Snack demo you provided.)

1. Basic carousel in a view
2. Profit??
3. Again, this is a pretty simple question

**Comment by bd-arc** [comment]
Hi @JakeHadley,

I'm not sure I've properly understood your question, but note that items' spacing has to do with two things:

- the value of prop `inactiveSlideScale` (the closer to `1` you are, the smaller the spacing is going to be)
- any margin or padding that you add to items' styles.

**Comment by fedu44** [comment]
Hi @JakeHadley, for deleting the space of the dots, use the property {paddingHorizontal:0} in the dotContainer. 
![image](https://user-images.githubusercontent.com/37313502/66045514-4a3d5080-e4fa-11e9-8b48-5058f2d874b3.png)
For the blue part try the same, some paddingBottom -20 or -30. And about the horizontal margin you can use same width   
![image](https://user-images.githubusercontent.com/37313502/66045647-896ba180-e4fa-11e9-8ad7-a2ba11b7bdc5.png)
Hope to help you.
