### ISSUE TITLE
ParallaxImage can't load the image

### ISSUE THREAD

**Issue by LostLord** [archriss/react-native-snap-carousel#582]
```react
<ParallaxImage
  source={require('../../../assets/test/courseTest.png')}
  containerStyle={styles.imageContainer}
  style={styles.image}
  parallaxFactor={0.4}
/>
const styles = StyleSheet.create({
  imageContainer: {
    flex: 1,
    marginBottom: Platform.select({ ios: 0, android: 1 }),
    backgroundColor: 'white',
    borderRadius: 8
  },
  image: {
    resizeMode: 'cover'
  }
})
```

I use the `ParallaxImage` component to load the image but the image can't be loaded normally and there is nothing but the spinner on my screen.

```react
<Image
  source={require('../../../assets/test/courseTest.png')}
/>
```

However, if I use the `Image` component, the image can be loaded normally.

So what's the cause of this issue?

**Comment by LostLord** [comment]
This problem has been solved. Because the `ParalaxImage` component should be the item of the  `Carousel` component, the image can be loaded normally.

**Comment by bd-arc** [comment]
@LostLord Indeed, the `ParallaxImage` component hasn't been created with a standalone usage in mind since you'll always need to link it to another component's scroll position anyway.
