### ISSUE TITLE
Is it possible to make the snap animation more 'snappy'?

### ISSUE THREAD

**Issue by Alenius** [archriss/react-native-snap-carousel#589]
Hello! This is a question / feature request

I have read the docs a bunch of times, and what I want probably can be solved through Custom interpolation, but is it possible increase the speed of the snapping itself through the existing props? From my understanding this is not possible.

Is it possible to add a prop to increase the translation speed? 

Thanks!

**Comment by bd-arc** [comment]
Hi @Alenius,

Unfortunately the Facebook team has never exposed anything allowing us to control the scroll animation's speed, despite everyone asking for it since 2017 (see #203).

Sorry, there's no solution that I'm aware of at this point.

**Comment by Alenius** [comment]
Okey, sorry for missing that information! Thanks for the quick reply.
