### ISSUE TITLE
Shadow in renderItem component not working

### ISSUE THREAD

**Issue by dev-andremonteiro** [archriss/react-native-snap-carousel#592]
I've been experiencing a visual bug on Android and I found only some old issues that weren't even remotely just like this one. Basically, it's a bug with shadow/elevation on the Component inside the slider, if you have a child component inside the render function of the slider ( a Card component for example ) you can't see the shadow in that child component. 

Snack: https://snack.expo.io/@zonder/carousel-snap-shadow-bug

iOS: Works just fine
![Screenshot from 2019-10-07 19-06-50](https://user-images.githubusercontent.com/19479358/66355557-b6261b80-e935-11e9-9306-c4388de3515f.png)

Android: Bug
![Screenshot from 2019-10-07 19-08-02](https://user-images.githubusercontent.com/19479358/66355590-cfc76300-e935-11e9-9898-8bdd7066a502.png)

**Comment by bd-arc** [comment]
This has nothing to do with the plugin and is a well known [React native bug](https://github.com/facebook/react-native/issues/6802). TL;DR: Android acts like it applies an `overflow: hidden` rule to every single view.

You can either add a wrapper with the necessary padding around the view with the shadow or try [this trick](https://medium.com/entria/solving-view-overflow-in-android-reactnative-f961752a75cd).

Here's your snap updated with the padding trick: https://snack.expo.io/S1LV9oKuB

**Comment by RWOverdijk** [comment]
Well that sucks... Luckily, there's me. And me has good news.

https://github.com/facebook/react-native/commit/b81c8b51fc6fe3c2dece72e3fe500e175613c5d4

It's still releasing 0.61.3 (across diff tools and such)
