### ISSUE TITLE
Crop item when scale

### ISSUE THREAD

**Issue by serzmerz** [archriss/react-native-snap-carousel#594]
### Is this a bug report, a feature request, or a question?

Bug report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Expected Behavior

Render overflow like on ios without  cropping.

### Actual Behavior

crop my item component when i try to scale component
screenshot: 
<img width="304" alt="Screen Shot 2019-10-09 at 5 29 36 PM" src="https://user-images.githubusercontent.com/24809641/66490900-92401280-eaba-11e9-9e5b-148ac2407477.png">

item in carousel cropped, at the botom you can see normal rectangle

#
<img width="304" alt="Screen Shot 2019-10-09 at 5 29 36 PM" src="https://user-images.githubusercontent.com/24809641/66490890-8d7b5e80-eaba-11e9-906d-d4aa1f1aa8a5.png">
## Reproducible Demo

link on snack https://snack.expo.io/SJiQoDiOS,

### Steps to Reproduce

1. render list of items in carousel
2. scale active element

**Comment by bd-arc** [comment]
Crop, overflow and Android? You're probably subject to [this](https://github.com/archriss/react-native-snap-carousel/issues/592#issuecomment-539357582).

**Comment by serzmerz** [comment]
Overflow on Android working since 0.59

**Comment by serzmerz** [comment]
I also updated the snack: https://snack.expo.io/BkGj7P3OS
Here I compared with the same FlatList and it works fine, but with a carousel I still have problems.
