### ISSUE TITLE
Can i achieve that effect

### ISSUE THREAD

**Issue by mingxin-yang** [archriss/react-native-snap-carousel#595]
![img](https://github.com/mingxin-yang/mingxin-yang.github.io/blob/master/images/1570689280774026.gif?raw=true)

**Comment by bd-arc** [comment]
No, it's not meant for this kind of effect.

You'll probably be better off with one of these plugins:

- https://github.com/lhandel/react-native-card-flip
- https://github.com/moschan/react-native-flip-card

**Comment by mingxin-yang** [comment]
@bd-arc Sorry I want to achieve the effect of the lower left corner, it is a swipe effect

**Comment by bd-arc** [comment]
The plugin will allow you to do that, but you could also just use a regular `ScrollView` with [a `snapToOffsets` prop](https://facebook.github.io/react-native/docs/scrollview.html#snaptooffsets).

**Comment by mingxin-yang** [comment]
this is my code now
```javascript
<Carousel
    ref={c => {
      this._carousel = c;
    }}
    data={x.photo}
    renderItem={this._renderItem.bind(
      this
    )}
    sliderWidth={90}
    hasParallaxImages={true}
    useScrollView={true}
    snapToOffsets={2}
    activeSlideOffset={2}
    enableMomentum={true}
    containerCustomStyle={{
      marginTop: 5,width:90
    }}
    itemWidth={30}
  />
```
when I add **useScrollView** and **snapToOffsets** , This error has occurred:

> Error while updating property 'snapToOffsets' of a view managed by: AndroidHorizontalScrollView Value for snapToOffsets cannot be cast from Double to ReadableArray

**Comment by mingxin-yang** [comment]
@bd-arc I want to let the active at the left of the view when it is the first. It is center now.

**Comment by bd-arc** [comment]
You're not supposed to use `snapToOffsets` with the carrousel. It will only mess things up.

Also make sure to read [the doc](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md), particularly regarding prop `activeSlideAlignment`.

**Comment by mingxin-yang** [comment]
> You're not supposed to use `snapToOffsets` with the carrousel. It will only mess things up.
> 
> Also make sure to read [the doc](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md), particularly regarding prop `activeSlideAlignment`.
I had tried `activeSlideAlignment`, It can't achieve like the gif. I also make the active center except the first and the last
