### ISSUE TITLE
inactiveSlideOpacity prop not working on Android

### ISSUE THREAD

**Issue by AndreaScapellato** [archriss/react-native-snap-carousel#603]
Code:

```javascript
<Carousel
    ref={c => {
        this._carousel = c;
    }}
    data={this.cards}
    renderItem={this._renderItem}
    sliderWidth={SCREEN_WIDTH}
    itemWidth={SCREEN_WIDTH}
    layout={"stack"}
    inactiveSlideOpacity={1}
    firstItem={Platform.OS == "android" ? this.cards.length - 1 : 0}
    containerCustomStyle={{
        transform: [{ scaleX: Platform.OS == "android" ? -1 : 1 }]
    }}
/>
```

As you can see, even if i set inactiveSlideOpacity to 1, the inactive cards still not have full opacity

![Screen](https://user-images.githubusercontent.com/28043186/67195896-16b75d00-f3fa-11e9-89e5-09e14783dfd0.jpg)

**Comment by bd-arc** [comment]
@AndreaScapellato I don't know what you're exactly trying to achieve, but [custom interpolations](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md) would be a much better way to go IMO.

**Comment by AndreaScapellato** [comment]
@bd-arc i would like to remove that transparency on the inactive slides, i've just set the inactiveSlideOpacity prop to 1, but as you can see in the pic, there is still transparency and it's visually bad

**Comment by bd-arc** [comment]
@AndreaScapellato `inactiveSlideOpacity` has no effect over the `stack` layout.

What you need to do is provide your own custom interpolation. You can basically copy-paste [the one created for the stack effect](https://github.com/archriss/react-native-snap-carousel/blob/master/src/utils/animations.js#L111-L198) and get rid of [the opacity interpolation](https://github.com/archriss/react-native-snap-carousel/blob/master/src/utils/animations.js#L147-L151).

**Comment by bd-arc** [comment]
@AndreaScapellato FYI, starting with version `3.8.3` the peaking slides will remain opaque if `inactiveSlideOpacity` is set to `1`.

**Comment by RWOverdijk** [comment]
@bd-arc Thanks for that, I'm glad I can remove the interpolation now 🎉
