### ISSUE TITLE
ListHeaderComponent support? 

### ISSUE THREAD

**Issue by vonwao** [archriss/react-native-snap-carousel#606]
### Is this a bug report, a feature request, or a question?

question/feature-request

Since I read this is using FlatList, is there support to set the ListHeaderComponent in the Flatlist?  I'd like to display a header but for it to be inside the carousel view

**Comment by bd-arc** [comment]
@vonwao I'm afraid this is to going to mess with the component's inner logic.

See #291 for more info.
