### ISSUE TITLE
get entry details onScroll?

### ISSUE THREAD

**Issue by jothikannan** [archriss/react-native-snap-carousel#618]
I would like to know is there any way to get the details of the current entry onScroll callback?

```
      entries = [
        {
            title: 'Aug 1',
        },
        {
            title: 'Aug 2',
        },
        {
            title: 'Aug 3',
        },
        {
            title: 'Aug 4',
        },
        {
            title: 'Aug 5',
        },
        {
            title: 'Aug 6',
        }
    ];

  <Carousel
              ref={ (c) => { this._carousel = c; } }
              data={this.state.entries}
              renderItem={this._renderItem.bind(this)}
              sliderWidth={450}
              itemWidth={180}
              layout={'default'}
              firstItem={0}
              onScroll={this._scrollnav.bind(this)}
            />

```
onScroll I wan tot get the title of the currentIndex, is there any default way to get it? or should I try
to get it by index?

**Comment by dpk787098** [comment]
i am also looking for solution. i want to detect the current index when scroll ends. i have tried onScroll, onScrollEndDrag, onSnapToItem, onBeforeSnapToItem. they didn't worked properly for me.

**Comment by bd-arc** [comment]
@jothikannan I definitely don't recommend handling that in `onScroll` since the event is triggered hundreds of times in a single second. What's your use case?

@dpk787098 `onSnapToItem` and `onBeforeSnapToItem` are supposed to provide you with this information. What's not working properly?

**Comment by jothikannan** [comment]
@dpk787098 In your case if you want to get current Index use  
`onSnapToItem={(index) => this.setState({activeSlider:index}) }` should work

**Comment by jothikannan** [comment]
> @jothikannan I definitely don't recommend handling that in `onScroll` since the event is triggered hundreds of times in a single second. What's your use case?
> 
> @dpk787098 `onSnapToItem` and `onBeforeSnapToItem` are supposed to provide you with this information. What's not working properly?

I have fixed it with onSnapToItem and set into state to be used in the other component, so I am closed the issue
