### ISSUE TITLE
How to control either inactive or active item width only.

### ISSUE THREAD

**Issue by devopsmanta** [archriss/react-native-snap-carousel#619]
The goal is to make the width of active item double the width of the inactive item.
By default, inActiveSlideScale changes the width and height of the inactive item.
I would like to change only the width scale.

**Comment by bd-arc** [comment]
See [custom interpolations](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md) and #594.
