### ISSUE TITLE
Autoplay is failing

### ISSUE THREAD

**Issue by ajaysaini-sgvu** [archriss/react-native-snap-carousel#630]
Hello I have integrated this plugin in my application. I want to turn off the auto play of the carousel. 

Here is I am doing  `autoplay={false}` and using version `react-native-snap-carousel - 3.8.0`

This is not working for me. Can you help what I am missing here ?

**Comment by bd-arc** [comment]
Autoplay is turned off by default. Can you provide a [Snack example](https://snack.expo.io/) in which the issue can be reproduced?

**Comment by bd-arc** [comment]
Closing as no further feedback has been provided.

**Comment by Aung-Myint-Thein** [comment]
Hello @bd-arc , can you help me take a look for this? https://github.com/archriss/react-native-snap-carousel/issues/628 :D
