### ISSUE TITLE
Scroll constantly auto scrolls to the first item

### ISSUE THREAD

**Issue by yanush** [archriss/react-native-snap-carousel#64]
I was trying to use this library on my project, and for some reason whenever I scroll, the list auto jumps to the first Item.
Have any idea what am I doing wrong?

**Comment by yanush** [comment]
nm. found the problem

**Comment by tiaaaa123** [comment]
Which is? I have the same problem :/

**Comment by gonzalezchris** [comment]
@tiaaaa123  @yanush what was the issue? I also have the same issue
