### ISSUE TITLE
No smooth sliding of pictures if there are more than 30 pictures in carousel

### ISSUE THREAD

**Issue by NeerajaaG** [archriss/react-native-snap-carousel#645]
### Is this a bug report, a feature request, or a question?

question

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

(yes.)

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

both

### Is the bug reproductible in a production environment (not a debug one)?

both production and debug

### Environment

(  Environment:
   "react": "16.8.6",
    "react-native": "^0.60.6",
   "react-native-snap-carousel": "^3.8.4",

  Target Platform:
    Android (5.0).)

### Expected Behavior

(smooth scrolling of pictures if the carousel contains more than 100 pictures)

### Actual Behavior

1.slide moves to right, if I try to swipe left and vice versa.

### Reproducible Demo

https://snack.expo.io/BkamVJ1z8

### Steps to Reproduce

(Write your steps so that anyone can reproduce the issue in the Snack demo you provided.)

apiResponse:
  [ {
     "path": "file:///storage/emulated/0/SHAREit/pictures/Download/Hills.jpeg",
     "metadata":["snow", "tree"]
    },
]
my carousel renderItem has following components
1. array  of pictures : display pictures from path(getting from api
2. array that has metadata items(scroll items if it has more data)
3. When tapping on picture call modal and shows full picture

Here, touchable events are shows abnormal behaviour. If I want to scroll on metadata slider is scrolling and moves to next slide and delay of 10sec while sliding

![Screenshot_2020-01-24-15-28-26](https://user-images.githubusercontent.com/36062997/73351769-b9af2b00-42b5-11ea-89d0-9d50563fa9eb.png)

**Comment by bd-arc** [comment]
@NeerajaaG Looking at your code, I'm positive the culprit is this: `useScrollView={true}`.

As stated in the doc, you should absolutely avoid setting that to `true` when not required as this will basically render all items at once.

*Your Snack example is not working by the way (error `Device: /module:/App.js: Unexpected token, expected "," (59:32)`).*
