### ISSUE TITLE
How can I center the selected item on landscape mode?

### ISSUE THREAD

**Issue by yanush** [archriss/react-native-snap-carousel#65]
Using the example project, I have enabled landscape mode, and when I rotate the device, the selected item is not centered anymore.
How can I fix this behavior?

**Comment by bd-arc** [comment]
Hey @yanush,

We haven't tried that yet, but I would use the prop [`onLayout`](https://facebook.github.io/react-native/docs/view.html#onlayout) on the carousel or its container to update `sliderWidth` and `itemWidth`.

Could you tell me if that works for you?

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.

**Comment by bd-arc** [comment]
For the record, here is the current way to handle device rotation: https://github.com/archriss/react-native-snap-carousel#handling-device-rotation

**Comment by abhatia-lix** [comment]
@bd-arc The readme for Handling Device Rotation has been removed?

**Comment by bd-arc** [comment]
@abhatia-lix I assume you're looking for [this](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/TIPS_AND_TRICKS.md#handling-device-rotation)? :-)
