### ISSUE TITLE
Question: Can i use this library for my project to accomplish my task?

### ISSUE THREAD

**Issue by micheilsgrey** [archriss/react-native-snap-carousel#656]
### Is this a bug report, a feature request, or a question?

Question.

Hello react-native-snap-carousel community! I am new to Javascript/react-native so i have a question. Is it possible to make UI same as on my example with this library, most importantly can i customise somehow Pagination Component so it looks same as mine ? I am using Redux for getting data from server  and storing it in redux store then i want to populate carousel with the data from my redux store . I am getting 20 objects which has data i want to show in cards/views in crousel. Thanks in advance! 

Example: 
![joxi_screenshot_1582758880423](https://user-images.githubusercontent.com/8958040/75397654-7a9de500-5908-11ea-8342-5b8e87165d66.png)

**Comment by GuillaumeSarfati** [comment]
Yes it look like the perfect component to do that be sure to adjust the width of your item to take the full size and no problem

**Comment by micheilsgrey** [comment]
Thanks i already figured it out. Finished this task a week ago.
