### ISSUE TITLE
How to align the left and Right Hidden card to same height in Centre card?

### ISSUE THREAD

**Issue by ramkumarb** [archriss/react-native-snap-carousel#658]
I would like  to align the left and Right card to Same Height, centre card is slightly at the top.

How to align the cards in Parallelex effects in same line?

![Screenshot_20200228-182041](https://user-images.githubusercontent.com/7746172/75550166-51d83580-5a57-11ea-8a2b-9e10274cae6b.png)

**Comment by rahulnainwal107** [comment]
I am also looking for the same ?

**Comment by GuillaumeSarfati** [comment]
Hello guys just write the props inactiveSlideScale={1} et alignez vos elems

**Comment by bd-arc** [comment]
@ramkumarb I'm pretty sure you've used the `inactiveSlideShift` prop, didn't you? This one will indeed translate the active slide up or down depending on its value.

Just set it to `0` or remove it, and everything should be aligned then.
