### ISSUE TITLE
_onScroll fails after remove a scrolled item 

### ISSUE THREAD

**Issue by JohnProg** [archriss/react-native-snap-carousel#66]
activeItem in _onScroll is undefined when I remove one item:
In this part after to remove a scrolled item, `this.state.interpolators[activeItem]` is undefined.
```
Animated[animationFunc](
              this.state.interpolators[activeItem],
              { ...animationOptions, toValue: 0 }
          ).start();
```

<img width="371" alt="screen shot 2017-05-07 at 9 31 57 pm" src="https://cloud.githubusercontent.com/assets/2661653/25788155/9fbad6fa-336c-11e7-9dee-0098d5c71f68.png">

**Comment by bd-arc** [comment]
@JohnProg Sorry for not getting back to you sooner.

Could you please provide more details about how to reproduce the bug, particularly about how you "remove" an item?

**Comment by bd-arc** [comment]
@JohnProg Version 2.3.0 should solve the issue.
