### ISSUE TITLE
Issue in 'Stack' and 'Tinder' Layout 

### ISSUE THREAD

**Issue by Amitdost** [archriss/react-native-snap-carousel#667]
Hi,

I have implemented Carousel but the issue is stack and tinder layout uses inverse effects in IOS and Android. 

Can you guys please guide me so that I can use stack or tinder layout in such a way that it remains similar in both the devices.

For Example, Stack and tinder are showing cards in stack in IOS, whereas I have to swipe first card to see the effect in Android.

**Comment by bd-arc** [comment]
@Amitdost Unfortunately, we're limited by a lot of `ScrollView` issues on Android.

Please take a look at [this section of the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/CUSTOM_INTERPOLATIONS.md#android) to learn more about it as well as see a few potential workarounds.
