### ISSUE TITLE
Config snapToNext animation duration?

### ISSUE THREAD

**Issue by heesienooi** [archriss/react-native-snap-carousel#671]
### Is this a bug report, a feature request, or a question?

Question

Is there any way to configure the `snapToNext()` animation duration? 

I have a next button which onPressed will programmatically trigger Carousel to snap to the next item.  However, in Android, the animation seems too fast to me and I'd like to slow it down to perhaps 500ms. 

What I'm seeing is like 100-150ms snap which is lightning fast. Worth mentioning, I've only tested this on Google Pixel 3a emulator. Could it be emulator issue? I'm not sure.

**Comment by bd-arc** [comment]
@heesienooi Unfortunately, this is something we've been asking for years to the React Native team (literally, see #203 for example) to no avail so far. [ScrollView's `scrollTo()` method](https://reactnative.dev/docs/scrollview.html#scrollto) just won't take any duration. And yes, that's a real bummer.

If things were to change on RN's side, I can guarantee you we'd be the first to implement it ;-)
