### ISSUE TITLE
[Carousel-v3.9.0-Android] The item gets stuck when dragged left

### ISSUE THREAD

**Issue by ahce** [archriss/react-native-snap-carousel#675]
### Is this a bug report, a feature request, or a question?

Bug

### Have you followed the required steps before opening a bug report?

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Environment

    React: 16.11.0
    React native: 0.62.1
    react-native-snap-carousel: 3.9.0

### Expected Behavior

No item stuck (previous version behavior)

### Actual Behavior

The item gets stuck when dragged left. 
This behavior is introduced by this commit archriss@9a42e4eef52e4c18bf8f177b1a0350de4a5e0c6b

![image](https://user-images.githubusercontent.com/12452003/78420637-3e585580-7627-11ea-8a0e-aaf97c845f76.png)

### Reproducible Demo

https://snack.expo.io/@ahce/a66df8

### Steps to Reproduce

1. Start expo example in Androird device
2. Drag the item to the left

**Comment by bd-arc** [comment]
Can you try the shiny new beta version and let me know how it works for you?

**[Click here to learn everything about the upcoming v4!](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/VERSION_4.md)**

**Comment by ahce** [comment]
> Can you try the shiny new beta version and let me know how it works for you?
> 
> **[Click here to learn everything about the upcoming v4!](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/VERSION_4.md)**

@bd-arc The bug continues in v4

**Comment by bd-arc** [comment]
@ahce After looking at your code, there is no bug: you're actually defining a `itemWidth` superior to `sliderWidth`, which just can't work.

Try inverting the two!

**Comment by ahce** [comment]
> @ahce After looking at your code, there is no bug: you're actually defining a `itemWidth` superior to `sliderWidth`, which just can't work.
> 
> Try inverting the two!

With the previous behavior, it was possible to drag the last item (similar to iOS), if itemWidth <= sliderWidth this does not happen.

**Comment by bd-arc** [comment]
@ahce The plugin is not meant to display items with a size superior to the one of the carousel. I think this was more of an unintended side effect.

What is your use case and what are you trying to accomplish with the plugin exactly?

**Comment by ahce** [comment]
> @ahce The plugin is not meant to display items with a size superior to the one of the carousel. I think this was more of an unintended side effect.
> 
> What is your use case and what are you trying to accomplish with the plugin exactly?

That the last item can be dragged, when it's released it's centered.
Check this [example](https://snack.expo.io/@ahce/rn-snap-carousel-bug)

Also the paging doesn't update correctly (with fast dragging on real devices). 
I had to go back to v3.8.4.

If reverse this  [commit](https://github.com/archriss/react-native-snap-carousel/commit/9a42e4eef52e4c18bf8f177b1a0350de4a5e0c6b), works fine.
