### ISSUE TITLE
How can i disable/enable swipe to next/pre slide?

### ISSUE THREAD

**Issue by nguyenchanhnghia** [archriss/react-native-snap-carousel#68]
Solution:
Add scrollEnabled to props

**Comment by kenkotch** [comment]
is there a way to disable swipe in only one direction?
I have questions in my slides and only allow going to the next if q is answered, but can go back.

**Comment by bd-arc** [comment]
@kenkotch There is no built-in way to do that.

You can try to leverage the `onScroll` prop, read the offset in the `event` argument and see if you find a way to prevent scrolling in the previous direction. There is no guarantee that it will work, but I can't think of any other way to try and implement this feature.

**Comment by diogoviannaaraujo** [comment]
Got all the way to detecting the direction fo the scroll and getting the event
found no way to stop scrolling the, prevent default don't work

**Comment by g1un** [comment]
I did it the next way:
```
const [users, setUsers] = useState([]);
...
<Carousel
  ref={(ref) => (carousel.current = ref)}
  data={users}
  onSnapToItem={() => {
    setUsers(users.slice(1));
    carousel.current.snapToItem(0, false, false);
  }}
/>
```
