### ISSUE TITLE
I got a warning when use react-native-snap-carousel

### ISSUE THREAD

**Issue by shenxiang11** [archriss/react-native-snap-carousel#690]
> Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release.

The warning appears both in verson 3.9.0 and 4.0.0-beta-2

**Comment by NelsonPRSousa** [comment]
Duplicated #672

**Comment by bd-arc** [comment]
Fixed in versions `3.9.1` and `4.0.0-beta.4` with backward-compatible code.
