### ISSUE TITLE
How to right align carousel using react-native-snap-carousel?

### ISSUE THREAD

**Issue by NelsonPRSousa** [archriss/react-native-snap-carousel#695]
### Is this a bug report, a feature request, or a question?

Question

I am trying to align the end of the carousel to the right.

This is how I defined the Carousel:

```javascript
<Carousel
    data={pointsOfSale}
    firstItem={0}
    renderItem={renderItem}
    sliderWidth={sliderWidth}
    itemWidth={itemWidth}
    hasParallaxImages
    containerCustomStyle={{
        marginStart: theme.mixins.widthPercentageToDP(2),
    }}
    inactiveSlideScale={1}
    inactiveSlideOpacity={1}
    activeSlideAlignment="start"
/>
```

With the property `activeSlideAlignment="start"` I was able to align the start of the carousel to the left. However, if I scroll to the end, the last item will align at the left (the same position as the first item). I would like to keep the last item in the right, just like FlatList.

Current behaviour:
![g8ksY](https://user-images.githubusercontent.com/8364345/82165330-8ae0b300-98ac-11ea-8e12-4c1e5b8a7c20.gif)

I would like to avoid those empty spots.

### Environment

React: 16.11.0
React native: 0.62.2
react-native-snap-carousel: 3.9.0

Thank you!

**Comment by bd-arc** [comment]
Not possible with version 3.x of the plugin.

However, this is something I've implemented as best I could in version 4 (currently in beta). More info [there](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/VERSION_4.md). Prop `useExperimentalSnap` is what you're looking for.

⚠️ Make sure to carefully read the description of that prop to see if it fits your use case!

**Comment by 16ntu1120** [comment]
@bd-arc I just wanted carousel to render cards from right to left rather then left to right. can you plz guide me?
