### ISSUE TITLE
onScroll doesn't get invoked

### ISSUE THREAD

**Issue by dittmarconsulting** [archriss/react-native-snap-carousel#70]
Env:
"react": "16.0.0-alpha.6",
"react-native": "0.43.3",
"react-native-snap-carousel": "^2.1.2"

Problem:
onScroll does not get invoked whilst scrolling

     <Carousel
        ref={(carousel) => { this._carousel = carousel }}
        sliderWidth={width}
        inactiveSlideScale={1}
        inactiveSlideOpacity={1}
        enableMomentum={false}
        itemWidth={width}
        onSnapToItem={::this._imageIndex}
        onScroll={() => { console.log('onScroll!') }}>
           {imageArray}
      </Carousel>

**Comment by bd-arc** [comment]
Hey @dittmarconsulting,
Looking at [the relevant source code](https://github.com/archriss/react-native-snap-carousel/blob/master/index.js#L545), it is obvious why this can't work. My mistake: I've merged a [PR](https://github.com/archriss/react-native-snap-carousel/pull/69) yesterday without actually checking that it was working.

I'll quickly add a specific prop for this use case.

**Comment by bd-arc** [comment]
@dittmarconsulting I've just published version 2.1.4 that adds prop `onScrollViewScroll`. Could you please confirm that it works for you?

**Comment by dittmarconsulting** [comment]
That works like a charm @bd-arc . 

Thanks for the fast response. 

Keep up with the great work.
