### ISSUE TITLE
Android snap is very bad

### ISSUE THREAD

**Issue by cinder92** [archriss/react-native-snap-carousel#71]
When you scroll to fast on Android, the snap item is very bad, an is not like in you show case app.
```
<Carousel
			ref={(carousel) => { this._carousel = carousel; }}
			sliderWidth={sliderWidth}
			itemWidth={itemWidth}
			firstItem={currentIndex}
			inactiveSlideScale={0.9}
			inactiveSlideOpacity={1}
			enableMomentum={false}
			showsHorizontalScrollIndicator={false}
			snapOnAndroid={true}
			enableSnap={true}
			containerCustomStyle={containerCustomStyle}
			contentContainerCustomStyle={contentContainerCustomStyle}
			onSnapToItem={(index) => {
				this.setState({
					currentIndex : index
				});
			}}
			>
                         {this._renderItems()}
                       </Carousel>
```

any fix about this?

**Comment by bd-arc** [comment]
@cinder92 Unfortunately, it has to do with React Native's `<ScrollView />` implementation.
You can find some useful information in [this thread](https://github.com/archriss/react-native-snap-carousel/issues/27).

**Comment by gmverdon** [comment]
The problem especially seems to occur when you have not yet scrolled through all the carousel childrens. When you do scroll to them, scrolling back goes much much smoother.

**Comment by bd-arc** [comment]
@gmverdon This is an interesting lead.
@cinder92 Could you try adding `renderToHardwareTextureAndroid={true}` to either the slides or the `Carousel` component itself? As you can read [here](https://facebook.github.io/react-native/docs/performance.html#moving-a-view-on-the-screen-scrolling-translating-rotating-drops-ui-thread-fps), it might help with scrolling performance.

**Comment by cinder92** [comment]
where do i need to put renderToHardwareTextureAndroid?

**Comment by bd-arc** [comment]
Well, you could try either:
```
<Carousel renderToHardwareTextureAndroid={true}>{ this._renderItems() }</Carousel>
```
or in your `_renderItems()` method:
```
<YourSlideContainer renderToHardwareTextureAndroid={true}>{ ... }</YourSlideContainer>
```

This is not a guaranteed fix, but @gmverdon's comment made me think that it could help.

**Comment by gmverdon** [comment]
I tried it, but unfortunately it did not have a significant boost in the snapping behaviour.

**Comment by bd-arc** [comment]
@gmverdon @cinder92 Could you post a short screencast of the issue so I can clearly see what's at stake and try to hack a way around?

**Comment by bd-arc** [comment]
Version 2.2.0 adds the prop `scrollEndDragThrottleValue` that can help smoothing things a bit.

Still, bear in mind that we have no control over `ScrollView`'s implementation on which the plugin is based. Android's `scrollTo` animation is unfortunately too quick and quite brutal and, at the moment, there is no way for us to change this. Go spam [React Native's Feature Request](https://react-native.canny.io/feature-requests) ;-)

I'm closing this for now since there is nothing we can do for now, but we'll be on the lookout for any update on React Native's side.

**Comment by bd-arc** [comment]
@gmverdon I've just thought about this: have you tried passing `useNativeDrive: true` to the carousel with prop `animationOptions`? Something along those lines:
```
<Carousel
  animationOptions={{
      easing: Easing.out(Easing.quad), // Easing.elastic(1),
      duration: 350,
      isInteraction: false,
      useNativeDriver: true
  }}
/>
```

It shall give you a huge boost in scrolling performance...

**Comment by Spookykiller** [comment]
This indeed, combined with the new release, gives me a performance boost. However, the snapping is still more responsive when swiping from right to left, in comparison from left to right. The initial slide is the first slide.

**Comment by bd-arc** [comment]
Hi @Spookykiller,
I really have trouble wrapping my head around this one. I'm pretty sure this has to do with `ScrollView`'s implementation.

We will soon start working on implementing `FlatList` instead (see #73). Let's hope this is going to help!

**Comment by jkvim** [comment]
Hi @bd-arc , what is the`Easing` module in your example 

```
<Carousel
  animationOptions={{
      easing: Easing.out(Easing.quad),
      duration: 350,
      isInteraction: false,
      useNativeDriver: true
  }}
/>
```

**Comment by bd-arc** [comment]
Hi @jkvim,

It comes straight from [React Native's doc](https://facebook.github.io/react-native/docs/easing.html) ;-)

**Comment by jkvim** [comment]
@bd-arc thanks.
