### ISSUE TITLE
Cannot swipe the carousel on Android devices

### ISSUE THREAD

**Issue by nghiadt91** [archriss/react-native-snap-carousel#72]
I have run an example using code from your source. It work fine on iOS but totally stuck on Android.
I cannot swipe or move any item like the list is stuck.
Tried on both emulator and real device but it still not working.
Using react v0.44.0
![screenshot_20170519-222547](https://cloud.githubusercontent.com/assets/5374576/26255193/0a25a1bc-3ce3-11e7-991c-021df8e8bb4c.png)

**Comment by bd-arc** [comment]
@nghiadt91 This is strange since we are using the plugin with RN 0.44 without any issue.
On which version of Android have you tested it?

**Comment by nghiadt91** [comment]
@bd-arc I have found the root issue. That is I put the flex:1 into sliderContainer style.
The issue was fixed when I remove this property
Thanks a lot

**Comment by bd-arc** [comment]
@nghiadt91 Thanks for letting us know. And I can confirm that you should never use `flex: 1` with `contentContainerCustomStyle` in a `<ScrollView />` ;-)
