### ISSUE TITLE
Can we have a custom key extractor?

### ISSUE THREAD

**Issue by t-ricci-enhancers** [archriss/react-native-snap-carousel#730]
In case I need to change the ordering of the elements in the carousel

https://github.com/archriss/react-native-snap-carousel/blob/0e5c1d412b0cd9eea7d058cbfb9d27d083942364/src/carousel/Carousel.js#L513

**Comment by bd-arc** [comment]
@t-ricci-enhancers As you can see [here](https://github.com/archriss/react-native-snap-carousel/blob/0e5c1d412b0cd9eea7d058cbfb9d27d083942364/src/carousel/Carousel.js#L1233), you can indeed pass your own `keyExtractor` prop to override the automatically added one.
