### ISSUE TITLE
react-native link react-native-snap-carousel not working for 0.62.2 version of React native.

### ISSUE THREAD

**Issue by selvarajendran** [archriss/react-native-snap-carousel#733]
react-native link react-native-snap-carousel not working for 0.62.2 version of React native.

### Environment

  Environment:
    React: 16.11.0
    React native: 0.62.2
    react-native-snap-carousel: 3.9.1

  Target Platform:
    Android (9.0)

### Expected Behaviour

It should automatically link/ add the dependencies to the corresponding IOS/ android files.

### Actual Behaviour

It is not linking/adding dependencies to android.

**Comment by selvarajendran** [comment]
As I am new to android development, if you could help me to manually link the package to the android it would be great help. For debug build it is working fine. whereas for the release build it is not loading.

Many Thanks.

**Comment by bd-arc** [comment]
@selvarajendran The plugin has no external native dependencies — apart from the React native ones that is.

So no `react-native link` command is required to use it.
