### ISSUE TITLE
Is it possible to make sliderWidth and itemWidth animated ?

### ISSUE THREAD

**Issue by RichardNassar1** [archriss/react-native-snap-carousel#736]
I'm trying create a snap carousel and under it a scroll view when the scroll view is scrolled to the top I want the carousel's width and item width to be 100%, and reduce the height... for the height it's working I'm rendering <Animated.View> ... , how can I do that to the width?

**Comment by bd-arc** [comment]
@RichardNassar1 Unfortunately, this is not possible at this point and would prove really tricky to implement.
