### ISSUE TITLE
Retrieving current index without waiting end of slide

### ISSUE THREAD

**Issue by GuillaumeA07** [archriss/react-native-snap-carousel#738]
When I try to retrieve the current index of the carousel item, there is a one second delay. How can I retrieve the index of the current object without waiting for the end of the slide movement.
I was using momentum but now it is deprecated.

I use this 
`onSnapToItem={index => this.setState({ activeIndexCarousel: index })} />`

Thank you for the help!

**Comment by oliverdolgener** [comment]
you could use `onBeforeSnapToItem` or write your own logic in `onScroll` like so:
```
onScroll={({ nativeEvent }) => {
  const { contentOffset } = nativeEvent;
  const index = Math.round(contentOffset.x / width);
  if (index !== activeIndex) {
    setActiveIndex(index);
  }
}}
```

**Comment by GuillaumeA07** [comment]
@oliverdolgener thanks for your help but onBeforeSnapItem has been deleted on version 4. For the onScroll event script you wrote, carousel is broke when using it. The others items still blur and in small size when scrolling.

**Comment by marvesimate** [comment]
@GuillaumeA07 kindly show an example fo how you used **onScrollIndexChanged**
