### ISSUE TITLE
bundling failed: SyntaxError: react-native-snap-carousel/src/pagination/Pagination.tsx: Unexpected token (11:12)

### ISSUE THREAD

**Issue by imrahulpatel** [archriss/react-native-snap-carousel#751]
I am getting the error when trying to run on android by react-native run-android

![Screenshot 2020-08-28 at 11 29 49 AM](https://user-images.githubusercontent.com/9443277/91526828-23fa7d80-e922-11ea-8d25-386de019284c.png)

**Comment by Titozzz** [comment]
Looks like your config cannot process typescript 3.8, make sure you are up to date :)

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

**Comment by switch13** [comment]
Same error here. 
![image](https://user-images.githubusercontent.com/1906710/91769640-c11d1680-ebad-11ea-8386-7f3ba25bab98.png)

**Comment by nonvongsochnith** [comment]
I also get the same error after yarn android. 
Can anyone help? 


Loading dependency graph, done.
error: bundling failed: SyntaxError: /home/dell/Documents/Projects/ucshipping-app/node_modules/react-native-snap-carousel/src/utils/animations.ts: Unexpected token (2:12)

  1 | import { Platform, Animated } from 'react-native';
> 2 | import type { CarouselProps } from 'src/carousel/types';
    |             ^
  3 | 
  4 | const IS_ANDROID = Platform.OS === 'android';
  5 | 
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99.2% (1491/1497)::ffff:127.0.0.1 - - [01/Sep/2020:13:20:21 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 99.2% (1491/1497), failed.
![Screenshot from 2020-09-01 20-28-07](https://user-images.githubusercontent.com/59134375/91857156-ba67cf80-ec91-11ea-89dc-7d96301db49f.png)

**Comment by NonkelDaniel** [comment]
I had the same error and noticed that yarn had automatically  installed version `^4.0.0-beta.6`. I downgraded to the latest stable version (`3.9.1`) and the error was no longer thrown.

**Comment by nonvongsochnith** [comment]
Thank you for your feedback @NonkelDaniel . May I know how to downgrade? or we just change version directly in package.json?

**Comment by NonkelDaniel** [comment]
@nonvongsochnith You can change the version directly in your package.json and then run yarn install again.

**Comment by Titozzz** [comment]
@bd-arc The last beta was mistakenly push to 'latest' on npm

Everyone else, have you tried https://github.com/archriss/react-native-snap-carousel/issues/751#issuecomment-683897541 ? This should fix it + get you access to the beta that is faster and typed natively..

**Comment by bd-arc** [comment]
Damn, that's entirely on me! I forgot to add the tag `beta` when publishing your update...

Does anyone know a a way of unpublishing a specific version or tag it as `beta` once it's published?

PS — Note that version 4 is soon to become the default version of this library.

**Comment by Titozzz** [comment]
Yes you can use npm set tag iirc

**Comment by bd-arc** [comment]
I've updated the tags and the latest release has been reverted to `3.9.1`.

You no longer should have this issue — until v4 is actually published :-)
