### ISSUE TITLE
Feature Request: "Flat" Interpolation

### ISSUE THREAD

**Issue by Immortalin** [archriss/react-native-snap-carousel#752]
Hi! Thanks for building this. I am looking for an interpolation with no shape transformations whatsoever. That is, the default interpolation except  the size of all cards remains constant and the only translation is on the x-y plane. (like tiktok)

**Comment by CantFayle** [comment]
> You can simply set inactiveSlideScale={1} to make items move horizontally.

https://github.com/archriss/react-native-snap-carousel/issues/504
