### ISSUE TITLE
[v4.0.0-beta.6] Rendering issue about custom initial animated value inside renderItem

### ISSUE THREAD

**Issue by ajacquierbret** [archriss/react-native-snap-carousel#756]
### Is this a bug report, a feature request, or a question?

It's a bug.

### Have you followed the required steps before opening a bug report?

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

No, it's not a React Native bug.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Yes this bug can be reproduced on both iOS and Android.

### Is the bug reproductible in a production environment (not a debug one)?

Yes this bug is reproductible in a production environment.

### Environment

Environment :
    React: 16.11.0
    React native : 0.62 (Expo SDK 38)
    react-native-snap-carousel: 4.0.0-beta.6

### Expected Behavior

It is expected that animations made inside rendered items components are fired.

### Actual Behavior

Animations inside renderItem component don't fire at all.

### Reproducible Demo

Really, it's impossible to provide a snack exemple because of the complexity of my app. I rely on way too much libraries, backend services and custom primitive components. But I'm 100% sure the problem isn't related to this. It'd take a complete day of work to build a working snack exemple.

If needed, I will try to provide a very simple snack exemple of the issue.
 

### Steps to Reproduce

1. Put some React Animated API color interpolations animations inside your rendered components (renderItem).
2. Fire animations by touching some TouchableOpacity components located inside rendered components.
3. See that everything works but animations don't fire, even with `useScrollView` prop set (I thought it could be related to Flatlist).

### IMPORTANT

- Animations I use don't rely on `useNativeDriver` since they are used by `backgroundColor` props.
- Animations are perfectly working inside components rendered by react-native-swiper library or horizontal ScrollView components.
- `useScrollView` prop doesn't seem to fix the problem.
- I'm using the latest react-native-snap-carousel version (4.0.0-beta.6)

**Comment by ajacquierbret** [comment]
I just figured out that animation doesn't fire because the previous value it takes (`initialValue`) is the same as the `toValue` prop. Don't know why it changes from a library to another though.

Here's the culprit :

```jsx
export const useTemperatureColorAnimation = (
  temperature: number,
  temperatureType: AppTemperatureType = 'setpoint',
): Animated.AnimatedInterpolation => {
  const animatedTemperature = useAnimation({
    type: 'spring',
    // initialValue: temperature (-1 || +1)
    toValue: temperature,
    useNativeDriver: false, // unfortunately not possible by native...
  });

  return useConstant(() => {
    const inputRange = [
      TemperatureThresholds.off,
      TemperatureThresholds.off + 1,
      TemperatureThresholds.antifreeze,
      TemperatureThresholds.min,
      TemperatureThresholds.medium - 1,
      TemperatureThresholds.medium,
      TemperatureThresholds.hot - 1,
      TemperatureThresholds.hot,
    ];
    const outputRangeColors: AppColorName[] = [
      getTemperatureColor(TemperatureThresholds.off, temperatureType),
      getTemperatureColor(TemperatureThresholds.antifreeze, temperatureType),
      getTemperatureColor(TemperatureThresholds.antifreeze, temperatureType),
      getTemperatureColor(TemperatureThresholds.min, temperatureType),
      getTemperatureColor(TemperatureThresholds.min, temperatureType),
      getTemperatureColor(TemperatureThresholds.medium, temperatureType),
      getTemperatureColor(TemperatureThresholds.medium, temperatureType),
      getTemperatureColor(TemperatureThresholds.hot, temperatureType),
    ];
    const outputRange = outputRangeColors.map(colorName =>
      getAppColor(colorName),
    );

    return animatedTemperature.interpolate({
      inputRange,
      outputRange,
      extrapolate: 'clamp',
    });
  });
};
```

The `initialValue` prop should be infered from the last function call, but with react-native-snap-carousel library, it doesn't. Any ideas ?

PS: I'm using react-native-animation-hooks lib.

**Comment by ajacquierbret** [comment]
Problem solved ! It wasn't about the library, sorry for opening an issue.
The problem is that I was using the `renderItem` prop this way :

```tsx
renderItem={({ item: group }: { item: AppGroup }) => <RenderItem group={group} />}
```

And not this way :

```tsx
renderItem={renderItem}
```

I was doing this because my RenderItem was using hooks, so it can't be rendered as a function and needed to be a real React functional component.

I found a solution for using hooks outside my function and then renamed "RenderItem" to "renderItem", which allowed my animations to infer the value of the `initialValue` with `toValue` prop of the previous `useTemperatureColorAnimation()` call.

I don't know why this was occuring, but this is now working ! If you have some explanations about this weird behaviour I'd be interested reading it.
Anyway, i can close this issue, hoping somebody will find this helpful.

**Comment by bd-arc** [comment]
Thank you for sharing your findings @ajacquierbret!

I'm sure it will help other people in the same situation :-)

**Comment by ajacquierbret** [comment]
Btw, here's a working snack example of the solution : https://snack.expo.io/@ajacquierbret/react-native-snap-carousel-issue
