### ISSUE TITLE
onIndexChange Function ?

### ISSUE THREAD

**Issue by ugrdursun** [archriss/react-native-snap-carousel#760]
Hello, thanks for this beautiful library.

I can't see and onIndexChange function on docs or issues, I need to adjust height according to index using state, is there any onIndexChange function or similar to do this operation ?

**Comment by ajacquierbret** [comment]
Hey @ugrdursun  ! If you are using v3, you can use `onSnapToItem`, if you are using v4, just use `onScrollIndexChanged(slideIndex)`.

Example :

```jsx
// react-native-snap-carousel v3
<Carousel onSnapToItem={(slideIndex: number) => doSomething(slideIndex)} />

// react-native-snap-carousel v4
<Carousel onScrollIndexChanged={(slideIndex: number) => doSomething(slideIndex)} />


// OR (shorter and easier) :

// react-native-snap-carousel v3
<Carousel onSnapToItem={doSomething} />

// react-native-snap-carousel v4
<Carousel onScrollIndexChanged={doSomething} />
```

**Comment by ugrdursun** [comment]
> Hey @ugrdursun ! If you are using v3, you can use `onSnapToItem(slideIndex)`, if you are using v4, just use `onScrollIndexChanged(slideIndex)`.
> 
> Example :
> 
> ```js-jsx
> // react-native-snap-carousel v3
> <Carousel onSnapToItem={(slideIndex: number) => doSomething(slideIndex)} />
> 
> // react-native-snap-carousel v4
> <Carousel onScrollIndexChanged={(slideIndex: number) => doSomething(slideIndex)} />
> 
> 
> // OR (shorter and easier) :
> 
> // react-native-snap-carousel v3
> <Carousel onSnapToItem={doSomething} />
> 
> // react-native-snap-carousel v4
> <Carousel onScrollIndexChanged={doSomething} />
> ```
> 
> PS: I highly recommend you to use v4

Thanks for your assist, but as you recommended v4; I checked my version its 3.9.1 and with npm install react-native-snap-carousel@latest its still installing 3.9.1. Want to use v4 as your suggestion but what im doing wrong?

**Comment by ajacquierbret** [comment]
react-native-snap-carousel v4 is still under beta so I need to say that you may still encounter some issues, but if you're not yet production-ready and wants to give it a try, a lot of people are putting efforts in this library, so I definitely recommend it.

To install v4-beta :

```
// with yarn :
yarn add react-native-snap-carousel@4.0.0-beta.5

// with npm :
npm i react-native-snap-carousel@4.0.0-beta.5
```

Also, you may consider beta.6 (typescript version) instead of beta.5 but it's still a work in progess, so you could need to write some @ts-ignore comments to make your IDE quiet. See : https://github.com/archriss/react-native-snap-carousel/pull/678#issuecomment-693514832

**Comment by ugrdursun** [comment]
> react-native-snap-carousel v4 is still under beta so I need to say that you may still encounter some issues, but if you're not yet production-ready and wants to give it a try, a lot of people are putting efforts in this library, so I definitely recommend it.
> 
> To install v4-beta :
> 
> ```
> // with yarn :
> yarn add react-native-snap-carousel@4.0.0-beta.5
> 
> // with npm :
> npm i react-native-snap-carousel@4.0.0-beta.5
> ```
> 
> Also, you may consider beta.6 (typescript version) instead of beta.5 but it's still a work in progess, so you could need to write some @ts-ignore comments to make your IDE quiet. See : [#678 (comment)](https://github.com/archriss/react-native-snap-carousel/pull/678#issuecomment-693514832)
> 
> Don't forget to close this issue if you achieved to install the beta 👍

Solved! Thanks for your help!
