### ISSUE TITLE
Create a specific <Image /> component for parallax effect

### ISSUE THREAD

**Issue by bd-arc** [archriss/react-native-snap-carousel#78]
The idea is to create a custom `<Image />` component aware of `Carousel`'s current scroll position and thus able to offer a nice parallax effect when scrolling.

[`react-native-parallax`](https://github.com/oblador/react-native-parallax) can serve as a good starting point.

For a preview of the effect we're after, see:
- [News App, by Krijn Rijshouwer for Framer](https://dribbble.com/shots/3370126-News-App-Page-Component-Example)
- [Invision Projects - Spaces iOS, by Charles Patterson for InVision](https://dribbble.com/shots/2845710-Invision-Projects-Spaces-iOS)

**Comment by bd-arc** [comment]
Implementation ideas :
- [Airbnb gif, biubiubiu freestyle, by JEE_lion](https://dribbble.com/shots/3623368-Airbnb-gif-biubiubiu-freestyle)

**Comment by bd-arc** [comment]
And here it is!

![react-native-snap-carousel parallax image](http://i.imgur.com/6iIb4SR.gif)

This can be tested in the [`flatlist` branch](https://github.com/archriss/react-native-snap-carousel/tree/flatlist).
[Documentation](https://github.com/archriss/react-native-snap-carousel/blob/flatlist/src/parallaximage/README.md) and [example](https://github.com/archriss/react-native-snap-carousel/tree/flatlist/example) have been updated. Let me know what you think!

![react-native-snap-carousel parallax images](http://i.imgur.com/m0297Ys.gif)

**Comment by bd-arc** [comment]
Available in version 3.0.0.

**Comment by crHand** [comment]
Hi @bd-arc !

I have an issue with the example above on Android.
When working with `ParallaxImage` (parallax={true}) the topLeft and topRight borders doesn't have radius.

Although when switching to React Native's `Image` (parallax={false}) works fine...

Any suggestion? Thanks!

**Comment by bd-arc** [comment]
Hi @crHand,

I'm sad to say that I'm well aware of the issue. Unfortunately, Android is incredibly buggy when it comes to border radiuses and images. As you can see by looking at RN issues [#8885](https://github.com/facebook/react-native/issues/8885) or [#3198](https://github.com/facebook/react-native/issues/3198), this is a classic problem.

There are a couple of workarounds in these threads that I've previously tried but weren't working at that time. Can you try them on your own and let me know if one of them is of any help?

**Comment by bd-arc** [comment]
@crHand I've tried it all, and there's just nothing we can do ATM; this is really a RN issue.

Good news though: apparently this has been fixed by [this commit](https://github.com/facebook/react-native/commit/30044fd531c22c4c5e8f1ede206fa7c2c3fd3aa8) which will land in RN `0.50.0`.

**Comment by crHand** [comment]
@bd-arc 

Yes!! I was about to reply you with that. Let's wait and see how that fix works.

Thanks!
