### ISSUE TITLE
Can't scroll any more than one item at a time

### ISSUE THREAD

**Issue by typhoon2099** [archriss/react-native-snap-carousel#79]
I'm working on a app and using react-native-snap-carousel to slide cards related to map markers. When the carousel snaps then the map is moved to the related marker. Currently this is working but I can't get the slider to move any more than a single card at a time. I have another carousel of images which does this but doesn't use the onSnapToItem property, and this snaps correctly to the item that the slider stops at. Here's the component call
`      <Carousel
        ref={(carousel) => {
          this._carousel = carousel;
        }}
        onSnapToItem={this.onSnap}
        sliderWidth={sliderWidth}
        itemWidth={itemWidth}
        firstItem={0}
        inactiveSlideScale={1}
        inactiveSlideOpacity={1}
        enableMomentum={false}
        containerCustomStyle={styles.slider}
        contentContainerCustomStyle={styles.sliderContainer}
        showsHorizontalScrollIndicator={false}
        snapOnAndroid
        removeClippedSubviews={false}
        decelerationRate={'fast'}
        renderToHardwareTextureAndroid
      >
        { this.getSlides(this.props.places) }
      </Carousel>`

I've tried tweaking options around but I still can't seem to get the desired interaction. Currently the app will scroll as far as you like but will then suddenly snap back to the next feature on the list, instead of snapping to the item that the slider comes to rest on. Am I missing a property/callback?

**Comment by bd-arc** [comment]
Hi @typhoon2099, I'm guessing you're having the issue on Android, am I right?

First, please read [this recent addition to the doc](https://github.com/archriss/react-native-snap-carousel#scrollviews-limitations) as well as #27 and #71.

Then, have you tried version 2.2.1 in conjunction with props `scrollEndDragThrottleValue` and `snapCallbackDebounceValue`? This might help a bit. Also, have you tried setting `enableMomentum` to `true`?

You mentioned another carousel; is it our plugin or another one? If it is another one, do not hesitate to share its repo with me so I can maybe find some tweaks to improve ours ;-)

**Comment by typhoon2099** [comment]
Hi, it's your carousel, it allows scrolling through multiple items at once. I haven't tried changing `scrollEndDragThrottle` and `snapCallbackDebounceValue` yet but I have set `enableMomentum` to true. I've fiddled with most of the values but end up with largely the same result.

**Comment by bd-arc** [comment]
@typhoon2099 I need to see your code to investigate further, especially the differences between the two carousels you've implemented.

Could you please share the relevant code and styles?

**Comment by typhoon2099** [comment]
I'll see what I can get to you, it's part fo a project for a client so I'll need to see what I'm permitted to share first.

**Comment by bd-arc** [comment]
@typhoon2099 Ok, but do not bother too much. A simple test case that helps me reproduce the bug would be enough ;-)

**Comment by renhongguang** [comment]
i fix it like this:
 _onScroll (event) {
       ...
            // Animated.parallel([
            //     Animated[animationFunc](
            //         this.state.interpolators[activeItem],
            //         { ...animationOptions, toValue: 0 }
            //     ),
            //     Animated[animationFunc](
            //         this.state.interpolators[newActiveItem],
            //         { ...animationOptions, toValue: 1 }
            //     )
            // ]).start();
            Animated[animationFunc](
                this.state.interpolators[newActiveItem],
                { ...animationOptions, toValue: 1 }
            ).start();

            Animated[animationFunc](
                this.state.interpolators[activeItem],
                { ...animationOptions, toValue: 0 }
            ).start();
}

**Comment by bd-arc** [comment]
Thanks @renhongguang! I guess this is linked to #81 then.

I'll run a few tests and publish a fix soon.

**Comment by typhoon2099** [comment]
Hi,
enableMomentum seems to have fixed the issue. I'm sure I had it set on before and still had issues, or perhaps I changed too many options at the same time. Apologies for the wild goose chase.

**Comment by bd-arc** [comment]
@typhoon2099 Thanks for letting me know, but I've still uncovered a bunch of edge cases (including this very issue) that I'm currently working on eradicating ;-)

**Comment by typhoon2099** [comment]
@bd-arc Glad I've managed to help out (even if it is only tangentially)!

**Comment by bd-arc** [comment]
@typhoon2099 Version 2.3.0 should solve your original issue.

You can try disabling momentum and playing with prop `scrollEndDragDebounceValue`. I recommend a higher value for Android (default is `50` for iOS and `150` for Android).
