### ISSUE TITLE
onSnapToItem not fired 

### ISSUE THREAD

**Issue by FrancisShi** [archriss/react-native-snap-carousel#80]
My device is Android Galaxy note 4

**Comment by bd-arc** [comment]
Hi @FrancisShi,

We can't help you without seeing your code and knowing which version of the plugin you're using...

**Comment by bd-arc** [comment]
@FrancisShi I've made a lot of refactoring regarding callback handling recently.

I recommend you to try version 2.3.0 and see if this solves your issue.

**Comment by itswaze** [comment]
+1

And i'm using 2.4.0
