### ISSUE TITLE
Determine swipe right at the last item in carousel

### ISSUE THREAD

**Issue by Saad-Bashar** [archriss/react-native-snap-carousel#815]
Is there any way to determine that a user is swiping right at the last item in the carousel? In my specific use case, I want to redirect them to another page if they swipe right at the last item. Thanks for any help :)

**Comment by ManhVuTien** [comment]
I have the same requirement 
```
<Carousel
...
onSnapToItem={index => {
           this.setState({ activeSlide: index });
     }}
   onScrollEndDrag={event => {
       const { contentSize, targetContentOffset } = event.nativeEvent;
       //Detect when swipe right at the last item
        if (activeSlide === lengthSlide-1 && targetContentOffset.x >= contentSize.width * ((lengthSlide - 1) / lengthSlide)) {
             // Do sth
            }
        }}
/>
```

**Comment by Saad-Bashar** [comment]
Oh thanks a lot for your kind response @ManhVuTien ! I will check it out!

**Comment by ManhVuTien** [comment]
> Oh thanks a lot for your kind response @ManhVuTien ! I will check it out!

I have changed to ```(lengthSlide - 1) / lengthSlide``` not ```lengthSlide - 1 / lengthSlide```. I missing (). you can try it again

**Comment by Saad-Bashar** [comment]
one question, what do you mean by length slide? Is it the item width? @ManhVuTien

**Comment by ManhVuTien** [comment]
> one question, what do you mean by length slide? Is it the item width? @ManhVuTien
 It means the number of item in the carousel

**Comment by Saad-Bashar** [comment]
![Screenshot 2021-02-22 at 3 18 25 PM](https://user-images.githubusercontent.com/13269141/108675057-38aa7d80-7521-11eb-886b-2f98024f592e.png)
the condition is not becoming true for me somehow, am I missing something? @ManhVuTien  
```
onScrollEndDrag={event => {
                    const { contentSize, targetContentOffset } = event.nativeEvent;
                    console.log("Content Size, targetContentOffset - ", contentSize, targetContentOffset);
                    //Detect when swipe right at the last item
                     if (isLastCard && (targetContentOffset.x >= contentSize.width * ((dummyData.length - 1) / dummyData.length))) {
                          // Do sth
                          console.log("END")
                          onNextTab()
                        }
                    }
                }
```

![Screenshot 2021-02-22 at 3 25 43 PM](https://user-images.githubusercontent.com/13269141/108675828-47456480-7522-11eb-88c8-ca15ae84d5c5.png)

I get this from your formula

**Comment by ManhVuTien** [comment]
In my case it is fullwidth

**Comment by ManhVuTien** [comment]
> ![Screenshot 2021-02-22 at 3 18 25 PM](https://user-images.githubusercontent.com/13269141/108675057-38aa7d80-7521-11eb-886b-2f98024f592e.png)
> the condition is not becoming true for me somehow, am I missing something? @ManhVuTien
> 
> ```
> onScrollEndDrag={event => {
>                     const { contentSize, targetContentOffset } = event.nativeEvent;
>                     console.log("Content Size, targetContentOffset - ", contentSize, targetContentOffset);
>                     //Detect when swipe right at the last item
>                      if (isLastCard && (targetContentOffset.x >= contentSize.width * ((dummyData.length - 1) / dummyData.length))) {
>                           // Do sth
>                           console.log("END")
>                           onNextTab()
>                         }
>                     }
>                 }
> ```
> 
> ![Screenshot 2021-02-22 at 3 25 43 PM](https://user-images.githubusercontent.com/13269141/108675828-47456480-7522-11eb-88c8-ca15ae84d5c5.png)
> 
> I get this from your formula

Can you show me itemWidth and sliderWidth?

**Comment by Saad-Bashar** [comment]
Thanks for your reply, my item width is `const itemSize = width * 0.8;` and slider width is full width. @ManhVuTien

**Comment by ManhVuTien** [comment]
> Thanks for your reply, my item width is `const itemSize = width * 0.8;` and slider width is full width. @ManhVuTien

(contentSize.width - width * 0.2) * ((lengthSlide - 1) / lengthSlide) if you don't have any margin/padding

**Comment by 7dp** [comment]
Did you know why my `onScrollEndDrag` callback didn't triggered?
Iam using version `"^3.9.1"`

In my case i want to detect left to right swipe at the first item
