### ISSUE TITLE
How to set the animation duration

### ISSUE THREAD

**Issue by viniciusdba27** [archriss/react-native-snap-carousel#821]
I'm using snap carousel beta 6 in vertical mode. I have noticed that the onSnapToItem is just called when the scroll animation has ended. Animated documentation says that default duration is 500ms. Is there any way to change scroll animation to have shorter duration so onSnapToItem could be triggered faster? I say that because I have a video in every snap then I need to play the audio when the snap is active. Currently the audio is taking 500+ms to play.

Thanks in advance! Kind Regards!

**Comment by traviswimer** [comment]
@viniciusdba27 Why was this closed? Do you figure out how to change the duration?

**Comment by viniciusdba27** [comment]
No, I did not find a way to do it.
