### ISSUE TITLE
Error on Upgrading to React Native 0.84 "The inferred type of '_getComponentStaticProps' cannot be named without a reference to 'react-native/node_modules/@types/react'"

### ISSUE THREAD

**Issue by princefishthrower** [archriss/react-native-snap-carousel#847]
### Is this a bug report, a feature request, or a question?

Bug report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [X] I have read [the guidelines regarding bug report](https://github.com/meliorence/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [X] I have reviewed [the documentation](https://github.com/meliorence/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [X] I have searched for [existing issues](https://github.com/meliorence/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [X] I am using [the latest plugin version](https://github.com/meliorence/react-native-snap-carousel/releases).
- [X] I am following [the issue template](https://raw.githubusercontent.com/meliorence/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/meliorence/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Specific to React Native in general.

### Is the bug reproductible in a production environment (not a debug one)?

It pertains to React Native upgrade, not environment.

### Environment

Environment:
    React: 16.11.0
    React native: 0.64.2
    react-native-snap-carousel: 4.0.0-beta

  Target Platform:
    Android (6.0)
    iOS (9.0)

### Expected Behavior

Upgrade from React Native 0.82 to 0.84 should work fine.

### Actual Behavior

Error during upgrade is as follows:

```
src/carousel/Carousel.tsx:1221:3 - error TS2742: The inferred type of '_getComponentStaticProps' cannot be named without a reference to 'react-native/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.

1221   _getComponentStaticProps () {
       ~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

So it seems the type annotations are missing for that function.

### Reproducible Demo

(Paste the link to a [Snack example](https://snack.expo.io/) in which the issue can be reproduced. Please follow [the guidelines](https://stackoverflow.com/help/mcve) for providing a Minimal, Complete, and Verifiable example.)

### Steps to Reproduce

Can't do a snack because it doesn't actually include specific react native versions. Upgrade from 0.82 to 0.84 with react-native-snap-carousel 4.0.0-beta installed

**Comment by princefishthrower** [comment]
In the end, this was actually an issue with npm battling yarn.  I don't believe this issue had anything to do with the library. Sorry!

**Comment by burtontanner** [comment]
@princefishthrower I am seeing the same thing in a project I am using. What did you do to fix the issue?
