### ISSUE TITLE
Style active dot in pagination differently from inactive dots

### ISSUE THREAD

**Issue by Billmike** [archriss/react-native-snap-carousel#854]
(Question.)

Is it possible to style the active dot in the pagination differently from the inactive dots? And not just the color. For instance, changing the width, height, and border-radius (pretty much adding a different style to the active dot) of the active dot

**Comment by sawane8** [comment]
Put this in pagination

`dotElement={<View style={{width:40, height: 5, backgroundColor:'grey', borderRadius: 20}} />}`

**Comment by flexbox** [comment]
Hey @Billmike 

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨
