### ISSUE TITLE
Parallax resizeMode center issue

### ISSUE THREAD

**Issue by newfylox** [archriss/react-native-snap-carousel#856]
Hi guys, using version `3.9.1` using this [example](https://github.com/meliorence/react-native-snap-carousel/blob/master/example/src/index.js#L46L87) with its appropriating [styling](https://github.com/meliorence/react-native-snap-carousel/blob/master/example/src/styles/index.style.js) I have a strange issue.

When using parallax and setting `resizeMode: "center"` instead of `resizeMode: "contain"`, the image gets larger but is not 100% width.

If passing `parallax={false}` to get a standard `<Image />` component, I have what I want, but now `resizeMode: "center"` or `resizeMode: "contain"` makes no different. The image is 100% width and centered in both case.

So how can I have the parallax effect but with a real center resize mode?

**Using Parallax example with center resize mode (losing left and right of the logo)**
<p align="center">
<img src="https://user-images.githubusercontent.com/3361669/127899143-76036f35-4f9a-4268-b3ff-862f42de5839.jpg" height="500" />
</p>

**Using standard Image component with either center or contain resize modes (no difference, what I want but with Parallax)**
<p align="center">
<img src="https://user-images.githubusercontent.com/3361669/127899246-bbbf1d14-575d-45c1-84b1-8a04e0d7c4f1.jpg" height="500" />
</p>

**Comment by dohooo** [comment]
@newfylox Sorry, please allow me to advertise for my open source library! ~
I think this library [react-native-reanimated-carousel](https://github.com/zwh1666258377/react-native-reanimated-carousel) will solve your problem. It is a high performance and very simple component, complete with React-Native reanimated 2

**Comment by Ahmedhamed77** [comment]
how did you solve it ?
