### ISSUE TITLE
Disable / Hide horizontalScrollIndicator

### ISSUE THREAD

**Issue by geovrisco** [archriss/react-native-snap-carousel#857]
hi im using react native snap carousel 
```
"react-native-snap-carousel": "^4.0.0-beta.6",
```

im using it on horizontal={true} it works fine but i cant disable the horizontal scroll indicator on some android device device eg(galaxy s7)

`
 <Carousel
                      // onMomentumScrollEnd={e => handleScrollEnd(e)}
                      showsHorizontalScrollIndicator={false}
                      onSnapToItem={slideIndex => handleScroll(slideIndex)}
                      data={productData}
                      sliderWidth={width}
                      itemWidth={CARD_WIDTH}
                      scrollEnabled={!cardExpanded}
                      layout="default"
`

my carousel is inside vertical ScrollView (i hide the scrollindicator also)

**Comment by haibert** [comment]
This is just a general message for the maintainers of this library: You guys should look into using react-native-big-list instead of flat list, its a much more performant library. It may need some changes before you guys can use it but the maintainer of the library is super responsive and active.

**Comment by geovrisco** [comment]
im sorry , actually the scroll indicator is not from the carousel. I created an indicator component with a flatlist and i forgot to disable the scroll indicator.

@haibert  thanks for replying the carousel works fine
