### ISSUE TITLE
Removing items from the carousel

### ISSUE THREAD

**Issue by typhoon2099** [archriss/react-native-snap-carousel#86]
Hi,
I'm trying to implement a filter for items but the app crashes when the currentIndex is higher than the totla number of items (from removing items from the carousel). I get `Undefined is not an object (evaluating 'singleClick.stopTracking')`. Is there a way to reset the currentIndex to 0 to prevent this error? I've tried snapToItem (using animated = false) but this is still causing the error. Without trying to reset the index then the carousel is entirely to the right and attempting to scroll will cause the error.

**Comment by bd-arc** [comment]
Hi @typhoon2099,
Can you tell me which version of the plugin you're currently using? Also, can you share the relevant source code?

**Comment by typhoon2099** [comment]
Hi, I'm using 2.3.0. Here's my code which creates the carousel:

    componentDidUpdate() {
    this._carousel.snapToItem(this.getPlacePosition(this.props.activePlaceId));
    }

    onSnap(index) {
    this.props.setActivePlace(this.props.places[index]);
    }

    getPlacePosition(currentPlaceId) {
    return this.props.places.findIndex((place) => {
      return place.id === currentPlaceId;
    });
    }

    getSlides(places) {
    if (!places) {
      return false;
    }

    return places.map((place, index) => {
      return (
        <Card
          renderToHardwareTextureAndroid
          navigator={this.props.navigator}
          last={index === places.length}
          key={`carousel-entry-${place.id}`}
          {...place}
        />
      );
    });
    }

    get carousel() {
    return (
      <Carousel
        ref={(carousel) => {
          this._carousel = carousel;
        }}
        onSnapToItem={this.onSnap}
        sliderWidth={sliderWidth}
        itemWidth={itemWidth}
        firstItem={0}
        inactiveSlideScale={1}
        inactiveSlideOpacity={1}
        enableMomentum
        containerCustomStyle={styles.slider}
        contentContainerCustomStyle={styles.sliderContainer}
        showsHorizontalScrollIndicator={false}
        snapOnAndroid
        removeClippedSubviews={false}
        decelerationRate={'fast'}
        renderToHardwareTextureAndroid
        animationOptions={{
          isInteraction: false,
          useNativeDriver: true,
        }}
      >
        {this.getSlides(this.props.places)}
      </Carousel>
    );

There's code in the parent component which filters the places and returns only the ones which match a set of selected categories. The crash can be reproduced by adding all the places to the carousel (no filtering active), scrolling to the end of the carousel, then adding some filters to reduce the number of items in the Carousel. I think the Crash is caused because the current position is past the end of the carousel.

**Comment by bd-arc** [comment]
Hi @typhoon2099,

Did you find a way to solve the issue? I'm sorry, I have been overbooked for the past weeks and didn't have time to take a look at it...

**Comment by typhoon2099** [comment]
Yes, I'm not sure what fixed it exactly but I added a pile of extra validation to my app and I can't replicate the issue any more.

**Comment by bd-arc** [comment]
Ok, good to know ;-)

**Comment by AndrewTi** [comment]
Hi @typhoon2099, @bd-arc 
I have the same problem
you can help me fix it?:)

**Comment by bd-arc** [comment]
Hi @AndrewTi,

Could you provide me with a simple example that reproduces the issue (based on [the example](https://github.com/archriss/react-native-snap-carousel/tree/master/example))? I will gladly take a look at it ;-)

Also, would you mind testing with the [`flatlist` branch](https://github.com/archriss/react-native-snap-carousel/tree/flatlist)? It contains a lot of updates and a new implementation that might help with the issue. There is a [migration guide](https://github.com/archriss/react-native-snap-carousel/tree/flatlist#migration-from-version-2x) in the README, and it is pretty straightforward.

You can use it by referencing branch's latest commit in your `package.json` file:
```
"react-native-snap-carousel": "https://github.com/archriss/react-native-snap-carousel#fbdb671"
```

**Comment by clarissarnr** [comment]
Hi how to remove flexGrow and flexShrink in carousel?
