### ISSUE TITLE
Swiping one item at a time (question)

### ISSUE THREAD

**Issue by codejet** [archriss/react-native-snap-carousel#90]
Hey, is there a way to enforce that the carousel only moves one item at a time, no matter how strong/fast the swipe is, without using a method/callback property? It already works relatively well (using the code of example 1, even better when activating momentum it seems), but it's also not too hard to swipe multiple items at a time.

**Comment by bd-arc** [comment]
Hi @codejet,

If you didn't read it already, you might find [this](https://github.com/archriss/react-native-snap-carousel#momentum) useful.

I suggest you play with the prop `scrollEndDragDebounceValue`and set it to smaller values or even `0` (note that this prop only works when momentum is disabled). I also recommend that you take a look at [`ScrollView`'s `decelerationRate`](https://facebook.github.io/react-native/docs/scrollview.html#decelerationrate) (iOS only). Unfortunately, `ScrollView` on Android doesn't provide much fine-tuning :-(

Hope this helps anyway.

**Comment by sridhard** [comment]
@codejet I am also looking for this feature. How you have supported this?

**Comment by codejet** [comment]
sorry @sridhard, i don't have access to the code anymore and after one year also don't remember the details/solution

**Comment by evanjmg** [comment]
adding  decelerationRate={0} works for me though the scroll is a little slow

**Comment by NishargShah** [comment]
@codejet how to solve this in 2020 because in V3.2.0 property `scrollEndDragDebounceValue` is removed

**Comment by princefishthrower** [comment]
Also wondering this, upgraded to 4.0.0-beta and its now possible to swipe through all items with a hard enough swipe.

**Comment by MathiasSvDK** [comment]
Any update on this?

**Comment by jslok** [comment]
> Any update on this?

This repo is no longer maintained.
