### ISSUE TITLE
Snap only one 1 index at once.

### ISSUE THREAD

**Issue by pbrochar** [archriss/react-native-snap-carousel#905]
Hello !

I would like to know how to snap from one index to the next no matter how fast you swipe.
At the moment, when I swipe "fast" I move several items. I would like to reproduce a behavior a bit like Instagram with only 1 index move, no matter the distance or the swipe speed.

Thanks for help !

**Comment by pbrochar** [comment]
Sorry, added in version 4.0.0-beta

**Comment by svenlombaert** [comment]
> Sorry, added in version 4.0.0-beta

@pbrochar how/where was this added?

**Comment by yudizAnkita** [comment]
@svenlombaert  Set below props and you will able to snap only one item/index at once

```
useExperimentalSnap={true}
disableIntervalMomentum={true}
```
