### ISSUE TITLE
onScrollEnd is not a function

### ISSUE THREAD

**Issue by jonajgs** [archriss/react-native-snap-carousel#91]
when I scroll in the carousel, I got this error, when the scroll is finish, but I am still scrolling.

**Comment by bd-arc** [comment]
Hi @jonajgs,
Could you please share your code so I can try to reproduce the bug?

**Comment by AndrePech** [comment]
I got the same problem.
Always happen when snapOnAndroid={false}

**Comment by bd-arc** [comment]
@AndrePech Good catch: I've overlooked one condition when snap was disabled.

I've just released version 2.3.1 that should resolve the issue. Can you confirm?

**Comment by AndrePech** [comment]
@bd-arc  that was fast =D

It works fine now, thanks.

**Comment by bd-arc** [comment]
@AndrePech That wasn't much trouble ;-)
