### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by coderMohammed** [archriss/react-native-snap-carousel#911]
Cannot read properties of undefined (reading 'style')
  Evaluating react-native-elements.js
  Evaluating App.js
  Loading App.js

I am getting this error when I run my app on web app

**Comment by coderMohammed** [comment]
Can Someone Please Help Me

**Comment by Exilz** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
> Although we might still help you without all these informations, it would be unfair to let some people post issues without filling everything.
