### ISSUE TITLE
Active slide delay Android

### ISSUE THREAD

**Issue by AndrePech** [archriss/react-native-snap-carousel#92]
I have noticed that the selected slide takes a while to show as active.

For example, on Android, when executing snapToItem(index) the carousel scrolls nicely to the desired slide, but it takes around 3 seconds for it to show as active.

I am using the example code.
No problem on iOS thought.

**Comment by bd-arc** [comment]
Hi @AndrePech,

I haven't been able to reproduce the issue so far. Have you tested on different Android devices?

Can you try adding the following to your `<Carousel />` and see if it helps?
```
animationFunc={'spring'}
animationOptions={{
    friction: 4,
    tension: 40,
    isInteraction: false,
    useNativeDriver: true
}}
```

**Comment by AndrePech** [comment]
Thanks @bd-arc 

The effect got better but it still taking around 2s to activate the "slide"
I might be doing something wrong o my side:

(the code below is the way it worked better, on iOS it is very smooth)

`<Carousel
              ref={(carousel) => { this._carousel = carousel; }}
              itemWidth={itemWidth}
              sliderHeight={300}
              enableMomentum={false}
              decelerationRate={0.1}
              activeSlideOffset={1}
              scrollEndDragDebounceValue={0.1}
              removeClippedSubviews={false}
              onSnapToItem={(index)=>this.onSnapToItem(index)}
              sliderWidth={sliderWidth}
              showsHorizontalScrollIndicator={false}
              containerCustomStyle={styles.carousel_container}
              animationFunc={'timing'}
              animationOptions={{
                friction: 4,
                tension: 40,
                isInteraction: false,
                useNativeDriver: true
              }}>`

I will try to test on other Android Devices, I am trying to achieve the same very smooth effect from the showcase app, with the animation starting as soon as the slide enters the screen. I will keep trying and let you know if something changes.

**Comment by bd-arc** [comment]
@AndrePech Were you, by any chance, testing in debug mode? Because carousel's performances are crappy on Android when JS Dev Mode is activated.

Regarding the number of slides, I've used it with 15 really graphic slides on an old Android device without any issue. Still, you might be interested to know that I will probably release next week a `FlatList` implementation that should solve performance issues when displaying large numbers of slides.

**Comment by AndrePech** [comment]
@bd-arc  Holy s***t I am really sorry, I is working wonder now.

Yes, I was JS DEV mode indeed, I was pretty sure it was off that did even check it. MY BAD. 
hahaha, I will stick with this library. 

Thank you very much and sorry again.
