### ISSUE TITLE
react-addons-shallow-compare missing after upgrading to 2.3.1

### ISSUE THREAD

**Issue by fendorio** [archriss/react-native-snap-carousel#93]
Just upgraded to the latest version of the repo, after clearing node modules and running **npm install** I get this error when the react native package manager is bundling my app:

```
error: bundling: UnableToResolveError: Unable to resolve module `react-addons-shallow-compare` from `/Applications/XAMPP/xamppfiles/htdocs/SiequenceRNApp/node_modules/react-native-snap-carousel/index.js`: Module does not exist in the module map or in these directories:
  /Applications/XAMPP/xamppfiles/htdocs/SiequenceRNApp/node_modules
,   /Applications/XAMPP/xamppfiles/htdocs/node_modules
```

```
{
  "name": "Test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native-scripts start",
    "test": "jest"
  },
  "dependencies": {
    "expo": "^18.0.3",
    "native-base": "~2.1.4",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-circular-slider": "^1.0.1",
    "react-native-fetch-blob": "^0.10.5",
    "react-native-image-crop-picker": "^0.13.1",
    "react-native-router-flux": "^3.39.1",
    "react-native-snap-carousel": "^2.3.1"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "1.9.2",
    "jest": "20.0.3",
    "jest-expo": "~18.0.0",
    "react-test-renderer": "16.0.0-alpha.6",
    "react-native-scripts": "0.0.40"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

I'm running on a Mac, node version 7.7.1 & npm version 5.0.4

Any ideas?

**Comment by fendorio** [comment]
I've spent the afternoon on this, tried many attempts at fixing it.

I had to add react-addons-shallow-compare to my package.json to get this to work, however doing this then lead to the same UnableToResolve error being thrown for 'lodash.debounce' package. 

I'm about to downgrade to the previous version 2.3.0 and run a fresh npm install, after removing react-addons-shallow-compare from my project's package.json, i'll report back with what happens.

**Comment by fendorio** [comment]
I can confirm that downgrading back to 2.3.0, clearing node modules, then running npm install results in both lodash.debounce and react-addons-shallow-compare being installed as expected.

Please let me know if you need any help with this, happy to lend a hand where I can.

**Comment by bd-arc** [comment]
Hi @fendorio,

Thank you for your investigation! I'm surprised because I've been using version 2.3.1 on miscellaneous projects without any issue. Moreover, there wasn't any update linked to dependencies in 2.3.1...

Would you mind clearing your `nodes_modules` folder and try to install your dependencies with [Yarn](https://yarnpkg.com/lang/en/) instead of `npm`?

**Comment by fendorio** [comment]
Hey @bd-arc  thanks for the swift response. 

Absolutely no worries, your carousel is going to form a major element in an app my team have been commissioned to develop, with that i'm happy to contribute where and when I can. 

I will try and reproduce this tomorrow, I did have a day of scratching my head unexpectedly today though so it may not be until Thursday that I get the time to properly go through this process again. 

I will report back here by Thursday PM (GMT) with my findings.

**Comment by bd-arc** [comment]
Hi @fendorio,

Any further feedback regarding your issue?

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.

Feel free to reopen if needed.
