### ISSUE TITLE
pager (indicator) support?

### ISSUE THREAD

**Issue by ozexpert** [archriss/react-native-snap-carousel#94]
nice to have a pager (indicator / progress bar). btw, good job on this! I love it.

**Comment by bd-arc** [comment]
Hi @ozexpert,
Since, it's pretty easy to implement, I'll make sure to add one soon ;-)

**Comment by bd-arc** [comment]
A `<Pagination />` component has been added in version 2.4.0.

Make sure to read the [specific doc](https://github.com/archriss/react-native-snap-carousel/blob/master/src/pagination/README.md) ;-)

**Comment by ozexpert** [comment]
You are the man!!!

**Comment by ozexpert** [comment]
and also, would it be possible to tap on the pager (dot) to scroll over?

**Comment by bd-arc** [comment]
Hi @ozexpert,

Those are good ideas. I'll take a look at it as soon as possible ;-)

**Comment by ozexpert** [comment]
Yup. also haven't tried, but what if the list is long (let say about 100s) what would happen to the pager?

another thing is if carousel is vertical, the pager should have a way to show vertical as well. (I think that is the expected behaviour). Thanks a lot. I love the plugin!

**Comment by bd-arc** [comment]
Hi @ozexpert,

It hasn't been published yet but the update is already available on `master`: new props for advanced customization of the `Pagination` component. Make sure to take a look at [the updated doc](https://github.com/archriss/react-native-snap-carousel/blob/master/src/pagination/README.md) ;-)

You can now animate color change, make dots tappable, layout dots vertically, and use the `renderDots` prop to provide your own logic and render (useful to handle hundreds of dots, to display numbers...).

Thanks for the ideas!

**Comment by ozexpert** [comment]
You know what? I already changed it according to your docs. :-) thanks for the fantastic support!

**Comment by sbefort** [comment]
Is there a way to make the pager dot move as soon as scrolling begins?  As of now the pager dot does not become active until scrolling snaps and it appears like lag.

**Comment by bd-arc** [comment]
@sbefort Unfortunately, there is no easy way to do that since the entire logic of the plugin is based upon determining the snap breakpoint (when the center of a slide reaches the center of the carousel).

I'll keep your comment in mind though, because it definitely makes sense.

**Comment by abdullatif422** [comment]
Hi @bd-arc ..

did the pager works, showing the Active number / Total numbers  below the carousel ... the updated doc says 404 page not found., can you please provide the updated docs

**Comment by bd-arc** [comment]
@abdullatif422 Please use the links available on the repo's main page (like https://github.com/archriss/react-native-snap-carousel#pagination-component).

It would be a miracle for a 2 years old link to still be active ;-)
