### ISSUE TITLE
Horizontal Carousel can be dragged vertically [iOS]

### ISSUE THREAD

**Issue by typhoon2099** [archriss/react-native-snap-carousel#95]
I've set up a Carousel but for some reason on iOS the Carousel can be dragged vertically, which looks weird. Here's the code for my Carousel
```
<Carousel
  ref={(carousel) => {
    this.carouselRef = carousel;
  }}
  onSnapToItem={this.onSnap}
  sliderWidth={sliderWidth}
  itemWidth={itemWidth}
  firstItem={0}
  inactiveSlideScale={1}
  inactiveSlideOpacity={1}
  enableMomentum
  containerCustomStyle={styles.slider}
  showsHorizontalScrollIndicator={false}
  snapOnAndroid
  removeClippedSubviews={false}
  decelerationRate={'fast'}
  renderToHardwareTextureAndroid
  animationOptions={{
    isInteraction: false,
    useNativeDriver: true,
  }}
>
  {this.getSlides(this.props.places)}
</Carousel>
```

The Carousel is fine on Android, it's just iOS where I get this scrolling issue cropping up.

**Comment by typhoon2099** [comment]
Never mind, the Carousel was in a ScrollView for some reason...

**Comment by alxvallejo** [comment]
I'm facing this issue, but i'm not using ScrollView. I am using animations for toggling dimensions when keyboard is in place tho.

**Comment by bd-arc** [comment]
Hi @alxvallejo,

Could you provide a test case? Because I don't have any clue about how to reproduce the issue...

**Comment by jr-k** [comment]
I have the same problem but only on iPad (iPad Pro (11-inch) iOS 12.1), it works normally on android and iphones.
