### ISSUE TITLE
This.updater.enqueCallback issue

### ISSUE THREAD

**Issue by d7laungani** [archriss/react-native-snap-carousel#96]
The exact issue is this.updater.enqueCallback is not a function. (in 'this.updater.enqueCallback(this,callback,'setState'), this.updater.enqueCallback is undefined.

the exact line is 393 in the carousel/index.js file and the code is below
```
 if (activeItem !== newActiveItem) {
            // WARNING: `setState()` is asynchronous
          -->>>>  this.setState({ activeItem: newActiveItem }, () => {
                // When "short snapping", we can rely on the "activeItem/newActiveItem" comparison
                if (!enableMomentum && this._canFireCallback && this._isShortSnapping) {
                    this._onSnap(newActiveItem);
                }
            });
```

**Comment by bd-arc** [comment]
Hi @d7laungani,

Unfortunately, I haven't been able to reproduce the issue. Could you please provide a bit more context as well as precise reproduction steps ?

**Comment by bd-arc** [comment]
Closing as no further feedback was provided.

Feel free to continue the discussion if needed.
