### ISSUE TITLE
FirstItem doesn't work properly

### ISSUE THREAD

**Issue by nitish1099** [archriss/react-native-snap-carousel#99]
Basically I have a listView at first and on click of any particular list item I open the specific index in the carousel by passing the index as props to the FirstItem. Although when i'm tapping quickly to other list item the carousel firstItem doesn't update.
```javascript
renderCarousel(cardIndex) {
    console.log("index"+cardIndex);
    return (
      <Carousel
        sliderWidth={sliderWidth}
        itemWidth={itemWidth}
        firstItem={cardIndex}
        inactiveSlideScale={0.94}
        inactiveSlideOpacity={0.6}
        enableMomentum={false}
        containerCustomStyle={styles.slider}
        contentContainerCustomStyle={styles.sliderContainer}
        showsHorizontalScrollIndicator={false}
        snapOnAndroid
        removeClippedSubviews={false}
        onSnapToItem={(index) => this.onCardChange(index)} 
        ref={(carousel) => { this._carousel = carousel; }}
      > 
          {this.getCards()}
      </Carousel>
    );
  }



getCards() {
    return this.props.currentCards.map((card) => {
      return (
        <Card style={styles.slideInnerContainer} key={card._id}>
          <Text style={styles.title} >{card.title}</Text>
          <Text style={styles.subtitle}>{card.description}</Text>
        </Card>
      );
    });
  }`

**Comment by bd-arc** [comment]
Hi @nitish1099,

I can confirm that updating `firstItem` will not update the active slide, and I'm going to work on a fix. Still, I wouldn't recommend using it in this case. Have you tried using the [`snapToItem` method](https://github.com/archriss/react-native-snap-carousel/#available-methods)?

**Comment by nitish1099** [comment]
I tried but didn't work for me. Which life cycle method would you recommend to put the snapToItem code in also, could you illustrate with an example?

**Comment by bd-arc** [comment]
Hi @nitish1099,

First, note that version 2.4.0 contains a fix for the dynamic update of `firstItem`.

Then, regarding your need, it should be pretty straightforward. This is how we usually do it:
```javascript
<TouchableOpacity onPress={() => this._carousel.snapToItem(index) />

<Carousel ref={(c) => { this._carousel = c; }}>
    // your slides
</Carousel>
```

**Comment by nitish1099** [comment]
@bd-arc I'm navigating between different scenes so maybe I would have to do it in a lifecycle method and 2.4.0 didn't fix it for me.

**Comment by bd-arc** [comment]
@nitish1099 Unfortunately, I can't go further without a sample project that can help me reproduce the issue. If you have time to create one, I'll gladly take a look at it.
